core/src/main/java/com/netease/arctic/iceberg/optimize/DeleteFilter.java, core/src/main/java/com/netease/arctic/io/reader/ArcticDeleteFilter.java, trino/src/main/java/com/netease/arctic/trino/keyed/KeyedConnectorPageSource.java
1. Ensure posDeleteFiles and DataFIles in one Task is the same node.
2. Avoid data record need _filePath columns.
=> [prepare for conference]Optimize pd one to one node

core/src/main/java/com/netease/arctic/data/PrimaryKeyData.java, core/src/main/java/com/netease/arctic/utils/NodeFilter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/shuffle/ShuffleHelper.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/shuffle/ShuffleHelper.java
Fixed the log/file shuffle OutOfIndexExp which is caused by the hashcode of the record is not positive.
**the main change log**:
**ShuffleHelper.hashPartitionValue(RowData)** and **ShuffleHelper.hashPartitionValue(RowData)**
=> [bugfix] Using Math.abs() make the hashcode positive.

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java
Fix #181.
`ArcticFileWriter` requests a new transaction ID for the next checkpoint period when the snapshot barrier arrives. But there is no data written during the next checkpoint period. `ArcticFileWriter` should be optimized that only requests new transaction ID if new data exists.
**The brief change log**
- `ArcticFileWriter` requests a new transaction ID when processing the new file data.
=> [ARCTIC-181][Flink] Reduce the number of allocated requests for new transaction IDs

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/KafkaDynamicSource.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/util/Projection.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/util/ProjectionTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/KafkaDynamicSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/util/Projection.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/util/ProjectionTest.java
Fix #108.
`ArcticDynamicSource` should implement the `SupportsProjectionPushDown` interface to accelerate data querying.
**The brief change log**
- `ArcticDynamicSource` and `KafkaDynamicSource` implement the `SupportsProjectionPushDown` interface to support `supportsNestedProjection` and `applyProjection` methods.
=> [ARCTIC-108][Flink] Support projection push down to arctic source reader

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/improvement.yml, .github/PULL_REQUEST_TEMPLATE
fix #219 
This helps Arctic project contributors create standard issues or pull requests nicely.
This is Github Issue & PR templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
Inspired by the templates of Apache Airflow and Iceberg: https://github.com/apache/airflow/issues/new/choose, https://github.com/apache/iceberg/issues/new/choose
=> [ARCTIC-219] GitHub: Add the issue and pull request forms

core/src/main/java/com/netease/arctic/table/BaseKeyedTable.java, core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java
There commit properties multipal in old logic, because the keyedTable and unkeyedTable both commit properties to ams. But keyedTable's base and change table are also unkeyedTable, so there may commit properties multipal.
=> fix duplicate commit properties logic

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/BaseOptimizeTaskRuntime.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/IJDBCService.java
As described in #240, for mysql with isolation level RR as sysdb, optimize will lose data because of dead lock.
- Set sysdb connection session isolation level to READ_COMMITTED
- update optimize task runtime in memory only after update sysdb success
=> [ARCTIC-240] fix data lose after optimize for mysql sysdb with REPEATABLE READ

flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java
In Flink 1.15 version, `ArcticFileWriter` should check whether the `WriteResult` is empty or not. Fix #188.
- `ArcticFileWriter` should check whether the `WriteResult` is empty or not in Flink 1.15.
=> [ARCTIC-188][Flink][FollowUp] Avoiding submitting too much empty snapshots

dist/src/main/arctic-bin/bin/ams.sh
Fix #28. Mac os doesn't have /proc/PID, so we hava to find another way to determine whether the process is running both for linux and mac os.
- change ams.sh, replace `test -d /proc/PID` with `test -n $(ps -p PID -o pid=)`
=> [ARCTIC-28] fix ams.sh running on mac os

hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
Hive table need name mapping to read existed parquet files.
Name mapping is setted into table properties when creating table.
Name mapping should be generated with schema after table creating instead of before creating, becase field id would be reassigned when creating table.
- *Generate name mapping properties after table created.*
- *Check hive table partition field is at laste of schema*
=> [Hive]Fix hive table name mapping

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java
```
Flink SQL> create catalog arctic with (
'type' ='arctic',
'metastore.url'='thrift://****/bdms_test_catalog');
Flink SQL> use catalog arctic;
[INFO] Execute statement succeed.
Flink SQL> use db;
[INFO] Execute statement succeed.
Flink SQL> show tables;
+----------------------+
| table name |
+----------------------+
| log_tab |
| log_table |
| log_table_outofindex |
| table_name |
+----------------------+
4 rows in set
Flink SQL> insert into log_table_outofindex /+ OPTIONS('arctic.emit.mode'='log')/ select id, '1', LOCALTIMESTAMP from default_catalog.default_database.source;
[ERROR] Could not execute SQL statement. Reason:
com.netease.arctic.shaded.org.apache.iceberg.exceptions.NoSuchTableException: load table failed bdms_test_catalog.db.default_catalog.
Flink SQL> use catalog …
```
=> [ARCTIC-205][Flink] Throw the NoSuchTableException when the default catalog is an Arctic catalog in Flink SQL

site/docs/ch/flink/flink-get-started.md
Resolve #278
#196 Arctic 0.3.1 have implemented parquet reader/writer for hive. Flink have to port to new API to support hive reading/writting. Here's the doc about Flink on adapt Arctic table.
- *Add the Flink on adapt Arctic table documentation in the flink chapter*
=> [Arctic-278][Doc]: Adding Flink on adapt Arctic table documentation

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java
fix #296 
There is a flink running job without any data ingestion. But submitted too many empty snapshots and cost too much storage.
- *update the default value of the ArcticValidator.*
=> [ARCTIC-296] hotfix: avoid submitting empty snapshots by default

spark/v3.1/spark/src/main/scala/org/apache/spark/sql/catalyst/parser/ArcticExtendSparkSqlAstBuilder.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedTableDDL.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java
fix create table cant set colmun struct type and timestamp type
*(For example: The Arctic Flink dataStream API has already supported this configuration: 'scan.startup.mode', but it is not available with Flink SQL. We should expose this configuration to users when they are using Flink SQL.)*
- *Add the 'scan.startup.mode' configuration to the ArcticScanContext in the flink modules*
- *The flink 1.12 and 1.14 versions are affected.*
=> fix create table cant set colmun struct type

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestAlterKeyedTable.java
Fix #320. 
fix bug when unset keyed table properties, remind "Cannot apply unknown table change: unset"
- *Add the 'scan.startup.mode' configuration to the ArcticScanContext in the flink modules*
- *The flink 1.12 and 1.14 versions are affected.*
=> [ARCTIC-320][Spark]support unset properties

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveFullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveMajorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/SupportHiveSyncService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/HiveLocationUtils.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileCleanSupportHive.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveOperateToTableRelation.java, hive/src/main/java/com/netease/arctic/hive/utils/HiveTableUtil.java, hive/src/main/java/com/netease/arctic/hive/utils/TableTypeUtil.java, trino/src/main/java/com/netease/arctic/trino/unkeyed/IcebergMetadata.java
close #323 
Hive-exec is necessary for hive adaptive table, however, it can be optional for native Arctic table.
- *Seperate TableTypeUtil from HiveUtil*
=> [ARCTIC-323] make hive-exec optional

spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/CreateArcticTableLikeExec.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java
use hive catalog , support “create table like”  grammar
https://arctic.netease.com/ch/spark/spark-ddl/#create-table-like
=> [Spark] Support create table like statement for hive catalog

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMinorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestSupportHiveMajorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/util/DataFileInfoUtils.java, core/src/main/java/com/netease/arctic/op/OverwriteBaseFiles.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MajorExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MinorExecutor.java
1.fix #314 
2.optimize support pos-delete in unKeyedTable
3.add name-mapping for support hive reader in optimize
- add check when minor optimize commit, if partition has files transactionId less than base.max-transaction-id, will give up this partition commit
- if throw ValidationException(Missing required files to delete or found new delete for replaced data file), will give up this commit, because files in base have changed
- major optimize for unKeyed table support pos-delete files
- add name-mapping for support hive reader in optimize
=> [ARCTIC-314][AMS] Clear optimize tasks when commit failed and support pos-delete in unkeyed table

ams/ams-server/src/main/resources/sql/mysql/ams-init.sql, ams/ams-server/src/main/resources/sql/mysql/upgrade-0.3.0-to-0.3.1.sql
fix #329
- move optimize_task_history upgrade sql to src/main/resources/sql/mysql/upgrade-0.3.0-to-0.3.1.sql
=> [Arctic-329] fix mysql/ams-init.sql for optimize_task_history

hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
Resolve #364 
* Someone who want to create keyed hive table with "optimize.full.trigger.max-interval" may need this change 
- *A judgment was added
=> [BUG-364] Can not set "optimize.full.trigger.max-interval" while create keyed hive

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizePlan.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, site/docs/ch/meta-service/table-properties.md
#371 table property key is inaccurate
- modify table property key optimize.major.trigger.delete-file-size-bytes to optimize.full.trigger.delete-file-size-bytes
=> [ARCTIC-371][core] modify table property

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/GlobalFlipCommitter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/LogMsgFactory.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaFactory.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducerTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/GlobalFlipCommitter.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/LogMsgFactory.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaFactory.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducerTest.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/GlobalFlipCommitter.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/LogMsgFactory.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaFactory.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducerTest.java
Resolve #363 
LOG_STORE_MESSAGE_TOPIC has been put into producerConfig in AbstractHiddenLogWriter.java. This custom properties may lead to TransactionalIdAuthorizationException in SASL.
And putting the invalid properties into kafka producer config is also ugly.
- *separate topic from producerConfig*
=> [ARCTIC-363][Flink] separate topic from producerConfig

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunctionTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunctionTest.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunctionTest.java
Fix #172 
If arctic's file-store only have data in base-table, but nothing in change-table, arctic source will reading nothing in ContinuousSplitPlannerImpl#discoverInitialSplits because changeSnapshot in change-table is null.
The data in base-table can be insert overwrite through Spark.
We should fix it.
- *Plan split if there is no snapshot in change-store, only some in base-store.*
=> [ARCTIC-172][Flink] Fix Flink read nothing in streaming mode when table has data in base, but not change

ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/TableTransactionMetaMapper.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/ArcticTransactionService.java
resolve #390 
change allocateTransactionId logic
insert data use flink and then use spark insert data, the transactionid will increase
=> [ARCTIC-390][AMS]resolve get error transactionId when insert data use flink and then use spark insert data

ams/ams-server/pom.xml, hive/src/main/java/com/netease/arctic/hive/ArcticHiveClientPool.java, hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java
resolve #402
Reconstructed `ArcticHiveClientPool` class to replace `HiveClientPool` from Iceberg, And in the init method to increase this:`HiveConf. AddResource (tableMetaStore. GetHiveSiteLocation (). OrElse (null));`
Configure multiple Hive catalogs and obtain table information through AMS, and use multiple threads to call the listDatabases method of different catalogs at the same time
=> [ARCTIC-402][HIVE]Incorrect table information is obtained when multiple Hive Catalogs exist

hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java, hive/src/main/java/com/netease/arctic/hive/utils/ChangeFieldName.java, hive/src/main/java/com/netease/arctic/hive/utils/HiveSchemaUtil.java, hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java, hive/src/test/java/com/netease/arctic/hive/utils/HiveSchemaUtilTest.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
Resolve #380 .
As Hive table support lowercase field name only, we should change table schema field name to lowercase when creating hive table.
- *Add ChangeFieldName converter for iceberg schema*
- *Change table field name to lowercase when creating hive table.*
=> [ARCTIC-380][Hive]Change hive table schema filed name to lowercase when creating table

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java
Fix #422 
Without ENABLE_LOG_STORE property validation, it may lead to exceptions for lacking of some required properties. It will confuse users in trouble shooting.
- *Add ENABLE_LOG_STORE  validation before building LogReader*
=> [ARCTIC-422] [FLINK] check ENABLE_LOG_STORE property before building LogReader

core/src/main/java/com/netease/arctic/table/TableProperties.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/HiddenLogOperatorsTest.java, hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
Spark will add owner to table properties when building a table, Arctic takes the difference owner from the Spark input when synchronizing HMS. Now this pr will synchronize the owner of the Hive table with the Arctic table
=> [SPARK]Synchronize the owner of the Hive table with the Arctic table

spark/v2.3/spark/src/main/java/com/netease/arctic/spark/util/ArcticSparkUtil.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
Spark 2.3 catalog property need "spark" prefix to take effect in spark-sql client.
- *Add 'spark.sql' prefix to catalog url*
=> [Spark] Add prefix to spark 2.3 catalog url properties

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableQuotaInfo.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizePlan.java
fix #430 
fix #431 
flink increment pull will failed if major commit use OverwriteFils because iceberg don't support this operation increment pull
- *record currentBaseSnapshotId rather than currentChangeSnapshotId for unKeyed table in BaseOptimizePlan class*
- *modify equals condition for compareTo method in TableQuotaInfo class*
- *modify overwrite dataFiles to rewrite dataFiles in major commit*
=> [ARCTIC-430][AMS]Record baseSnapshotId for unKeyed table

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeExecuteService.java
fix #436 
When the Optimizer job stops, the dashboard still displays the job status as running
change OptimizerMonitor.monitorStatus() logic
=> [ARCTIC-436][AMS]:OptimizerMonitor check optimizer status logic error

spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteUpdateArcticTable.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
In the Spark update plan, the final query was originally constructed as a outer join, now the Query will be constructed as a select + project
=> [SPARK]Change the Spark update from outer join to select + project

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java
Select partial fields from arctic table, but there will be all fields without projecting. It will cause unmatched rowtype and real rowdata. And shuffle is using all fields `RowType`, which may cause `ArrayIndexOutOfBoundsException`. 
Fix #257.
- Update `readSchema` and `flinkSchemaRowType` with the projection fields for `SupportsProjectionPushDown#applyProjection`.
- Use `scanContext#project` for the projected schema of `RowDataReaderFunction`.
=> [ARCTIC-257][Flink] Flink source project pushdown would cause reading all fields to downstream

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/TerminalService.java
Resolve #504 
* Resolve catalog names with special characters may lead terminal execute sql failed
- *Add back-quotes when execute "use catalog" 
=> [ARCTIC-504]When the catalog name contains line-through, terminal executes sql with an error

ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java
resolve #528 
execute failover() when there is error occur in ArcticMetaStore.tryStartServer()
=> [ARCTIC-528][AMS]if ams start error there should be shutdown first and then restart

core/src/main/java/com/netease/arctic/io/reader/DataReaderCommon.java, core/src/main/java/com/netease/arctic/io/reader/GenericIcebergDataReader.java, core/src/test/java/com/netease/arctic/io/TaskReaderTest.java
spark need read change table with "_transaction_id, _file_offset,_action" columns.
subtask of #521 
com.netease.arctic.io.reader.BaseIcebergDataReader can read  "_transaction_id, _file_offset,_action" columns
=> [CORE]Make BaseIcebergReader can read "transaction_id, offset,action"

hive/src/main/java/com/netease/arctic/hive/utils/HiveSchemaUtil.java
Resolve #555 
*Some hive table can not convert to iceberg schema when auto-convert is false
- *Set auto convert is true
=> [ARCTIC-555] When upgrade hive table set auto convert as true

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableOptimizeRuntime.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java, trino/src/test/java/com/netease/arctic/trino/iceberg/BaseConnectorTest.java
As https://github.com/NetEase/arctic/issues/576 described, the lock timeout will cause the initTableOptimizeRuntime method return directly with restore the TableOptimizeRuntime object history status. This will cause this table optimize job always in Pending status and no optimize job plan  for the Arctic table anymore.
- add cloneTableOptimizeRuntime and restoreTableOptimizeRuntime methods to clone and restore TableOptimizeRuntime status.
- add try catch cause to wrap the method, when exception occurrs, restore the history status before persist to database.
<pre>
2022-11-08 20:49:40,733 ERROR [Optimize Plan Thread Queue-1] [com.netease.arctic.ams.server.service.impl.OptimizeQueueService] [] - hadoop_catalog.iceberg_test.xxxxx plan failed, continue …
=> [ARCTIC-576] Bugfix for initTableOptimizeRuntime

core/src/main/java/com/netease/arctic/catalog/BaseArcticCatalog.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestJoin.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestWatermark.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestJoin.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestWatermark.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestJoin.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestWatermark.java, hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
Fix #558 
* Now drop arctic table will leave an empty directory in hdfs
-After drop table, delete table directory 
=> [ARCTIC-558] Drop table operation will leave an empty table directory in hdfs

flink/v1.15/flink-runtime/pom.xml
Resolve #563 
when use Arctic-flink 1.15, we will get the ClassNotFoundException about flink-connector-kafka dependency
- *Replaced dependency names for flink-connector-kafka in the pom file*
=> [Flink][bugfix] Fixed the ClassNotFoundException problem about Flink Kafka Connector under Flink 1.15

LICENSE, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/AdaptHiveFlinkAppenderFactory.java, flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveFlinkParquetWriters.java, flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveParquetWithFlinkSchemaVisitor.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/AdaptHiveFlinkAppenderFactory.java, flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveFlinkParquetWriters.java, flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveParquetWithFlinkSchemaVisitor.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/AdaptHiveFlinkAppenderFactory.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveFlinkParquetWriters.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/data/AdaptHiveParquetWithFlinkSchemaVisitor.java, hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveTypeToMessageType.java, spark/v2.3/spark/src/main/java/com/netease/arctic/spark/io/InternalRowFileAppenderFactory.java, spark/v2.3/spark/src/main/java/org/apache/iceberg/spark/data/AdaptHiveParquetWithSparkSchemaVisitor.java, spark/v2.3/spark/src/main/java/org/apache/iceberg/spark/data/AdaptHiveSparkParquetWriters.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/io/InternalRowFileAppenderFactory.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/AdaptHiveParquetWithSparkSchemaVisitor.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/AdaptHiveSparkParquetWriters.java, style/arctic-checkstyle.xml, style/suppressions.xml
see #585 
- Remove column name compatible logic with avro  in `AdaptHiveTypeToMessageType` to avoid transfroming "$" to "_X24"
- Use new `AdaptHiveTypeToMessageType` in Flink/Spark
- Copy  `org.apache.iceberg.flink.data.AdaptHiveParquetWithFlinkSchemaVisitor` from iceberg  `org.apache.iceberg.flink.data.ParquetWithFlinkSchemaVisitor` to avoid checking name compatible
- Copy  `org.apache.iceberg.flink.data.AdaptHiveParquetWithSparkSchemaVisitor` from iceberg  `org.apache.iceberg.flink.data.ParquetWithSparkSchemaVisitor`  to avoid checking name compatible
=> [ARCTIC-585][Hive][Flink][Spark]FIX: Adapt hive column name with "$"

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/ArcticWriter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/ArcticWriter.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/ArcticWriter.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/AbstractHiddenLogWriter.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java
FIX #561 
- *The flink 1.12 and 1.14 , 1.15versions are affected.*
=> [ARCTIC-561] Fix 561. When flink job fails over, flink job will commit a wrong transaction id

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedSparkBatchWrite.java
fixbug;  for unkeyed hive table.  file transaction id not changed for each spark sql executed
- change unkeyed table transactioId field from static to private
=> [Spark]: fix un-keyed table transaction id not change for each execute

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/util/DataUtil.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/util/DataUtil.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/util/DataUtil.java, site/docs/ch/flink/flink-get-started.md
fixed #592 
*When an Arctic table with the write.upsert feature enabled is read, data with the same primary key will exist, which should be fixed*
- *replace the shuffle policy involved in write operations*
=> [Flink][bugfix] Fixed the problem of duplicate primary key data in Arctic table with upsert feature enabled

ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/CatalogController.java, ams/ams-server/src/main/resources/sql/derby/ams-init.sql, ams/ams-server/src/main/resources/sql/mysql/0.4.0-init.sql
resolve https://github.com/NetEase/arctic/issues/617
we set table-format ICEBERG , catalog type ams in local catalog,
add paltform_file_info ddl in init sql.
add storage.type with value hdfs add storage_configs of Catalog object when adding catalog.
=> [ARCTIC-617][Improvement]: do some initialization when add catalog

ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/PlatformFileInfoMapper.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/derby/DerbyPlatformFileInfoMapper.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/PlatformFileInfoService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/JDBCSqlSessionFactoryProvider.java, ams/ams-server/src/main/resources/sql/derby/ams-init.sql, ams/ams-server/src/test/java/com/netease/arctic/ams/server/util/DerbyTestUtil.java, dist/src/main/arctic-bin/conf/config.yaml
resolve https://github.com/NetEase/arctic/issues/622
=> [ARCTIC-622][Improvement]: fix file upload when use derby as storage

ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/derby/DerbyPlatformFileInfoMapper.java
Fix #660 
`fetch first 1 rows only` instead `limit 1`
=> [ARCTIC-660][AMS] Derby does not support the `limit` syntax

core/src/main/java/com/netease/arctic/scan/BaseChangeTableIncrementalScan.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedTableDMLInsertOverwriteDynamic.java
To fix #479 , Iceberg EntriesTables return Entry from manifest with null sequence, the right sequence should be inherited from manifest metadata (in manifest list).
- use the `rows` API of `org.apache.iceberg.DataTask` which uses the inherited sequence number
=> [Arctic-479][MOR]: fix getting null sequence from manifest entry when plan change table

ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/OptimizerController.java
fix #669 
when the container type of optimizer is local, the core number equals parallelism.   
=> [Bug][ARCTIC-669]Wrong optimizer resource allocation display for local optimizer in Arctic Dashboard

trino/src/main/java/com/netease/arctic/trino/keyed/KeyedDeleteFilter.java, trino/src/test/java/com/netease/arctic/trino/arctic/HiveTestRecords.java, trino/src/test/java/com/netease/arctic/trino/arctic/TestBaseArcticPrimaryTable.java, trino/src/test/java/com/netease/arctic/trino/arctic/TestHiveTable.java, trino/src/test/java/com/netease/arctic/trino/arctic/TestHiveTableBaseForTrino.java
Fix: #652 
Reconstruct Trino type to Iceberg type in com.netease.arctic.trino.keyed.KeyedDeleteFilter
=> [ARCTIC-652][Trino]Reconstruct Trino type to Iceberg type

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseIcebergOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMajorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMinorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMajorOptimizePlan.java
resolve #707 
- *split optimize task for native iceberg by file size in bytes of data files and delete files*
=> [ARCTIC-707] split optimize task for native iceberg by all file size

ams/ams-server/pom.xml, spark/v2.3/spark-runtime/pom.xml, spark/v2.3/spark/pom.xml, spark/v3.1/spark-runtime/pom.xml, spark/v3.1/spark/pom.xml
spark module name format is arctic-spark_{SPARK_VERSION} , this maybe conflict with spark binary version suffix e.g. spark-sql_2.12
so change the module name to format arctic-spark-{SPARK_VERSION}
- change spark module name format
=> refactor spark module

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java, site/docs/ch/flink/hidden-kafka.md, site/docs/ch/meta-service/table-properties.md
fix: #745 
Update the configuration name of consistency between Logstore and Filestore:
`log.consistency.guarantee.enable` -> `log-store.consistency-guarantee.enable`
Unify the name format with the other table properties.
- *ArcticValidator in the multiple flink modules*
- *documentation pages*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) docs
=> [ARCTIC-745] Update the configuration name of consistency between Logstore and Filestore

ams/ams-api/src/main/java/com/netease/arctic/ams/api/properties/OptimizeTaskProperties.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java, optimizer/src/main/java/com/netease/arctic/optimizer/exception/TimeoutException.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/BaseExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/IcebergExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MajorExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MinorExecutor.java, optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/NodeTask.java, optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestIcebergExecutor.java
fix #636 
Failed full optimization that supports Hive produced useless data files in the partition location, which is unclear.
- *before retrying failed full optimize support Hive, try to clear useless data files*
- *optimizer add max execute time to avoid producing useless data files, and throw timeout exception*
=> [ARCTIC-636][optimizer] Clear useless data files produced by failed full optimize which support hive

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #798 
- *Use StringUtils#isNotEmpty to check custom-hive-sub-directory whether empty*
=> [ARCTIC-798] Fix fail optimize task doesn't retry

ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
some page request like http://xxx/aaa?xxx=yyy can't redirect to  login page.
fix #782
- *remove singlerootpage register*
- *add  get("/{aaa}", ctx -> ctx.html(getFileContent())); return index.html  when handle request like  http://xxx/aaa?xxx=yyy  after login*
- *return index.html  when handle request like  http://xxx/aaa?xxx=yyy  before login*
=> [ARCTIC-782] Not auto jump to login page if visit some page without login

ams/ams-api/src/main/java/com/netease/arctic/ams/api/properties/CatalogMetaProperties.java, core/src/main/java/com/netease/arctic/catalog/BaseArcticCatalog.java, core/src/main/java/com/netease/arctic/utils/CatalogUtil.java, core/src/test/java/com/netease/arctic/utils/CatalogUtilTest.java
Resolve #171
- *Add logical to filter  default properties for a catalog with specific prefix in `TablePropertiesUtil`.*
- *Add logical to  set default properties into table metadata when creating tablemeta in `TableMetaBuilder`*
=> [Arctic][AMS] admin-configured default table properties with adding into catalog #171

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMinorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMinorOptimizePlan.java
fix #814 
- *Even if the minor optimize output is nothing, the commit still updates "max-txId" in partition properties*
=> [ARCTIC-814] Fix optimize can't stop when the change store only has eq-delete files and the base store has no files

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, core/src/main/java/com/netease/arctic/utils/CompatiblePropertyUtil.java, site/docs/ch/meta-service/table-properties.md
fix #820 
- remove `self-optimizing.max-task-file-size`
- `BinPacking` of full-optimize/major-optimize use `self-optimizing.target-size` now
=> [ARCTIC-820] Remove table configuration `self-optimizing.max-task-file-size`

ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/OptimizeTasksMapper.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/derby/DerbyOptimizeTasksMapper.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/BaseOptimizeTask.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TaskConfig.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseArcticOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergFullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMinorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MinorOptimizePlan.java, ams/ams-server/src/main/resources/sql/derby/ams-init.sql, ams/ams-server/src/main/resources/sql/mysql/0.4.0-init.sql, ams/ams-server/src/main/resources/sql/mysql/upgrade-0.3.2-to-0.4.0.sql, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsEnvironment.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/OptimizeIntegrationTest.java
fix #846.
When `Minor Optimize` commit, we check if there is any conflict commit on BaseStore during the execution of tasks, using the minTransactionId of these tasks.
However, we use the legacy TransactionId. We have to fix it by using the right TransactionId.
- add minTransactionId for optimize_task
- minor optimize plan set minTransactionId into optimizeTask
- use the right minTransactionId to check if there is any conflict commit
=> [ARCTIC-846] Fix checking conflict commit with the legacy `TransactionId` before `Minor Optimize` commit

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestOrphanFileClean.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanServiceTest.java
fix #877 
- use URI of file path for valid files and actual files
=> [ARCTIC-877] Fix Orphan files clean delete files unexpected

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
fix #890 
- *Load the insert files cache in optimize task when adding the insert files into the target files*
=> [ARCTIC-890][AMS] Fix the data loss when the minor optimize in progress and restart the ams at the same time

core/src/main/java/com/netease/arctic/op/ArcticHadoopTableOperations.java
*Fix #635*
- *Throw CommitStateUnknownException when Hadoop table commit failed*
- Does this pull request introduces a new feature? (yes / **no)**
=> [ARCTIC-635]Skip cleaning maniftes files when commiting failed for hadoop table

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterITCase.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterITCase.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterITCase.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveOutputFileFactory.java
Fix #561 Fix #826 
the fix #568 about Flink 1.14, 1.15 was wrong due to the op cannot fetch right restore ckpId after failover if op has no state.
And the ckpId assigned to writer is not one to one correspondence, which leads to the repeatable file name.
=> [ISSUE-561][Flink] Fix flink cannot fetch right ckpId after failover

dist/src/main/arctic-bin/bin/ams.sh, docker/ams/config.sh
Limit JVM memory for AMS in docker.
Print Gc log details.
- *Change XMX XMS parameter in docker.*
- *Add JVM GC parameter to print GC logs and rotation it.*
=> [Docker] Limit JVM memory for AMS in docker

ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalSessionFactory.java, site/docs/ch/spark/spark-conf.md, site/docs/ch/spark/spark-ddl.md, site/docs/ch/spark/spark-dml.md, spark/v2.3/spark/src/main/java/com/netease/arctic/spark/util/ArcticSparkUtil.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestKeyedHiveTableInsertOverwriteDynamic.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestKeyedHiveTableInsertOverwriteStatic.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestKeyedHiveTableMergeOnRead.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestUnkeyedHiveTableInsertOverwriteDynamic.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestUnkeyedHiveTableMergeOnRead.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/SparkSQLProperties.java, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteAppendArcticTable.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/delegate/TestArcticSessionCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/delegate/TestMultiDelegateSessionCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedHiveInsertOverwriteDynamic.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
resolve #907 
Add a spark property: spark.sql.check-data-duplicates.enabled, the default value is true 
=> [ARCTIC-907][SPARK]Duplicate keys verification for the source table should add a property to control in Spark

hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java
*Fix #910.*
- *Ignore committing error to HMS when committing Hive format table*
=> [ARCTIC-910]Ignore committing error to HMS when committing Hive format table

README.md
Our quick-start URL on Github front page is out-of-date, we need to change it.
- *Fixed README's quick-start URL on front page*
=> [Docs] Fixed README's quick-start URL on front page

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableOptimizeRuntime.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseArcticOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/OptimizeIntegrationTest.java
fix #920 
- *force refresh the base table when checking the file cache in the base table*
- *remove isRunning in TableOptimizeRuntime and use optimize task size to check whether the table is running*
- *generate partition running status before getting data files to avoid incorrect plan*
=> [ARCTIC-920][Optimize] Fix the problem of data inconsistency after minor optimize

core/src/main/java/com/netease/arctic/data/DefaultKeyedFile.java, core/src/main/java/com/netease/arctic/data/PrimaryKeyedFile.java, core/src/main/java/com/netease/arctic/table/BaseUnkeyedTable.java, core/src/test/java/com/netease/arctic/data/KeyedDataFileTest.java
fix: #860 
BaseUnkeyedTable get TableScan without includeColumnStats
=> [ARCTIC-860] Improve  memory usage when plan table

core/src/main/java/com/netease/arctic/table/TableMetaStore.java, site/docs/ch/mpp/trino.md, trino/src/main/java/com/netease/arctic/trino/ArcticConfig.java, trino/src/main/java/com/netease/arctic/trino/ArcticHdfsAuthentication.java
Signed-off-by: Yi Xie <xieyi01@rd.netease.com>
fix: https://github.com/NetEase/arctic/issues/928
It only can config one kerberos user in trino cluster, but trino have many users in one cluster.
We need proxy trino user to connector hadoop
**yes**
**docs, in site/docs/ch/mpp/trino.md**
=> [ARCTIC-928] Trino support hadoop proxy user 

ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/FileInfoCacheMapper.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/TestFileInfoCacheService.java
Fix #967 
- Load sequence from `file_info_cache` when `getChangeTableTTLDataFiles` is invoked
=> [ARCTIC-967] Fix change files exceeding TTL deleted by mistake

core/src/main/java/com/netease/arctic/op/ArcticTableOperations.java, core/src/main/java/com/netease/arctic/scan/TableEntriesScan.java
As described in the #955, when process table entries scan for getting file sequence, we call `table.spec()` many times which invokes `ugi.doAs()` each time.
And also, there is no need to load column metrics if not necessary.
- cache table spec for table entries scan
- only include colum stats when necessary
=> [ARCTIC-955] Improve performance of Table entries scan

core/src/main/java/com/netease/arctic/io/writer/BaseTaskWriter.java, core/src/main/java/com/netease/arctic/io/writer/ChangeTaskWriter.java
To fix #966, check the written row number before closing the file writer.
- *Calculate the written row number in task writer*
- *Complete only if written row number > 0*
=> [ARCTIC-966][Core]Check the written row number before closing the file writer

hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
improve #979 
- *use alter to modify partition location rather than delete and add the partitions in UpdateHiveFiles commit*
=> [ARCTIC-979][Core]Use alter to modify partition location rather than delete and add the partitions in UpdateHiveFiles commit

hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetConversions.java, hive/src/test/java/com/netease/arctic/hive/ArcticHiveTestMain.java
fix: #996
Resolve time zone in org.apache.iceberg.parquet.AdaptHiveParquetConversions
=> [ARCTIC-996][Hive]Fix data inaccuracy when query data using where statement contain without time zone column

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
=> [ARCTIC-1018][AMS] Avoiding concurrent operations by `tasksLock`

ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/AmsClientPools.java
There are several UTs stuck in AMS thrift connection. Assigning a timeout value try to fix it.
Set a timeout value to thrift client.
=> [AMS] set thrift client timeout

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedTableDML.java
fix #620 to support `refresh table xxx` grammar for arctic catalog.
- Remove useless implement method in ArcticSparkCatalog.
=> [Arctic-620][Spark]: Support refresh table

spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteAppendArcticTable.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
When set property: spark.sql.arctic.check-source-data-uniqueness.enabled = false
then execute upsert will throw exception
=> [SPARK]Fix bug: when disable duplicate keys check, execute upsert will throw exception

trino/src/main/java/com/netease/arctic/trino/keyed/KeyedConnectorPageSource.java
**To fix #1052 **
When trino executes the limit statement, it will read the page through the driver. When the read page meets the limit number requirements, it will close the corresponding pagesource, that is, KeyedConnectorPageSource, no longer read subsequent pages, and call the close method.
```
@Override
public void close() throws IOException {
close = true;
}
```
However, KeyedConnectorPageSource uses current (an instance of IcebergPageSource) to get the page. Current is closed only when all pages have been read. 
```
while (page == null) {
page = current.getNextPage();
if (page == null) {
current.close();
if (dataTasksIt.hasNext()) {
completedPositions += current.getCompletedPositions().isPresent() ?
current.getCompletedPositions().getAsLong() : 0L;
completedBytes += …
```
=> [ARCTIC-1052] fix close_wait problem caused by limit query

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSourceBuilder.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/log/pulsar/LogPulsarSourceBuilder.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSink.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/descriptors/PulsarConfigurationConverter.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/util/CompatibleFlinkPropertyUtil.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/pulsar/HiddenPulsarFactory.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/hidden/HiddenLogOperatorsTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSourceBuilder.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSink.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/util/CompatibleFlinkPropertyUtil.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSourceBuilder.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSink.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/util/ArcticUtils.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/util/CompatibleFlinkPropertyUtil.java, site/docs/ch/flink/flink-ds.md
Resolve #1039
- Validation of table's properties is in catalog, it may cause unfriendly exception in datastream API.
- Some parameters of Datastream API is unfriendly, such as underlying log properties which can be parsed from tableProperties.
- The conversion of properties should be processed under datastream API, not in table API.
=> [ARCTIC-1039][FLINK] Datastream API optimize

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveCommit.java, core/src/main/java/com/netease/arctic/io/ArcticFileIO.java, core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java, core/src/test/java/com/netease/arctic/io/ArcticFileIoDummy.java, hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java
Fix #1016 
*Exception thrown when FileSystem returns false.
*If the new path does not exist during Support Hive Commit,  and then create it.
*Fix some simple grammar errors.
=> [ARCTIC-1016] Moving files will fail if the target parent directory doesn't exist in HDFS

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, core/src/main/java/com/netease/arctic/op/KeyedPartitionRewrite.java, core/src/main/java/com/netease/arctic/op/OverwriteBaseFiles.java, core/src/main/java/com/netease/arctic/scan/BaseChangeTableIncrementalScan.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java, core/src/test/java/com/netease/arctic/op/OverwriteBaseFileTest.java, hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java, hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java, spark/v2.3/spark/src/main/java/com/netease/arctic/spark/writer/ArcticKeyedSparkOverwriteWriter.java, spark/v2.3/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/KeyedSparkBatchWrite.java, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/AlterArcticTableDropPartitionExec.scala, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/TruncateArcticTableExec.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
Now, the transaction ids of each partition are stored in the base table's property, and the legacy transaction id is supposed to be read when the transaction id is not present, in order to be compatible with the legacy tables from 0.3.*.
However, when the transaction id is not present, we return `-1`, which is error-prone, and causes compatibility problem for MOR.
- return `null` instead of `-1` when transaction id is not present.
- refactor `OverwriteBaseFiles` when handling transaction id
- for data consistency, allow `KeyedPartitionRewrite` to set the transaction id to a smaller value 
=> [ARCTIC-994] fix read legacy transaction id when MOR

ams/ams-api/src/test/java/com/netease/arctic/ams/api/MockArcticMetastoreServer.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableBlockerService.java, core/src/main/java/com/netease/arctic/table/blocker/RenewableBlocker.java
avoid NoSuchObjectException when renew blocker, like 
- check blocker exist before renewing blocker
- MockArcticMetastoreServer support renewBlocker
=> [ARCTIC-985] avoid NoSuchObjectException when renew blocker

spark/v3.1/spark-runtime/pom.xml, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/SparkSQLProperties.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/util/DistributionAndOrderingUtil.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedSparkBatchWrite.java, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/optimize/OptimizeWriteRule.scala, spark/v3.1/spark/src/main/scala/org/apache/spark/sql/arctic/catalyst/ArcticSpark31CatalystHelper.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestOptimizeWrite.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedHiveInsertOverwriteStatic.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestUnkeyedHiveInsertOverwriteDynamic.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestUnkeyedHiveInsertOverwriteStatic.java
fix: #1066 
- Set default value of write options `writer.distributed-and-ordered` to false for the unkeyed table.
- Set the right value of FileIndexBucketMask
- Do optimize write for Batch Insert 
=> [Arctic-1066][Spark]:Fix ordered write error when using MixedHive unkeyedTable

ams/ams-server/src/main/java/com/netease/arctic/ams/server/config/ArcticMetaStoreConf.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalSessionFactory.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java, site/docs/ch/guides/deployment.md
fix #1062 
- add config key prefix of terminal: SPARK_CONF = "spark."
Terminal  is executed in local mode, you can configure Spark properties
arctic.ams.terminal.backend: local
arctic.ams.terminal.local.spark.driver.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.executor.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.sql.session.timeZone: UTC
arctic.ams.terminal.local.spark.sql.iceberg.handle-timestamp-without-timezone=false
=> [ARCTIC-1062][AMS]Terminal support config spark properties in the local model

ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/config/ArcticMetaStoreConf.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/LoginController.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/SettingController.java, dist/src/main/arctic-bin/conf/config.yaml, site/docs/ch/guides/deployment.md
resolve #1081 
Add ams properties in config file.
`login.username=
login.password=`
to set login info.
=> [AMS][Improvement]: Support set login user and login password in config yaml file

ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
fix #1091 
- *Manually load the static resource favicon.ico
- *Fix some grammar errors
=> [ARCTIC-1091] Browser tab does not display Arctic's icon

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java
- Lower the log level in ShuffleSplitAssigner when it's an idle subtask due to an empty queue.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
=> [hotfix] Lower the log level in ShuffleSplitAssigner

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizeCommit.java
fix #1095 
- *Add the sequence number for the native iceberg table when the major optimizing commit*
=> [ARCTIC-1095][AMS] Add the sequence number for the native iceberg table when the major optimizing commit

hive/src/main/java/com/netease/arctic/hive/ArcticHiveClientPool.java, hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java
fix #924 
- Set the default retry to true when the CachedHiveClientPool executes an HMS-related operation
=> [ARCTIC-924][Hive] When AMS runs for a period of time and then cannot connect to HMS

core/src/main/java/com/netease/arctic/log/JsonToLogDataConverters.java, flink/v1.12/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/shuffle/LogRecordV1Test.java, flink/v1.14/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/shuffle/LogRecordV1Test.java, flink/v1.15/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/shuffle/LogRecordV1Test.java
Address the deserializing exception of the array<string> type in the logstore
Fix: #1111 
- *Add LogRecordV1Test*
- *The flink 1.12, 1.14, and 1.15 versions are affected.*
- *Update the JsonToLogDataConverters class*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not
=> [ARCTIC-1111] Address the deserializing exception of the array<string> type in the logstore

core/src/main/java/com/netease/arctic/op/PartitionPropertiesUpdate.java, core/src/test/java/com/netease/arctic/op/UpdatePartitionPropertiesTest.java
fix #1107 
- *add remove the key to the removeProperties*
=> [ARCTIC-1107] Fix the problem that PartitionPropertiesUpdate can't remove key

flink/v1.12/flink/pom.xml, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffsetSerializer.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousEnumerationResult.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImplTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffsetSerializer.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousEnumerationResult.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImplTest.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffset.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticEnumeratorOffsetSerializer.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ArcticSourceEnumerator.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousEnumerationResult.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/ContinuousSplitPlannerImplTest.java
fix #1063 
The ArcticSourceEnumerator enumeratorPosition does not advance with empty snapshots commit, which would cause this problem #1063 when empty snapshots are committed and the snapshot marked by the enumeratorPosition expires, so we need to change the movement rules for the enumeratorPosition
- *Change the movement rules for the enumeratorPosition of ArcticSourceEnumerator*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
=> [ARCTIC-1063] When the flink jobs reads the arctic table for a while, the flink job fails

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/ContentFileUtil.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/HiveLocationUtils.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtil.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileClean.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileCleanSupportHive.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestOrphanFileClean.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtilTest.java
fix #1105 
- *The snapshot expire check valid DataFiles according to scan from metadata files*
- *The orphan file clean check valid DataFiles according to scan from metadata files*
=> [ARCTIC-1105][AMS] Fix snapshot expire and orphan clean misdelete the DataFiles 

core/src/main/java/com/netease/arctic/table/TableMetaStore.java
resolve #1134 
Reset `sun.security.krb5.principal` before `ugi.checkTGTAndReloginFromKeytab()`.
=> [ARCTIC-1134][Core] Fix kerberos authenticate failure

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #1153 
- *Put task back into the queue if polling tasks failed*
=> [ARCTIC-1153][Optimize] Put task back into the queue if polling tasks failed

optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkConsumer.java
Resolve #1152
When the Optimizer job under Flink environment is canceled during runtime, it cannot exit smoothly.
Use variables to optimize the while loop logic in the run method of the FlinkConsumer class in the arctic-optimizer module. When the user cancels the job, control the loop variable to be false to allow the while loop to exit in a timely manner.
- Modified the FlinkConsumer class in the optimizer module, adding a loop variable in the run method.
- Local testing has been conducted.
=> [ARCTIC-1152]Fix the smooth cancellation issue of Optimizer jobs during runtime in Flink environment

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/LogDynamicSource.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java
fix #1171 
- *LogDynamicSource support ProjectionPushDown feature*
=> [ARCTIC-1171][FLINK] When reading partial fields from Logstore, the number of fields does not match

ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtil.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtilTest.java
resolve #1175 
- *Remove the check of the file's status in the UnKeyedTableUtil#getAllContentFilePath method*
=> [ARCTIC-1175][AMS] Improve the return of the UnKeyedTableUtil#getAllContentFilePath method

hive/src/main/java/com/netease/arctic/hive/op/ReplaceHivePartitions.java, hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
fix #873 
change Map<StructLike, Partition> type to StructLikeMap
=> [ARCTIC-873][CORE]Fix bug:insert overwrite will throw exception

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
fix #1201 
- check table changed before optimizing checker scan files, only for native iceberg table, keyed table's minor plan, because major and full plan have to be triggered by interval, it doesn't need table to be changed
=> [ARCTIC-1201][AMS] Optimizing checker should check if table changed before scan files

spark/v3.1/spark/pom.xml, spark/v3.1/spark/src/main/scala/org/apache/spark/sql/arctic/catalyst/ArcticSpark31CatalystHelper.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/ArcticSparkCatalogTestGroup.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestInsertOverwritePartitionTransform.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/util/RecordGenerator.java
fix #1203 to support truncate type transform when do optimize for spark insert overwrite.
- Add truncate support when convert expression from `connector.expression` to `catalyst.expression` 
- Add a new unit test to cover all types of transforms
=> [Arctic-1203][Spark][Bugfix]: Support truncate transform in spark optimize write

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractArcticOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractIcebergOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BasicOptimizeCommit.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergFullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMinorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/OptimizingIntegrationTest.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/IcebergHadoopOptimizingTest.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpireFileCleanSupportIceberg.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergBase.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizePlan.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, site/docs/ch/configurations.md
fix #1208 
- Support only optimizing a part of partitions for Minor/Full Optimizing of native Iceberg table
- when optimizing, partitions should be sorted by priority, and collect tasks one by one
- for the native Iceberg table's Minor Optimizing, the priority should be the small-files count in the partition
- for the native Iceberg table's Full Optimizing, the priority should be the delete-file size in the partition
=> [ARCTIC-1208] Optimizing of native Iceberg table supports optimizing a part of partitions at a time

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableQuotaInfo.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractArcticOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractIcebergOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergFullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMinorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MinorOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveFullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveMajorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMinorOptimizePlan.java
fix #1213 
- add PartitionWeight to sort partitions when planning
- PartitionWeight for Mixed Iceberg Format Table's Minor-Optimizing is interval and change files' count
- PartitionWeight for Mixed Iceberg Format Table's Major-Optimizing is interval and base small files' count
- PartitionWeight for Mixed Iceberg Format Table's Full-Optimizing is interval and delete files' size
- PartitionWeight for Mixed Hive Format Table's Major-Optimizing is interval and count of base files not in the hive location
- PartitionWeight for Mixed Hive Format Table's Full-Optimizing is interval and delete files' size
- Minor-Optimizing is now triggered by the change files' count instead of delete files' count
- If yes, how is the feature …
=> [ARCTIC-1213] Optimizing of Mixed Format Table supports optimizing a part of partitions at a time

spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/delegate/TestArcticSessionCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java
fix #1210 
When execute create table like command without using arctic it will throw NPE exception.
Achieve the following effects:
1. In ArcticSparkSessionCataog, provider = 'arctic' can create the arctic table
2. In ArcticSparkCatalog, the provider must be arctic or None. If it is None, the default value is arctic
=> [ARCTIC-1210][Spark][BUG]Fix bug:  NPE exception when execute create table like command without using arctic

flink/v1.12/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
fix: #1231  
- *Add a timeout strategy to the ArcticSourceTest in the flink modules*
- *The flink 1.12, 1.14, and 1.15 versions are affected.*
- *Add some logs to help locate the problem*
- *Reduce the processing time during executing the ArctciSourceTest UTs*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) no
=> [ARCTIC-1231] Add a timeout strategy to avoid blocking the UTs ArcticSourceTest

hive/pom.xml, hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveApplyNameMapping.java, hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveReadConf.java, hive/src/test/java/org/apache/iceberg/parquet/TestAdaptHiveReadConf.java
resolve #1227 
Case differences are ignored when matching parquet file schema and namemapping
=> [ARCTIC-1227] should not be case sensitive when reading the hive upgrade table schema

flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java
resolve https://github.com/NetEase/arctic/issues/1238
Remove code from the `withEmit `method in the `FlinkSink `class
`context.generateUid("arctic-writer").ifPresent(writerStream::uid);`
`context.generateUid("arctic-committer").ifPresent(writerStream::uid);`
=> [ARCTIC-1238][Flink] Remove the code that sets the UID.Solve the problem of UID conflicts in a multi-sink scenario

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
resolve #1243 
Previously, the Spark client was not allowed to pass the Catalog configuration except for the catalog url, but now it supports the configuration of catalog properties in spark-default.conf like this:
spark.sql.catalog.arctic_catalog.auth.load-from-ams = false.
change initialize() in ArcticSparkCatalog
=> [ARCTIC-1243][Spark]ArcticSparkCatalog supports the configuration of catalog properties

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/delegate/TestArcticSessionCatalog.java
fix #1255 
When using ArcticSparkSessionCatalog, skip the table creation and then execute the query existing tables directly, it will throw NPE.
This problem caused by the arcticCatalog not initialized
This pr needs to cherry-pick to the 0.3.x
The change is in the com.netease.arctic.spark.ArcticSparkSessionCatalog#loadTable()
=> [ARCTCI-1255][Spark]Fix bug: When using session catalog , load table will throw exception

ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/DerbyService.java
resolve #1273 
prepare derby env before init container/optimize config
=> [ARCTIC-1273] When using derby to execute quickstart, the table was erroneously accessed before it was created

hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java, hive/src/test/java/com/netease/arctic/hive/utils/HiveMetaSynchronizerTest.java
resolve #1263 
Sync hive to arctic only if hive partition location and arctic partition location are the same and transient_lastDdlTime is different
=> [ARCTIC-1263] hive data sync to arctic error

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/ArcticFileWriter.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/ArcticFileWriterTest.java
fix: #1233 
This patch #1010 has changed the txId generation rule, the flink writer operator doesn't need to fetch a transaction with a checkpoint before committing a snapshot from AMS. Then, the checkpoint no longer needs to be generated and maintained in the state.
- *Remove the useless code in the file writer operator*
- *Remove the state which contains a checkpoint in the file writer operator*
- *The flink 1.12, 1.14, and 1.15 versions are affected.*
=> [ARCTIC-1233] Arctic filestore write task can't been restored from checkpoint after modifying the sink parallelism

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsEnvironment.java
fix, #1242 
- optimizing-check thread pool skips `pending` tables and only changes optimizing status from `idle` to `pending`
- optimizing-planner thread skips `idle` tables and only plans tables in `pending` 
=> [ARCTIC-1242][ams] Optimizing plan thread should only plan tables in pending status

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/util/ArcticSparkUtils.java, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/optimize/OptimizeWriteRule.scala, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/optimize/RewriteAppendArcticTable.scala, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/ArcticSparkCatalogTestGroup.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestUpsert.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/util/RecordGenerator.java
To fix #1265 
Currently, the optimize write rule required open one parquet file at once. But in upsert mode, we have to write UPDATE_BEFORE and UPDATE_AFTER in one writer to get the right offset value. so we have to close optimize write for upsert and update/delete.
- Disable optimize write for upsert
=> [Arctic-1265][BugFix][Spark]: Disable optimize write for upsert

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/ArcticTransactionService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UpdateTool.java
fix #1295 
- table with currentTxId == 0 should be valid for allocating TxId from AMS
=> [ARCTIC-1295] fix writing into an empty KeyedTable with flink/spark 0.3.x/0.4.0 and AMS 0.4.1

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
fix #1280 
Problem: When the AMS deployment of high availability, use ArcticsparkSessionCatalog load table will throw exception.
Cause: The cause of this problem is that load hive table requires Kerberos authentication. After the hive table is loaded, Kerberos authentication information is carried to access the non-Kerberos Zookeeper.
Change initialize() in ArcticSparkSessionCatalog.class.
Change to load arctic catalog first
=> [ARCTIC-1280][Spark]Fix bug: When the AMS deployment of high availability, use ArcticsparkSessionCatalog loadTable will throw exception

ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/SettingController.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/controller/SettingControllerTest.java
fix #1308 
The front-end ams Settings page should not display quotes
=> [ARCTIC-1308] The front-end ams Settings page should not display quotes

ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/SparkContextUtil.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalManager.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSession.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSessionFactory.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/kyuubi/KyuubiSession.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalSessionFactory.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalTerminalSession.java, site/docs/ch/guides/deployment.md
Fix  #1266 
Support terminal access hive table when switch to a catalog with HMS metastore 。
- Use ArcticSparkSessionCatalog for terminal
- Add a config properties to support access hive in terminal.
=> [Arctic-1266][AMS]: Use ArcticSparkSessionCatalog for terminal

site/docs/ch/configurations.md
fix #1313 
- change default value of `self-optimizing.major.trigger.duplicate-ratio` from 0.2 to 0.5
=> [ARCTIC-1313] [doc] fix default value of self-optimizing.major.trigger.duplicate-ratio

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java
fix #1283 
*In some scenarios rowDataInput's parallelism may be negative (e.g. if cdc-event-duplicate is enabled) which needs to be changed to get the parallelism from the ExecutionEnvironment.*
- *Change the way to obtain the parallelism of the write operator*
=> [ARCTIC-1283][FLINK]when source is a kafka with canal-json format, the task can't run with a exception thrown

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/FlinkSource.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestUnkeyed.java
fix #1306  
*Currently watermark is a virtual field and is not in the physical schema of the arctic unkeyed table, so the watermark needs to be filtered out to avoid FieldNotFound Exception.*
- *Filter watermark related fields.*
=> [ARCTIC-1306][FLINK] Arctic Define watermark on unkeyed table encounters FieldNotFound Exception

.github/workflows/core-ci.yml, .github/workflows/trino-ci.yml, pom.xml
disable jacoco when run github ci for not blocking code development.
This PR releated to #1364 but not fixed it totally, so this PR will not close the issue. In the future we should find out the reason of the EOFException and enable the test cover check.
- Add `-Djacoco.skip=true` for core ci
- Add `-B ` for core ci to diable print colorful code.
- Add `--no-transfer-progress` to not print download process
=> [Arctic-1364]: Disable jacoco in github CI

ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtil.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtilTest.java
fix #1386
- add equality-delete files when get all valid content files
=> [ARCTIC-1386][ams] fix Iceberg Format table's orphan files clean mistakenly delete the `equality-delete` files 

spark/v3.3/spark-runtime/pom.xml
fix #1388 
Fix bug: The runtime jar of Spark 3.3 throws a NoClassDefFoundError when executing SQL.
This bug is caused by mistakenly shading classes from Spark package when shading files in the pom file.
change pom.xml in spark/v3.3
=> [ARCTIC-1388][Spark]Fix bug: The runtime jar of Spark 3.3 throws a NoClassDefFoundError when executing SQL.

core/src/main/java/com/netease/arctic/IcebergFileEntry.java, core/src/main/java/com/netease/arctic/scan/TableEntriesScan.java, core/src/main/java/com/netease/arctic/utils/ManifestEntryFields.java, core/src/test/java/com/netease/arctic/scan/TableEntriesScanTest.java
fix #1380 
- support sequence number from entry to be null
- Does this pull request introduces a new feature? (**yes** / no)
=> [ARCTIC-1380] [core] fix NPE when scan entries of Iceberg table < 1.0.0

ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ArcticZookeeperFactory.java, ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ZookeeperService.java, spark/v3.1/spark-runtime/pom.xml, spark/v3.2/spark-runtime/pom.xml, spark/v3.3/spark-runtime/pom.xml
fix #1346 
When AMS is deployed HA, use Kerberos to access non-Kerberos zookeeper will throw an exception.
Now the access to zk with or without Kerberos authentication information is controlled by turning off the parameter `zookeeper.sasl.client`.
Change in com.netease.arctic.ams.api.client.ZookeeperService#newClient
Add property `ZKClientConfig.ENABLE_CLIENT_SASL_KEK = false` into ZKClientConfig.
=> [ARCTIC-1346][AMS]Fix bug: When AMS is deployed HA, use Kerberos to access non-Kerberos zookeeper will throw an exception

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceFetcherManager.java
fix #1431 
KafkaSourceFetcherManager in com.netease.arctic.flink.read.internals path should use KafkaPartitionSplitReader in com.netease.arctic.flink.read.internals path instead of KafkaPartitionSplitReader in org.apache.flink.connector.kafka.source.reader path.
- *change package path related to KafkaPartitionSplitReader For KafkaSourceFetcherManager*
- *Only the Flink 1.12 version is affected.*
=> [ARCTIC-1431][FLINK][Bug]: when Logstore failover, will encouter ClassCastException

ams/ams-server/src/main/java/com/netease/arctic/ams/server/maintainer/command/TableCall.java
Fix #1444 
When the catalog is found to be a Mixed-Hive catalog, only the Arctic table is deleted without deleting the Hive table
=> [ARCTIC-1444] When executing the drop_metadata command with the repair tool, the Hive table was also deleted

hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
fix #1350  
Imporvement the  performance of orphan file check when hive table commit
- Use Set instead of List when checking orpthan files.
=> [Arctic-1350][Hive]: Improvement the performance of orphan file check when hive table commit

ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ArcticZookeeperFactory.java, ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ZookeeperService.java, spark/v3.1/spark-runtime/pom.xml
cherry-pick #1414 to 0.4.x
When AMS is deployed HA, use Kerberos to access non-Kerberos zookeeper will throw an exception.
Now the access to zk with or without Kerberos authentication information is controlled by turning off the parameter `zookeeper.sasl.client`.
Change in com.netease.arctic.ams.api.client.ZookeeperService#newClient
Add property `ZKClientConfig.ENABLE_CLIENT_SASL_KEK = false` into ZKClientConfig.
=> [ARCTIC-1346][AMS]Fix bug: When AMS is deployed HA, use Kerberos to a…ccess non-Kerberos zookeeper will throw an exception. cherry-pick from #1414

ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java, core/src/main/java/com/netease/arctic/op/PartitionPropertiesUpdate.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedHiveInsertOverwriteStatic.java
fix #1456 
In the `com.netease.arctic.hive.op.UpdateHiveFiles#commitPartitionProperties`, remove the `hive-location` from the properties for the partition that needs to be deleted.
=> [ARCTIC-1456][Core]Fix bug: For mix-hive tables, data overwritten by Spark InsertOverwrite can still be queried with Hive after a period of time.

ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingConfig.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedHivePartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedIcebergPartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingEvaluator.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingPlanner.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/PartitionEvaluator.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/MixedTablePlanTestBase.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestHiveKeyedPartitionPlan.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestHiveOptimizingEvaluator.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestHiveUnkeyedPartitionPlan.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestKeyedPartitionPlan.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestOptimizingEvaluator.java, core/src/main/java/com/netease/arctic/op/KeyedPartitionRewrite.java, core/src/main/java/com/netease/arctic/op/OverwriteBaseFiles.java, core/src/main/java/com/netease/arctic/op/PartitionTransactionOperation.java, core/src/main/java/com/netease/arctic/op/RewritePartitions.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java, core/src/test/java/com/netease/arctic/op/TestOverwriteBaseFile.java, hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java
- refactor PartitionTransactionOperation: apply() return partition properties
- support table partition property `base-op-time` as base partition last optimized time
- use HiveTableProperties `transient-time` as hive partition last optimized time
- optimizing support base max delay and hive max delay
- add partition evaluator weight
=> [AMS-Refactor] Optimizing trigger support hive/base max delay for each partition

flink/v1.12/flink-runtime/pom.xml, flink/v1.14/flink-runtime/pom.xml, flink/v1.15/flink-runtime/pom.xml, site/docs/ch/flink/flink-ddl.md, spark/v3.1/spark-runtime/pom.xml, spark/v3.2/spark-runtime/pom.xml, spark/v3.3/spark-runtime/pom.xml
fix #1482.
In the same way as pr #1414, the Flink engine needs to include zookeeper and curator-related dependencies when packaging.
- *Add zookeeper and curator dependency in flink-runtime pom file*
- *The flink 1.12 ,1.14 and 1.15 versions are affected.*
=> [ARCTIC-1482][Flink]: When making a connection via ams in high availability mode, NoClassDefFoundError is encountered

flink/v1.12/flink/pom.xml, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceReader.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaPartitionSplit.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceFetcherManager.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceReader.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaPartitionSplit.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSource.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSourceReader.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceFetcherManager.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceReader.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaPartitionSplit.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSource.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/log/kafka/LogKafkaSourceReader.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java
fix #1423 which results in OffsetOutOfRangeException.
fix #1431. When performing the unit test in 1.14 and 1.15 modules, ClassCastException related to #1431 was encountered and should be fixed.
- *Modified the parameters passed to the LogKafkaPartitionSplit constructor*
- *Override the KafkaSourceFetcherManager class from flink-kafka-connector to fix ClassCastException*
=> [ARCTIC-1423][FLINK]: OffsetOutOfRangeException is encountered when the arctic logstore failover.

ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java, ams/server/src/main/java/com/netease/arctic/server/table/RuntimeHandlerChain.java, ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
…bleHandler should not throw exception
=> [AMS-Refactor] make `TableRuntime`'s fileds as `StateField`

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java, core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java
To solve the problem of `arctic `being unable to delete `Iceberg `orphaned files, please refer to: https://github.com/NetEase/arctic/issues/1500
nothing
=> [ARCTIC-1500][Bug]: failed to delete orphaned files

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java
fix #1420.
This bug only exist with iceberg 0.12.x, so there is no need to cherry-pick to 0.4.x(iceberg 0.13.2) or master (iceberg 1.0+).
- for full/major optimize commit, when there are no added DataFiles and removed DeleteFiles, use Overwrite instead of Rewrite
- don't split the commit process into two Rewrite operations
=> [ARCTIC-1420] Fix optimize commit for 0.3.x when there are no target files

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/RuntimeDataExpireService.java
fix #1474 
OptimizeService::getTableOptimizeItem  doesn't check the table in optimizeTables.  
RuntimeDataExpireService::expire  will trigger refreshAndListTables when can't get the TableOptimizeItem, i  think we should refresh first and then do expire logic.
1. call   refreshAndListTables to get tables which need to expire optimize_history
2、Improve logging when TableOptimizeItem cannot be found.
=> [ARCTIC-1474]: Self-Optimizing cached table list not fetched correctly 

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/test/suites/sql/TestArcticSessionCatalog.java, spark/v3.2/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java, spark/v3.2/spark/src/test/java/com/netease/arctic/spark/test/suites/sql/TestArcticSessionCatalog.java, spark/v3.3/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java, spark/v3.3/spark/src/test/java/com/netease/arctic/spark/test/suites/sql/TestArcticSessionCatalog.java
fix #1545 
- Using CompatibleHivePropertyUtil to read hive table properties
=> [ARCTIC-1545][Bug][Spark]: Adapt legacy hive properties in spark session catalog.

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
pick #1546 to fix #1545 
Using CompatibleHivePropertyUtil to read hive table properties
Not documented
=> [ARCTIC-1545][PICK-1546][Bug][Spark]: Adapt legacy hive properties in spark session catalog.

core/src/main/java/com/netease/arctic/catalog/BasicArcticCatalog.java, core/src/test/java/com/netease/arctic/catalog/TestMixedCatalog.java
Reverts NetEase/arctic#1555.
In offline discussions, it was suggested that the properties of the catalog should remain consistent with the existing logic. Only when reading, the properties of the catalog should be merged with the properties of the table, and not written into the table properties.
=> Revert "[ARCTIC-1551]: Global Catalog configuration not valid for table build check"

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/Split.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/AbstractArcticEnumerator.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/TestArcticSourceEnumerator.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/Split.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/AbstractArcticEnumerator.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/TestArcticSourceEnumerator.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/Split.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/enumerator/AbstractArcticEnumerator.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/TestArcticSourceEnumerator.java
fix #1562 
- *Add a new status called SUBTASK_UNAVAILABLE for split*
- *Modified some of the judgement logic about assignSplits*
=> [ARCTIC-1562][FLINK]: When Flink task parallelism is more than the number of table partitions, the data in the Filestore is not read.

hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java, hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java, hive/src/test/java/com/netease/arctic/hive/op/TestHiveSchemaUpdate.java
fix #1521 
*(For example: The Arctic Flink dataStream API has already supported this configuration: 'scan.startup.mode', but it is not available with Flink SQL. We should expose this configuration to users when they are using Flink SQL.)*
- affect 0.4.x master
- affect table format: mixed hive
- add a new parameter named  `arctic.table.root-location`  to hive table to specify the root directory for storing Arctic table when creating it.
=> [ARCTIC-1521] [Improvement]: Add hive location to table properties of Mixed hive format

ams/server/src/main/resources/mysql/ams-mysql-init.sql
Fix #1584 .
- *Make `resource_id` not null in table `resource`.*
=> [ARCTIC-1584] Fix Mysql init sql

ams/server/src/main/java/com/netease/arctic/server/table/executor/HiveCommitSyncExecutor.java
Fix #1609 
- *Make HiveCommitSyncExecutor always enabled.*
- *Check if is a hive table in execute.*
=> [ARCTIC-1609] Check if is a hive table in execute in HiveCommitSyncExecutor

optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkReporter.java
fix #725 #1248
Since createtime is initialized in the Reporter constructor instead of the open() method, Reporter createTime cannot be updated when a failover or attempt is made
```
2023-06-08 00:00:49,061 INFO [pool-4-thread-260] [com.netease.arctic.ams.server.service.impl.OptimizerService] [] - get report OptimizerStateReport(optimizerId:502369, optimizerState:
{status_identification=1685938140303, flink-job-id=43c46ea9645533421327c5a6e7dcc73d})
#after failover，createtime is not updated
2023-06-08 16:55:33,177 INFO [pool-4-thread-199] [com.netease.arctic.ams.server.service.impl.OptimizerService] [] - get report OptimizerStateReport(optimizerId:502369, optimizerState:
{status_identification=1685938140303, flink-job-id=43c46ea9645533421327c5a6e7dcc73d}
)
```
- [Flink-external-optimizer] …
=> [ARCTIC-725] [optimizer,ams]Reporter createTime cannot be updated when failover or attempt 

ams/server/src/main/resources/mysql/ams-mysql-init.sql, hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java, hive/src/main/java/com/netease/arctic/hive/utils/HivePartitionUtil.java, hive/src/main/java/com/netease/arctic/hive/utils/UpgradeHiveTableUtil.java, hive/src/test/java/com/netease/arctic/hive/utils/TestUpgradeHiveTableUtil.java
resolve #1378
Set partition properties for all partitions even if there are no files under the partition when upgrading a Hive table to an Arctic table.
=> [ARCTIC-1378] Incorrect data synchronization caused the data of the arctic base table to be overwritten

ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java
fix #1626 
- not set touch time of optimizer to current time
- `SuspendingDetector`'s delay should be optimizer touch timeout
=> [ARCTIC-1626] Fix the touch time of Optimizer when restarting AMS

ams/server/src/test/java/com/netease/arctic/server/optimizing/flow/view/KeyedTableDataView.java, core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java, core/src/test/java/com/netease/arctic/utils/TestArcticDataFiles.java
fix: #1600 
Modify the handling of the string "null" in the com.netease.arctic.utils.ArcticDataFiles#data method.
=> [ARCTIC-1600][Core]Fix Self-Optimizing error when partition value is null in Mixed-format

flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/TestArcticSource.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaConsumerBaseLog.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java, flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/TestHiddenKafkaProducer.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/TestArcticSource.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaConsumer.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/TestHiddenKafkaProducer.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/TestArcticSource.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaConsumer.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/hidden/kafka/TestHiddenKafkaProducer.java
fix #1596
- *remove @Ignore in Flink module unit test*
=> [ARCTIC-1596][Flink]: turn on all unit tests annotated with @Ignore

flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducer.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducer.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/hidden/kafka/HiddenKafkaProducer.java
fix #1630 
- *Add non-null judgment for kafka producer.*
- *The flink 1.12 ,1.14 and 1.15 versions are affected.*
=> [ARCTIC-1630][Flink] Kafka producer encounters NPE when calling the close function

ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java, ams/server/src/main/java/com/netease/arctic/server/table/executor/TableRuntimeRefreshExecutor.java
Fix #1656 and some related questions.
- *Make plan task breaks when offered tasks to the task queue.*
- *Make the evaluator not evaluate when the table is processing in optimizing.*
=> [ARCTIC-1656][AMS] Make plan return when offered a task and do not evaluate when the table is optimizing

core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java, core/src/test/java/com/netease/arctic/utils/TestArcticDataFiles.java
fix #1653 
- using `URLDecoder` when converting partition path to partition data
=> [ARCTIC-1653] Support special characters in partition values

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtil.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestOrphanFileClean.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, site/docs/ch/configurations.md
This is to increase the feature to 0.4.x，for details, please refer to https://github.com/NetEase/arctic/issues/1628.
Regularly delete iceberg independent deleteFiles by configuring 'clean-independent-delete-files.enabled'.
=> [ARCTIC-1628][Feature][AMS]: Remove the Independent DeleteFiles for the Iceberg Format Table

ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
Fix #1679.
- *Clean the pendingInput when begin optimizing*
- *When completing the optimizing process, set the optimizing status to Idle.*
=> [ARCTIC-1679] Clean pending input when begin optimizing process

ams/optimizer/pom.xml
fix #1673 to adapter more flink version for flink optimizer. close #1272 
- Add a profile flink1.16 to flink optimizer.
- Change default dependend version to flink1.14.6
=> [ARCTIC-1673]: Add maven profile to set flink version for flink optimizer 

core/src/main/java/com/netease/arctic/io/reader/GenericCombinedIcebergDataReader.java
Fix #1696.
- *Using the table schema to order the equality delete ids.*
=> [ARCTIC-1696] Fix the different schema for delete filter and the PK projection

ams/server/pom.xml
fixed #1704 
Class conflict due to hadoop-client-api referenced by spark3.3
exclude hadoop-client-api
=> [ARCTIC-1704][BUG] exclude hadoop-client-api

dist/src/main/arctic-bin/conf/log4j2.xml
resolve #1694 
1.Added compression to all logs
2.For info logs, it will make him start rolling up at a smaller size
=> [ARCTIC-1694] AMS logs need to be compressed and rolled up

core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java, hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java
fix #1708
1.  Use caseInsensitiveSelect when generating GenericRecord
2.  Lowercase partition names when creating mixed hive tables
=> [ARCTIC-1708] [Bug]: When using a partition name with uppercase letters in the mixed hive format, it leads to an exceptio

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeExecuteService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/RuntimeDataExpireService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/SupportHiveSyncService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TrashCleanService.java
resolve https://github.com/NetEase/arctic/issues/1737 in 0.3.x
- add try-catch for scheduleWithFixedDelay
=> [ARCTIC-1737] 0.3.x fix the tasks of ScheduledExecutorService that halts when an exception or error is thrown

ams/server/src/main/java/com/netease/arctic/server/table/executor/SnapshotsExpiringExecutor.java, ams/server/src/test/java/com/netease/arctic/server/table/executor/TestSnapshotExpire.java
Fix #1736.
- *Fetch optimizing snapshot time when the table is processing.*
- *Fetch the target snapshot id in the optimizing process instead of the current snapshot id.*
- *Modify the UT test.*
=> [ARCTIC-1736] Fix SnapshotsExpiringExecutor will expire the snapshot which table used to plan

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingPlanner.java
resolve #1745
- fix the calculation of `actualInputSize` when skip some partitions for optimizing
=> [ARCTIC-1745] fix the calculation of `actualInputSize` when skip some partitions for optimizing

core/pom.xml, core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java, core/src/test/java/com/netease/arctic/utils/map/TestSimpleSpillableMap.java
fix #1751 and #1194 
get corrent eq-delete file and the sequence number to make sure duplicate records are filtered
=> [ARCTIC-1751] Update the memory map in spillable map when new value was existed for the key

hive/pom.xml
fix #1761 
- Exclude hadoop-parquet-bundle in arctic-hive module.
=> [ARCTIC-1761]: Fix parquet dependency conflict.

ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingPlanner.java
fix #1745 , if the first partition's size > maxSize, it should not be skipped
- fix skip all partitions when the first partition's size > maxSize
=> [ARCTIC-1745] Only skip partitions when the maximum size limit is exceeded

ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/FileTree.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveFullOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizePlan.java
fix #1700 
- using bin-packing to split tasks if only base files exit and all files in node(0,0)
- add unit test case
=> [ARCTIC-1700] For unpartitioned Mixed Format KeydTable, using bin-packing to split tasks for Full Optimizing on root node

core/src/main/java/com/netease/arctic/utils/SchemaUtil.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/lookup/KVTableFactory.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/lookup/RocksDBCacheState.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/lookup/UniqueIndexTable.java, flink/v1.14/flink/src/test/java/com/netease/arctic/flink/lookup/TestKVTable.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/lookup/KVTableFactory.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/lookup/RocksDBCacheState.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/lookup/UniqueIndexTable.java, flink/v1.15/flink/src/test/java/com/netease/arctic/flink/lookup/TestKVTable.java
fixed: #1783 
- *Adjust the order of the primary keys and join keys when creating unique and join keys mapping index*
- *The Flink 1.15 and 1.14 versions are affected.*
- *Avoid NPE if the initialization process fails*
- *Add some tests*
=> [ARCTIC-1783][lookup] The primary key serialization exception occurs when the primary key definition is different from the schema fields order

flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java
fixed: #1783 
- Adjust the order of the projected fields when creating projected schema from base schema;
- The Flink 1.15 and 1.14 versions are affected.
=> [ARCTIC-1783][lookup] Ensure that projection schemas are in the same order

ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
fix #1802 
- fix the task is not offered to the `retryQueue` if polling fails
- put tasks back to `executingTaskMap` if reset fails when `checkSuspending`
- remove useless field `next` from `TaskStatusMachine`
- add some logs for optimizing
=> [AMORO-1802] Fix optimizing tasks failed to retry

hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java, hive/src/main/java/com/netease/arctic/hive/catalog/MixedHiveTables.java, hive/src/main/java/com/netease/arctic/hive/utils/UpgradeHiveTableUtil.java, hive/src/test/java/com/netease/arctic/hive/catalog/TestArcticHiveCatalog.java
fix #1807 
Added a logic that deletes the hive table, but does not delete the amoro table
=> [AMORO-1807] When I upgrade a hive table and it fails, it deletes the original hive table

ams/server/src/main/java/com/netease/arctic/server/IcebergRestCatalogService.java, ams/server/src/test/java/com/netease/arctic/server/TestIcebergRestCatalogService.java
fix #1820 
- Return empty list when listNamespace passes a database name
=> [AMORO-1820]: Fix spark drop namespace error in rest catalog services.

ams/server/src/main/java/com/netease/arctic/server/optimizing/SchedulingPolicy.java
FIX #1822
When I edited an optimizer group, it will fail if I did not add the scheduling-policy property.
=> [AMORO-1822][Bug]: Failed to edit optimizer group

core/src/main/java/com/netease/arctic/table/TableMetaStore.java
Resolve #1817.
- *Remove sun.security.krb5.Config.refresh()*
- *Remove KrbException.*
=> [AMORO-1817] Remove JDK internal imports

ams/server/src/main/java/com/netease/arctic/server/table/executor/OrphanFilesCleaningExecutor.java
fix #1864
fix delete metadatafile uri to `fileInfo.location()`
=> [AMORO-1864]  fix metadata file has not been deleted

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedHivePartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedIcebergPartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingEvaluator.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/PartitionEvaluator.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/MixedTablePlanTestBase.java, core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java
fix #1883 
- filter files when adding files to `PartitionEvaluator` and `AbstractPartitionPlan`
- split tasks based on rewriteFiles and rewritePosFiles instead of fragment files and segment files
- remove `taskNeedExecute` after splitting tasks
- remove `addPartitionProperties` from `PartitionEvaluator`, add it to the constructor
=> [AMORO-1883] Perform file filtering when adding files to `PartitionEvaluator` instead of during splitting tasks

ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java
fix #1603 
For a table without a primary key, set the corresponding water mark according to whether there is a change mertic or not
=> [ARCTIC-1603] The water mark is not displayed properly for tables without primary keys

ams/optimizer/src/main/java/com/netease/arctic/optimizer/OptimizerExecutor.java, docs/admin-guides/managing-optimizers.md
Close #1893 .
- Fix unit conversion for parameters `-msz` to spillmap configuration
- Add optimizer parameter doc
=> [AMORO-1893][Optimizer] Fix unit conversion for parameters `-msz` to spillmap configuration

ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java, core/src/main/java/com/netease/arctic/table/BasicUnkeyedTable.java, trino/src/main/java/com/netease/arctic/trino/ArcticCatalogSupportTableSuffix.java
…Runtime` did not override `toString`
Close #1914
1. `BasicUnkeyedTable` and `ChangeTableWithExternalSchemas` override `name` method
2. `TaskRuntime` override `toString`
=> [AMORO-1914] Override `org.apache.iceberg.Table#name` for some classes and `toString` for `TaskRuntime`

core/src/main/java/com/netease/arctic/table/TableMetaStore.java, docs/engines/trino.md
Fix #1912.
Roll back the ` sun.security.krb5.Config.refresh();` and add docs for Trino.
=> [AMORO-1912] Roll back the refresh when constructing UGI

.scalafmt.conf, ams/api/pom.xml, ams/api/src/test/java/com/netease/arctic/ams/api/MockArcticMetastoreServer.java, pom.xml, spark/v3.1/spark/pom.xml, spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/TruncateArcticTableExec.scala, spark/v3.2/spark/pom.xml, spark/v3.2/spark/src/main/scala/com/netease/arctic/spark/sql/ArcticExtensionUtils.scala, spark/v3.2/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala, spark/v3.2/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticMergeIntoTable.scala, spark/v3.2/spark/src/main/scala/org/apache/spark/sql/arctic/parser/QueryParsingErrors.scala, spark/v3.3/spark/pom.xml, spark/v3.3/spark/src/main/scala/com/netease/arctic/spark/sql/ArcticExtensionUtils.scala, spark/v3.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala, spark/v3.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticMergeIntoTable.scala, spark/v3.3/spark/src/main/scala/org/apache/spark/sql/arctic/parser/QueryParsingErrors.scala, style/arctic-checkstyle.xml
First step to solve the #1402. 
- Add global config of `spotless-maven-plugin`
- Using googleJavaFormatter as java format style.
- Remove some checkstyle rules conflict with googleJavaFormatter. 
- Replace `spotless-maven-plugin` with `scalastyle-maven-plugin` as scala code format checker
=> [Improvement]: Add basic configration of spotless

ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
Close #1242 . 
This PR (#1284) has achieved only planning the pending tables to improve plan efficiency, but it still refreshes the idle tables. When there are many tables, this can become a bottleneck.
In the production scenario, we observed more than 1,00 tables were refreshed for each plan, which cost 10-20s. 
However, plan for each table only cost 1-2s.
- check pending status before refresh table
- modify some logs for plan cost of each table
=> [AMORO-1242] Fix refreshing a large number of tables during optimizing plan

ams/server/src/main/java/com/netease/arctic/server/table/TableConfiguration.java, ams/server/src/main/java/com/netease/arctic/server/table/executor/OrphanFilesCleaningExecutor.java, ams/server/src/main/java/com/netease/arctic/server/table/executor/SnapshotsExpiringExecutor.java, ams/server/src/test/java/com/netease/arctic/server/table/executor/TestSnapshotExpire.java
Close #1943 .
- using `TableConfiguration` instead of `TableProperties` for snapshot expiring and orphan files cleaning
=> [AMORO-1943] using `TableConfiguration` instead of `TableProperties` for AMS

charts/amoro/.helmignore, charts/amoro/Chart.yaml, charts/amoro/README.md, charts/amoro/templates/NOTES.txt, charts/amoro/templates/_helpers.tpl, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/templates/amoro-deployment.yaml, charts/amoro/templates/amoro-role.yaml, charts/amoro/templates/amoro-rolebinding.yaml, charts/amoro/templates/amoro-service.yaml, charts/amoro/templates/amoro-serviceaccount.yaml, charts/amoro/values.yaml
AMS Run On K8S
Close #1335.
- add helm chart for amoro
- ams running on k8s
=> [AMORO-1335]Amoro AMS Support On K8S

ams/server/src/main/java/com/netease/arctic/server/dashboard/PlatformFileManager.java, ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java, ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/PlatformFileInfoController.java
Close #1120  cherry-pick #1379 to master.
- When receiving a file access request, return a byte array.
=> [AMORO-1120] we return bytes array when we response file load request

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java
fix full optimizing bug
close #1924 
- should not check major necessary and minor necessary if it's full optimizing
- Does this pull request introduce a new feature? (yes )
=> [AMORO-1924]Fix Iceberg tables undergoing major optimizing repeatedly

charts/amoro/templates/amoro-configmap.yaml, charts/amoro/templates/amoro-deployment.yaml, charts/amoro/values.yaml
Amoro Helm Chart Support Overwrite JVM Optional.Users can adjust jvm and some other parameters
Close #1962 .
Amoro Support Overwrite JVM Optional
=> [AMORO-1962][helm-chart] Amoro Support Overwrite JVM Optional

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractIcebergOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/AbstractOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizePlan.java, ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizePlan.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, site/docs/ch/configurations.md
Close #1935 .
- add table property self-optimizing.max-task-file-size-bytes
- add to docs
=> [AMORO-1935] 0.4.x introduce a table property for task spliting size of self-optimizing

ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingConfig.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java, ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, docs/user-guides/configurations.md
Close #1935.
- add a new table property `self-optimizing.max-task-size-bytes`
- modify the docs
=> [AMORO-1935] Introduce a table property for task spliting size of self-optimizing

ams/dashboard/README.md, ams/dashboard/vue.config.js
=> doc: update dashboard readme

ams/server/src/main/java/com/netease/arctic/server/table/executor/TableRuntimeRefreshExecutor.java
Close #1869 
- Avoid SQL Transaction Timeouts
=> [AMORO-1869] Avoid evaluating pending input during the optimization process

ams/api/src/main/java/com/netease/arctic/ams/api/client/AmsClientPools.java, ams/api/src/main/java/com/netease/arctic/ams/api/client/ThriftClientPool.java
Close #1977.
- Invalidate the object when the client is disconnected.
- Cancel the second time to get the client.
=> [AMORO-1977] Fix retry logic in ThriftClientPool

spark/v3.2/spark/src/main/scala/com/netease/arctic/spark/ArcticSparkExtensions.scala
When using amoro spark-3.2-runtime-0.5.0.jar, an error was reported and the class ResolveProcedures could not be found. Through comparison, it was found that changing the class is no longer necessary. Simply remove the dependency of this class.
Close #2032 .
-
=> [AMORO-2032]: Spark3.2 version does not require the class ResolveProcedures

ams/server/src/main/java/com/netease/arctic/server/ArcticServiceContainer.java, ams/server/src/main/java/com/netease/arctic/server/utils/ConfigurationUtil.java, ams/server/src/test/java/com/netease/arctic/server/util/ConfigurationUtilTest.java, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/templates/amoro-database-secert.yaml, charts/amoro/templates/amoro-deployment.yaml, charts/amoro/values.yaml
AMS Helm Chart Support Database Secret On K8S
When the user fills in the mysql password in the helm template, use secret to protect it.
Close #1945 .
- Add System Env Method Filter start with "ams.*" properties
- Database MySQL Type use secret to write env and read it
=> [AMORO-1945]AMS Support Database Secret On K8S

hive/src/main/java/com/netease/arctic/hive/utils/TimeUtil.java, hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetConversions.java, hive/src/test/java/com/netease/arctic/hive/utils/TestTimeUtil.java
Close #2044 
- Add 'com.netease.arctic.hive.utils.TimeUtil#microsBetween' to Instead 'ChronoUnit.MICROS.between(instant,instant)'
=> [AMORO-2044]Fix the issue of not being able to write time fields with large time value in mixed-hive format

ams/server/pom.xml, ams/server/src/main/java/com/netease/arctic/server/terminal/SparkContextUtil.java, ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalSessionFactory.java
The future mixed-format related features should be plug-in based. In order to better organize the project structure, the AMS module should not directly depend on the code of MixedFormat. This PR will remove the hard-coded access to the spark module in the AMS module.
- Change socpe of `amoro:spark` to runtime in `ams/server` dependencies part.
- Using static final string instead of `Class.getName` 
=> [Improvement]: Change socpe of `amoro:spark`  to runtime in `ams/server` dependency.

core/src/main/java/com/netease/arctic/table/TableProperties.java, docs/user-guides/configurations.md
fix #1935 .
Change the default split task size from 1G to 128MB to keep the same behavior as in version 0.5.0 and avoid unexpected OOM errors.
- change default value of self-optimizing.max-task-size-bytes to 128MB
=> [AMORO-1935] Change the default value of Self-Optimizing split task size to 128MB

core/src/main/java/com/netease/arctic/io/reader/ArcticDeleteFilter.java
Close #2091.
- [using InternalRecordWrapper to build PrimaryKeyData for NodeFilter](https://github.com/NetEase/amoro/commit/15b1bb68f179972f61ae892059d081cfa3054c2d)
=> [AMORO-2091] Resolve the optimzing exception for KeyedTable with Timestamp(without zone) column as Primary key

.github/workflows/docker-images.yml, docker/optimizer-flink/Dockerfile
Auto build official docker image by github workflow actions. 
- Add workflow to build official image Automated.
1. When commits merged into master or tags pushed,  `amoro`, `optimizer-flink`, `quickdemo` will be built automated.
2. When a PR is merged into the master branch, it triggers the building of a "master-snapshot" image. When a tag is pushed, it triggers the building of a "release" image, and the image tag matches the corresponding GitHub tag.
=> [Workflow]: Auto build Official Docker Image

dist/src/main/arctic-bin/conf/config.yaml, docs/admin-guides/managing-optimizers.md
Fix typo in config.yaml example
- Same with `managing-optimizers.md`
=> [Hotfix] Fix typo in config.yaml example

ams/server/src/main/java/com/netease/arctic/server/ArcticManagementConf.java, ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java, dist/src/main/arctic-bin/conf/config.yaml
As titled.
Close #2109.
- Remove the lock in the table sync.
- Delegate the table sync workload to a configurable thread pool.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not documented
=> [AMORO-2109] Make AMS table sync with external catalogs multithreaded

ams/server/src/main/java/com/netease/arctic/server/persistence/NestedSqlSession.java, ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java, core/src/main/java/com/netease/arctic/io/reader/ArcticDeleteFilter.java, core/src/main/java/com/netease/arctic/optimizing/BaseOptimizingInput.java, trino/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- specify options various is class field
- use ThreadLocal method remove instead of set null
=> [fix] specify options various is class field;use ThreadLocal remove instead of set null

ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableStatistics.java, ams/server/src/main/java/com/netease/arctic/server/dashboard/utils/TableStatCollector.java
Fix TableStatistics.setTotalFilesStat method's variable is assigned to itself
https://github.com/NetEase/amoro/blob/d0283bb8f71ad4fa0d7771cbecc03e5ef5332834/ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableStatistics.java#L61-L63
=> [hotfix]  Fix TableStatistics.setTotalFilesStat method's variable is assigned to itself

ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java
Fix the format of thread name in DefaultTableService
=> [Fix] Fix the format of thread name in DefaultTableService

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java
Close #2090.
- binpack using max value of task size and target size
=> [AMORO-2090] Fix the problem of Optimizing bin-packing tasks being too small

ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
Using the wrong map when getting table transactions.
- Change the map to put.
=> [Fix] Fix using the wrong summary map

docker/README.md
"./build.sh ams" should be "./build.sh amoro" for refactoring code
-
=> Fix build.sh wrong args in README.md

ams/server/src/main/java/com/netease/arctic/server/catalog/PaimonServerCatalog.java, ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java
I encountered a Kerberos error when there was no  hive-conf-dir parameter. However, this error does not always occur and may be related to the Kerberos environment of the server where AMS is located.
```
javax.security.sasl.SaslException: GSS initiate failed
at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[?:1.8.0_152]
at org.apache.thrift.transport.TSaslClientTransport.handleSaslStartMessage(TSaslClientTransport.java:95) ~[libthrift-0.13.0.jar:0.13.0]
at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:265) ~[libthrift-0.13.0.jar:0.13.0]
at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:38) ~[libthrift-0.13.0.jar:0.13.0]
at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssu …
```
=> [Fix] Add hive-conf-dir option to paimon catalog

ams/server/src/main/java/com/netease/arctic/server/manager/FlinkOptimizerContainer.java
Close #2196.
- Break out of the loop when the value is successfully fetched.
- Remove useless 'fetch' for 'releaseOptimizer'.
=> [AMORO-2196] Fix scale out error

core/src/main/java/com/netease/arctic/data/FileNameRules.java, core/src/test/java/com/netease/arctic/io/TestFileNameGenerator.java
Fix the bug introduced by #2183
In #2183 , the writer attempted to maintain consistency between the connector and HiveServer reads by writing to a hidden file, but overlooked adapting to the new file name style during the process of parsing the relevant parameters from the file name.
- Make the regular expression for parsing the Key Filename adapt to hidden file names.
- Does this pull request introduce a new feature? (  no)
=> [AMORO-2168]:Fix-2183 FileNameRules adapt to hidden filename.

core/src/main/java/com/netease/arctic/optimizing/IcebergRewriteExecutor.java, hive/src/main/java/com/netease/arctic/hive/optimizing/MixFormatRewriteExecutor.java
Close #2223.
- Cast empty partition data to NULL.
- Fix some warnings.
=> [AMORO-2223]Cast empty partition data to NULL to avoid creating empty partition directory.

core/src/main/java/com/netease/arctic/data/file/FileNameGenerator.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java, core/src/test/java/com/netease/arctic/io/DataTestHelpers.java, flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveOutputFileFactory.java, hive/src/main/java/com/netease/arctic/hive/op/OverwriteHiveFiles.java, hive/src/main/java/com/netease/arctic/hive/op/ReplaceHivePartitions.java, hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java, hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java, hive/src/main/java/com/netease/arctic/hive/table/SupportHive.java, hive/src/main/java/com/netease/arctic/hive/utils/HiveCommitUtil.java, hive/src/test/java/com/netease/arctic/hive/HiveTableTestBase.java, hive/src/test/java/com/netease/arctic/hive/io/HiveDataTestHelpers.java, hive/src/test/java/com/netease/arctic/hive/op/AutoSyncHiveTest.java, hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestRewritePartitions.java, hive/src/test/java/com/netease/arctic/hive/utils/HiveMetaSynchronizerTest.java, site/docs/ch/configurations.md, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/ArcticSparkCatalogTestGroup.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/io/TestConsistentWrite.java
Pick #2183  to 0.4.x branch 
see #2183 
- Does this pull request introduce a new feature? (yes  )
- If yes, how is the feature documented? ( docs  )
=> [Pick-2183][AMORO-2168] Support hive commit protocol in mixed-hive format. 

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java, core/src/main/java/com/netease/arctic/table/TableProperties.java, core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java, docs/user-guides/configurations.md, flink/flink-common/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java, hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java, hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java, hive/src/test/java/com/netease/arctic/hive/io/HiveDataTestHelpers.java, hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java, hive/src/test/java/com/netease/arctic/hive/op/TestRewritePartitions.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java, spark/v3.1/spark/src/test/java/com/netease/arctic/spark/writer/TestSparkWriter.java, spark/v3.2/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java, spark/v3.2/spark/src/test/java/com/netease/arctic/spark/writer/TestSparkWriter.java, spark/v3.3/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java, spark/v3.3/spark/src/test/java/com/netease/arctic/spark/writer/TestSparkWriter.java
Close #225.
- Change the default value of `self-optimizing.major.trigger.duplicate-ratio` to 0.1
- Rename property `hive.consistent-write.enabled` to `base.hive.consistent-write.enabled` and move it to HiveTableProperties.
- Polish some codes.
=> [AMORO-2225] Change the default value of `self-optimizing.major.trigger.duplicate-ratio` to 0.1

ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/ServiceContainer.java
Close #2217 .
- ServiceContainer supports reset before start
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / ServiceContainer supports reset before start)
=> [AMORO-2217] 0.4.x fix clear and reset ServiceContainer after HA

ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java, ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
Close #2244 .
- check task status to be Init/Executing when on prepared
- change delete file log from DEBUG to INFO
=> [AMORO-2244] fix 0.4.x `Failed` optimizing tasks should not change to `Prepared`

docs/admin-guides/managing-optimizers.md
The optimizer-job.jar path in the "deploy external optimizer" document is incorrect
Change the path from ${ARCTIC_HOME}/plugin/flink/optimizer-job.jar to ${ARCTIC_HOME}/plugin/optimizer/flink/optimizer-job.jar
- Does this pull request introduce a new feature?  no
=> fix the optimizer-job.jar path error in the document

flink/v1.15/flink-runtime/pom.xml, flink/v1.16/flink-runtime/pom.xml, flink/v1.17/flink-runtime/pom.xml
Close #2271.
- Exclude org.apache.thrift.TException during shade amoro flink runtime.
=> [AMORO-2271]: Exclude shade org.apache.thrift.TException in flink runtime.

spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/KeyedSparkBatchScan.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/SparkScanBuilder.java, spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/UnkeyedSparkBatchScan.java, spark/v3.2/spark/src/main/java/com/netease/arctic/spark/reader/KeyedSparkBatchScan.java, spark/v3.2/spark/src/main/java/com/netease/arctic/spark/reader/SparkScanBuilder.java, spark/v3.2/spark/src/main/java/com/netease/arctic/spark/reader/UnkeyedSparkBatchScan.java, spark/v3.3/spark/src/main/java/com/netease/arctic/spark/reader/KeyedSparkBatchScan.java, spark/v3.3/spark/src/main/java/com/netease/arctic/spark/reader/SparkScanBuilder.java, spark/v3.3/spark/src/main/java/com/netease/arctic/spark/reader/UnkeyedSparkBatchScan.java
The NPE may be throwed when spark comparing the table scan during plan.
- Add default value to SparkScanBuilder
=> [BugFix][Spark]: Add default value of table-filters in spark scan builder to avoid NPE when comparing the table scan.

core/src/main/java/com/netease/arctic/table/BasicKeyedTable.java
Close #2295.
- Using hash map instead of ImmutableMap.Builder for KeyedTable.properties()
- Does this pull request introduce a new feature? (  no)
=> [AMORO-2295]: Fix the table property `watermark.base` conflict for keyed-table

core/src/main/java/com/netease/arctic/table/blocker/RenewableBlocker.java
Close #2336 .
- name the renew blocker thread
- set the renew blocker thread daemon
=> [AMORO-2336] Set the renew blocker thread to be a daemon thread

ams/server/src/main/java/com/netease/arctic/server/table/internal/InternalMixedIcebergCreator.java, ams/server/src/test/java/com/netease/arctic/server/TestInternalMixedCatalogService.java
Close #2329.
- Set change table location and primary key spec when create a keyed mixed-iceberg table.
=> [AMORO-2329]: Miss ChangeStore && PrimaryKeySpec in table detail when creating mixed-iceberg table in InternalCatalog.

trino/src/main/java/com/netease/arctic/trino/keyed/KeyedConnectorMetadata.java, trino/src/test/java/com/netease/arctic/trino/arctic/TestBaseArcticPrimaryTable.java, trino/src/test/java/com/netease/arctic/trino/arctic/TestHiveTable.java
Close #2246.
- Delete calculating on change store.
- Delete merge stats method.
- Only use base store's stats.
- Does this pull request introduce a new feature? (**no**)
- If yes, how is the feature documented? (**not applicable**)
=> [AMORO-2246] Make Trino stats only calculate on base store

core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java, core/src/test/java/com/netease/arctic/utils/TestArcticDataFiles.java
…ns in multithreading
Close #2324 .
-Use 'DateTimeFormatter' to avoid format parsing exceptions in multithreading
=> [AMORO-2324] Use 'DateTimeFormatter' to avoid format parsing exceptions in multithreading

ams/server/src/main/java/com/netease/arctic/server/table/executor/TableRuntimeRefreshExecutor.java
When I changed the `self-optimizing.enabled` from `true` to `false`, I got this error message if there is no running optimizing process.
```
2023-11-30 15:43:29,206 ERROR [async-table-runtime-refresh-executor-0] [com.netease.arctic.server.table.RuntimeHandlerChain] [] - failed to handle, ignore and continue
java.lang.NullPointerException: null
at com.netease.arctic.server.table.executor.TableRuntimeRefreshExecutor.handleConfigChanged(TableRuntimeRefreshExecutor.java:69) ~[classes/:?]
at com.netease.arctic.server.table.RuntimeHandlerChain.lambda$fireConfigChanged$2(RuntimeHandlerChain.java:67) ~[classes/:?]
at com.netease.arctic.server.table.RuntimeHandlerChain.doSilently(RuntimeHandlerChain.java:110) ~[classes/:?]
at com.netease.arctic.server.table.RuntimeHandlerChain.fireConfigChanged(Run …
```
=> [hot-fix] Fix the `NullPointerException` when modifying the `self-optimizing.enabled`

ams/server/pom.xml
Currently, Ams lib contains unnecessary test jars.
Exclude test jars from ams lib.
=> [HOTFIX] limit ams server dist dependencies to runtime scope

ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java
Skip cleaning up dangling delete files for Iceberg V1 table
Close #2222.
- if iceberg v1 table , no need to cleanDanglingDeleteFiles
=> [AMORO-2222] [Improvement]: Skip cleaning up dangling delete files for Iceberg V1 table

ams/server/src/main/java/com/netease/arctic/server/utils/HiveLocationUtil.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/maintainer/TestSnapshotExpireHive.java, ams/server/src/test/java/com/netease/arctic/server/table/executor/ExecutorTestBase.java
Close #2404 .
- #2404 
- get hive locations return the uri path
- change the unit test to cover this case
=> [AMORO-2404] fix Mixed Hive table mistakenly deletes hive files during expiring snapshots

ams/dist/src/main/arctic-bin/bin/ams.sh
Close #2415.
- Add '-XX:+PrintGCDateStamps' to ams.sh.
=> [AMORO-2415] Print GC date stamps 

core/src/main/java/com/netease/arctic/scan/TableEntriesScan.java
Close #2441 .
- fix TableEntriesScan without format suffix
=> [AMORO-2441] Fix `TableEntriesScan` when no file format is specified in the file name

ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java, ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/MixedTableMaintainer.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/maintainer/TestSnapshotExpire.java
Fix #1720 in 0.6.x
- cherry-pick and fix conflict #2394 
=> [AMORO-1720] 0.6.x Fix Mixed Format KeyedTable expiring all the snapshots with optimized sequence 

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedIcebergPartitionPlan.java
Close #2464 .
- correct the logic of checking the minor optimze tirgger conditions.
=> [AMORO-2464] Fix bug AMS will repeat trigger the same minor optimize when the bucket > self-optimizing.minor.trigger.file-count

mixed/trino/pom.xml
We forgot to remove trino's Checkstyle in https://github.com/NetEase/amoro/pull/2175.
- remove trino's Checkstyle.
=> [HOTFIX] Remove Trino module's Checkstyle

ams/server/src/main/java/com/netease/arctic/server/TableManagementService.java
Close #2466.
- correct the check logic for legacy MixedIceberg to avoid throw out exception when quering the mix-hive format table.
=> [AMORO-2466] Fix bug #2466 spark query the mix_hive table will throw out exception

mixed/flink/v1.15/flink/pom.xml, mixed/flink/v1.16/flink/pom.xml, mixed/flink/v1.17/flink/pom.xml
`artifactId` has been modified via #2374 
- Fix artifactId from `flink-common` to `amoro-mixed-flink-common`
=> [Hotfix] Fix artifactId of shade plugin

ams/server/pom.xml
Close #2478.
Since https://github.com/NetEase/amoro/pull/2399 we only involve 'runtime' scope when copying dependencies, so we need to change the `standalone-optimizer`'s scope to runtime.
- Change the `standalone-optimizer`'s scope to runtime.
- Adjust dependency order
=> [AMORO-2478] Package involve standalone-optimizer

ams/server/src/main/java/com/netease/arctic/server/table/DataExpirationConfig.java, ams/server/src/main/java/com/netease/arctic/server/table/TableConfiguration.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/maintainer/TestDataExpire.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/maintainer/TestOrphanFileClean.java, ams/server/src/test/java/com/netease/arctic/server/optimizing/maintainer/TestSnapshotExpire.java
Close #2488.
- Exclude table with `gc.enable` = `false`  from table data cleanups.
=> [AMORO-2488] Respect Iceberg GC table properties

ams/server/src/main/java/com/netease/arctic/server/ArcticManagementConf.java, ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalSessionFactory.java
=> [Feature]: Make local terminal cores configurable

mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/BinaryRowDataSerializerWrapper.java, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/RocksDBCacheState.java, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/RocksDBRecordState.java, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/RocksDBSetSpilledState.java
Close #2497.
- Using `ThreadLocal` API to make the `BinaryRowDataSerializerWrapper` utility thread-safe.
=> [AMORO-2497] [Flink]: Support for serialization and deserialization thread-safe in lookup JOIN

ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java, docs/user-guides/configurations.md
Add the trigger condition of combine multiple position delete file for minor
- Add trigger condition `combinePosSegmentFileCount > 0` for minor optimizing.
- Fix the description of config `self-optimizing.minor.trigger.file-count`
=> [Improvement] Add the trigger condition of combine multiple position delete file for minor

ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java
Close #2522.
- Delete the dispose of DefaultOptimizingService in TableRuntimeHandlerImpl
=> [AMORO-2522] Delete the dispose of DefaultOptimizingService in TableRuntimeHandlerImpl

core/src/test/java/com/netease/arctic/formats/AmoroCatalogTestHelper.java, core/src/test/java/com/netease/arctic/formats/IcebergHadoopCatalogTestHelper.java, core/src/test/java/com/netease/arctic/formats/MixedIcebergHadoopCatalogTestHelper.java, core/src/test/java/com/netease/arctic/formats/PaimonHadoopCatalogTestHelper.java, mixed/flink/flink-common/pom.xml, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/catalog/FlinkUnifiedCatalog.java, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/catalog/factories/FlinkUnifiedCatalogFactory.java, mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/catalog/factories/paimon/PaimonFlinkCatalogFactory.java, mixed/flink/flink-common/src/test/java/com/netease/arctic/flink/catalog/FlinkAmoroCatalogITCase.java, mixed/flink/flink-common/src/test/java/com/netease/arctic/flink/catalog/FlinkCatalogContext.java, mixed/flink/flink-common/src/test/java/com/netease/arctic/flink/catalog/TestFlinkUnifiedCatalogs.java, mixed/flink/flink-common/src/test/java/com/netease/arctic/flink/table/AmoroCatalogITCaseBase.java, mixed/flink/v1.15/flink/pom.xml, mixed/flink/v1.16/flink/pom.xml, mixed/flink/v1.17/flink/pom.xml
Close https://github.com/NetEase/amoro/issues/2345.
- support UnifiedCatalog to contain Paimon format table in Flink Engine
- add FlinkAmoroCatalogITCase for Flink UnifiedCatalog based on AmoroCatalogTestBase
no
=> [AMORO-2345] Support UnifiedCatalog to contain Paimon format table in Flink Engine

ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java, pom.xml
Close #2546.
- Bump Paimon 0.5.0 to 0.7.0
=> [AMORO-2546] Upgrade paimon dependency to 0.7.0

core/src/main/java/com/netease/arctic/io/writer/BaseTaskWriter.java, pom.xml
Close https://github.com/NetEase/amoro/issues/2560.
-ORC fileformat support roll new file with self-optimizing.target-size for mixed_format
-Change orc-core.version to 1.8.3 
because org.apache.iceberg.orc.OrcFileAppender#length would call org.apache.orc.Writer#estimateMemory, but it did not exsits in orc-core 1.7.2, which would cause java.lang.NoSuchMethodError: org.apache.orc.Writer.estimateMemory as below
=> [AMORO-2560]Filformat ORC support roll new file for mixed_format

.github/workflows/docker-images.yml
The `quickdemo` docker image cannot be built successfully by Github action when releasing a new version, related error can be found here: https://github.com/NetEase/amoro/actions/runs/7984579979/job/21802352068.
We should fix it.
- To fix parsing errors, retrieve version information from the first line of the tag output.
After the modification, the image was successfully built in the 0.6.1 version release：
https://github.com/NetEase/amoro/actions/runs/7984948851
=> [Hotfix] Fix quickdemo docker image build error in GitHub action

README.md
Fix Maven package command for trino module in README.md;
- 'mixed/trino' instead of 'trino' module.
=> [DOCS] Fix Maven command for trino module in README.md

core/src/main/java/org/apache/iceberg/IcebergFindFiles.java, core/src/test/java/org/apache/iceberg/TestIcebergFindFiles.java
=> [AMORO-2571] Cannot find data files under partitions with null partition values

.github/labeler.yml
The labeler action cannot label the `ams-server` properly because of some error configuration, we need to fix it.
- Fix the labeler configuration for `ams-server` module
=> [Hotfix][Infra] Fix github labeler action configuration for ams-server module

ams/server/pom.xml
#2578 add test scope dependencies for log4j2 related packages in the root module, but the `ams-server` module relies on them in compile scope, we should fix it.
- Declare the dependent scope to compile for log4j2 related packages in the `ams-server` module
=> [Hotfix] Dependent on log4j2 related packages in compile scope in the `ams-server` module

docker/amoro/entrypoint.sh
Close #2576.
- When writing to the JVM configuration file, remove the quotation marks from the value section.
- When adding a new configuration, remove excess slash(/).
=> [AMORO-2576] Fix the configuring JVM options error in `entrypoint.sh`

ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
Close  https://github.com/NetEase/amoro/issues/2601.
-fix:  File pages for paimon tableformat, 'Commit Time' for file has wrong zone
fix: Optimizing pages for paimon tableformat, 'Start Time' for file has wrong zone and wrong value for Duration
File 'Commit Time' on ams-server
FIle createTime in HDFS filesystem
Optimizing pages for 'Start Time'  and 'Duration'
=> [AMORO-2601] Paimon tableformat for 'Commit Time' in File pages and 'Start Time' in Optimizing pages

ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
Close https://github.com/NetEase/amoro/issues/2607.
- Fix: 'Last Commit Time' for Paimon partition table in File pages has wrong zone
for partition updatae_day=2024-03-08 'Last Commit Time' is '2024-03-08 18:24:03' on dashboard as below
update time is  also '2024-03-08 18:24' in hdfs filesystem
=> [AMORO-2607]'Last Commit Time' for Paimon partition table in File pages has wrong zone

ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java
Close #2638.
- Catch exceptions generated by listTables
=> [AMORO-2638] fix `refresh-external-catalogs` cannot be completed when exist database listTable fails

mixed-format/flink/flink-common/src/test/java/com/netease/arctic/flink/catalog/TestMixedCatalog.java
Close https://github.com/NetEase/amoro/issues/2640.
- rename TestLegacyMixedCatalog to TestMixedCatalog
- TestMixedCatalog containes test cases for mixed catalog factories, including: MIXED_ICEBERG_IDENTIFIER, MIXED_HIVE_IDENTIFIER, LEGACY_MIXED_IDENTIFIER
- use Juit Parameterized to make unit test cases also work for MIXED_ICEBERG_IDENTIFIER and MIXED_HIVE_IDENTIFIER, not only LEGACY_MIXED_IDENTIFIER
=> [AMORO-2640]Adjust the test case for different catalog factory under mixed/flink module

mixed-format/spark/v3.2/spark-runtime/pom.xml, mixed-format/spark/v3.3/spark-runtime/pom.xml
=> [AMORO-2672][Bug]: The spark-runtime shade configuration specifies incorrect dependencies for common and spark

ams/metric-reporter/pom.xml, ams/metric-reporter/prometheus-reporter/pom.xml, ams/optimizer/common/pom.xml, ams/optimizer/flink-optimizer/pom.xml, ams/optimizer/pom.xml, ams/optimizer/spark-optimizer/pom.xml, ams/optimizer/standalone-optimizer/pom.xml
Close #2746 .
The artifactId of the sub modules of ams should use the same prefix
- change `amoro-optimizer` to `amoro-ams-optimizer`
- change `amoro-metric-reporter` to `amoro-ams-metric-reporter`
=> [AMORO-2746] The artifactId of the sub modules of ams should use the same prefix

amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/util/DateTimeUtils.java
In this code snippet, "36524" represents a specific numerical value, which actually denotes the total number of days in four years. This is because in the Gregorian calendar, a leap year occurs every four years. Therefore, "36524" signifies the total number of days in four years.
- Modify the Chinese characters to "36524".
=> [Hotfix] Fix the Chinese characters in the code

charts/amoro/values.yaml
Fix #2795  
- Add variables existed in templates but not in Values.yaml. Those variables are: nameOverride, commonLabels and commonAnnotations. 
- Change Values.yaml: add more descriptions, refs and modify the file with standard format which seems more pretty.
test with unittest(#2794)
This change is not dependency by #2794 , Just use it as test.
- If yes, how is the feature documented?  none
=> [AMORO2795][helm chart] add variables and descriptions into values.yaml

amoro-mixed-format/amoro-mixed-format-hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetWriter.java
Fix bug that memory leaks when using mix -hive format to write parquet files.
To avoid writing tasks causing memory leak when write a mix-formatted table. Details refers to issue pls.
Close #2789 .
- add logic of release a compressor to pool after finishing writing a file.
=> [AMORO-6789]Memory leaks when using mix -hive format to write parquet files.

amoro-ams/dist/src/main/arctic-bin/bin/ams.sh
=> [Amoro-2830] Use G1 GC by default

amoro-mixed-format/amoro-mixed-format-spark/pom.xml, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-runtime-3.2/pom.xml, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-runtime-3.3/pom.xml, docs/admin-guides/deployment.md
Close #2827 .
Keep the same naming style as amoro-mixed-format-flink-runtime module
`amoro-mixed-format-flink-runtime` modules
- amoro-mixed-format-flink-runtime-1.15
- amoro-mixed-format-flink-runtime-1.16
- amoro-mixed-format-flink-runtime-1.17
=> [AMORO-2827] Keep the same naming style as amoro-mixed-format-flink-runtime module

.github/workflows/core-hadoop2-ci.yml, .github/workflows/core-hadoop3-ci.yml, .github/workflows/trino-ci.yml, CONTRIBUTING.md, README.md, amoro-mixed-format/amoro-mixed-format-trino/pom.xml, docs/admin-guides/deployment.md
Close #2853.
It not friendly for users to use `mvn clean package -DskipTests -pl '!amoro-mixed-format/amoro-mixed-format-trino'` to build the amoro project. Add a new `skip-trino-build` profile to improve the build command.
=> [AMORO-2853] Improve the packaging and compilation process for amoro project

amoro-core/src/main/java/org/apache/amoro/utils/map/StructLikeWrapperSizeEstimator.java, amoro-core/src/test/java/org/apache/amoro/utils/map/TestStructLikeWrapperSizeEstimator.java
=> [AMORO-2864] Filter the null field when estimate size of records

amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-runtime-3.2/pom.xml, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-runtime-3.3/pom.xml
Close #2857.
- Shade HTTP client classes for mixed-format spark runtime jars.
=> [AMORO-2857] Fix http client class not found error in mixed-format spark runtime jars

amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/pom.xml, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/amoro/spark/MixedFormatSparkExtensions.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/amoro/spark/sql/catalyst/analysis/MixedFormatAlignRowLevelCommandAssignments.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/amoro/spark/sql/catalyst/plans/MergeIntoMixedFormatTable.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/amoro/spark/sql/catalyst/plans/UnresolvedMergeIntoMixedFormatTable.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/spark/sql/amoro/catalyst/AssignmentHelper.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/main/scala/org/apache/spark/sql/catalyst/analysis/MixedFormatAssignmentAlignmentSupport.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/src/test/java/org/apache/amoro/spark/test/suites/sql/TestMergeIntoSQL.java, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/pom.xml, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/src/main/scala/org/apache/amoro/spark/MixedFormatSparkExtensions.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/src/main/scala/org/apache/amoro/spark/sql/catalyst/analysis/MixedFormatAlignRowLevelCommandAssignments.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/src/main/scala/org/apache/amoro/spark/sql/catalyst/plans/UnresolvedMergeIntoMixedFormatTable.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/src/main/scala/org/apache/spark/sql/catalyst/analysis/MixedFormatAssignmentAlignmentSupport.scala, amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-3.3/src/test/java/org/apache/amoro/spark/test/suites/sql/TestMergeIntoSQL.java
Close #2872 .
- add  MixedFormatAlignRowLevelCommandAssignments  to cast constant to the field type
- add unittest
=> [AMORO-2872] "Merge into when not matched" may result in incorrect writing of floating-point field data.

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java, charts/amoro/Chart.yaml, charts/amoro/templates/_optimizer.tpl, charts/amoro/values.yaml, docs/admin-guides/deployment-on-kubernetes.md, docs/admin-guides/managing-optimizers.md
=> [AMORO-2895] Add more image related properties for the amoro optimizers

amoro-core/src/main/java/org/apache/amoro/io/AuthenticatedHadoopFileIO.java
When creating an Iceberg table on OSS and executing clean-orphan-file, there are normal data_files (just created but not yet committed to Iceberg) being cleaned up. The clean-orphan-file.min-existing-time-minutes parameter is not taking effect.  
Through debugging, it was found that because OSS does not record the file access time, getAccessTime returns 0, causing the clean-orphan-file.min-existing-time-minutes parameter to become ineffective.  
At the same time, the [listPrefix](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java#L133-L152) function of Iceberg also uses getModificationTime. So using getModificationTime should be a better choice.
- In the listDirectory function, replace getAccessTime with getModificationTime.
- Does …
=> [AMORO-2925] Fix the issue of clean-orphan-file mistakenly deleting data files.

amoro-core/src/main/java/org/apache/amoro/table/TableProperties.java, docs/admin-guides/deployment.md, docs/admin-guides/managing-catalogs.md, docs/concepts/catalogs.md, docs/engines/flink/flink-ds.md, docs/engines/flink/flink-get-started.md, docs/user-guides/cdc-ingestion.md, docs/user-guides/configurations.md, docs/user-guides/metrics.md, docs/user-guides/using-tables.md
Fix some issues of docs for releasing 0.7.0
- Fix some doc issues
- If yes, how is the feature documented? (not applicable )
=> [Improvement] Improve docs for relasing 0.7.0

amoro-ams/dist/src/main/amoro-bin/conf/config.yaml, charts/amoro/values.yaml, docs/admin-guides/managing-optimizers.md
hotfix.
```
2024-06-20 03:37:44,219 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS encountered an unknown exception, will exist
java.lang.RuntimeException: java.nio.file.NoSuchFileException: ～/.kube/config
at org.apache.amoro.server.manager.KubernetesOptimizerContainer.getKubeConfigContent(KubernetesOptimizerContainer.java:187) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
at org.apache.amoro.server.manager.KubernetesOptimizerContainer.init(KubernetesOptimizerContainer.java:72) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
at org.apache.amoro.server.resource.ResourceContainers$ContainerWrapper.loadResourceContainer(ResourceContainers.java:98) ~[amoro-ams-server-0.7-SNAPSHOT.jar:0.7-SNAPSHOT]
at org.apache.amoro.server.resource.ResourceContainers$ContainerWrap …
```
=> [Hotfix] Fix NoSuchFileException when deploy on k8s

charts/amoro/templates/amoro-admin-secret.yaml, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/templates/amoro-deployment.yaml, charts/amoro/values.yaml
=> Move admin username and password to secrets

.github/ISSUE_TEMPLATE/bug_report.yml, amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/SparkOptimizerContainer.java, charts/amoro/values.yaml
=> [Hotfix] Unlock some configs of the spark optimizer

amoro-mixed-format/amoro-mixed-format-trino/pom.xml, pom.xml
Skip the javadoc plugin for `amoro-mixed-format-trino` module by default.
- Skip the javadoc plugin for `amoro-mixed-format-trino` module by default.
=> [Improvement] Support skip javadoc plugin for `amoro-mixed-format-trino` module

amoro-ams/amoro-ams-dashboard/src/views/catalogs/Detail.vue, amoro-ams/amoro-ams-server/pom.xml, amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java, amoro-core/src/main/java/org/apache/amoro/formats/paimon/PaimonCatalogFactory.java, amoro-core/src/main/java/org/apache/amoro/table/TableMetaStore.java, amoro-core/src/main/java/org/apache/amoro/utils/MixedCatalogUtil.java, pom.xml
Close #2960.
Support paimon s3 based catalog
=> [AMORO-2960] Support paimon s3 based catalog

amoro-core/src/main/java/org/apache/amoro/table/TableMetaStore.java
Using ams internal catalog and s3 as storage, but NPE occurs. The root cause is that 
`org.apache.amoro.server.utils.InternalTableUtil#newIcebergFileIo L86 -> Configuration conf = store.getConfiguration();`
core-site and hdfs-site is null when using s3 storage.
>  
-
=> [Hotfix] Meet NPE when loading tables which use s3 storage

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/persistence/TaskFilesPersistence.java
Close https://github.com/apache/amoro/issues/3033.
- avoid IndexOutOfBoundsException
=> [AMORO-3033]IndexOutOfBoundsException when start up AMS during selectProcessInputFiles  because of no optimizing process_id

amoro-ams/amoro-ams-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerConfig.java
Close #2787.
- amoro-ams/amoro-ams-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerConfig
=> [AMORO-2787]: Remove `memorySize` option

amoro-ams/amoro-ams-server/pom.xml
Close #3041 .
- Config `failOnNoGitDirectory` to `false`
- Config `failOnUnableToExtractRepoInfo` to `false`, refer to https://issues.apache.org/jira/browse/FLINK-18655
=> [AMORO-3041] Config failOnNoGitDirectory and failOnUnableToExtractRepoInfo to false for git-commit-id-plugin

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/executor/TableRuntimeRefreshExecutor.java
=> [Hotfix] Fix wrong javadoc for TableRuntimeRefreshExecutor

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java, amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmsServiceMetrics.java, amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/TestAmsServiceMetrics.java, docs/user-guides/metrics.md
Close https://github.com/apache/amoro/issues/3053.
1. collect system metric for jvm  using api from jdk
it's refer from flink jvm system metric https://github.com/apache/flink/blob/af7d2b3ab0e0ecc4157005704bebac9c767f2e1a/flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java#L129
2. register metric in AmoroServiceContainer  during start ams httpserver by using amoro metric plugin  
I had test HEAP_USED,HEAP_COMMITTED,HEAP_MAX,THREADS_COUNT ,the count collected by jdk api is meet expectations
But I'm not sure  the number of CPU_LOAD and CPU_TIME collected by jdk api is equals to the number collect from machinery system
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not …
=> [AMORO_3053]Add system metric for ams service

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/PaimonTableDescriptor.java, amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/model/ConsumerInfo.java
Close #3073.
- Add Paimon Consumer AmoroSnapshotsOfTable of previous Snapshot Id Info
=> [AMORO-3073]: Paimon Consumer adds the previous Snapshot Id Info (#3073)

amoro-core/src/main/java/org/apache/amoro/utils/MixedDataFiles.java, amoro-core/src/test/java/org/apache/amoro/utils/TestMixedDataFiles.java
fix issues [3091](https://github.com/apache/amoro/issues/3091)
support TIMESTAMP in `MixedDataFiles.fromPartitionString()`
=> [AMORO-3091] Support TIMESTAMP in `MixedDataFiles.fromPartitionString()`

amoro-ams/dist/src/main/amoro-bin/conf/config.yaml
Close #3097 
The current default configurations of AMS are somewhat unreasonable, and we should improve them.
Turn off the sync-hive-tables service (change ams.sync-hive-tables.enabled to false).
Turn on the data-expiration service (change ams.data-expiration.enabled to true).
Add table-manifest-io.thread-count configuration example (add ams.table-manifest-io.thread-count and set default value to 20)
Add http-server.rest-auth-type configuration example (add ams.http-server.rest-auth-type and set default value to token)
Add terminal.result.limit configuration example(add terminal.result.limit and set default value to 1000)
Add terminal.stop-on-error configuration example(add terminal.stop-on-error and set default value to false)
Add terminal.session.timeout configuration example(add …
=> [AMORO-3097] Improve the default configuration for AMS

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/HighAvailabilityContainer.java
Close #3132 .
Refact the logic of closing resources in HighAvailabiltyContainer.
-
=> [AMORO-3132]High available service should not close curator client before LeaderLatch closing

amoro-ams/amoro-ams-server/pom.xml, pom.xml
Close  https://github.com/apache/amoro/issues/3095
- Just add the mvn pom dependency
When I connect to S3:
Before:
After:
=> [AMORO-3095][ams-server]Fix: Add s3a dependency software.amazon.awssdk:s3-transfer-manager

amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java
Close #3153.
-The implementation class of TServer has been modified.
=> [AMORO-3153]Modify the implementation class of the thrift server

amoro-ams/amoro-ams-server/pom.xml
We add conf to fail silent when no git dir before, so that it would not block the
release process, but it may not fail in normal mode also, in this commit
we move the configuration to profile and can be enabled in the release process
Close #3125 .
-
=> [AMORO-3152] Make git-commit-plugin fail on no git dir configurable

dist/src/main/amoro-bin/bin/ams.sh
When `-Dcom.sun.management.jmxremote` is set, jvm will listen on a random port as jmxremote.port.  
- Only set jmxremote params when jmxremote.port is set.
=> [Improvement]: Disable jmxremote when jmxremote.port is not set.

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/MixedAndIcebergTableDescriptor.java
=> [AMORO-3149] The parameter type of iceberg's snapshot method is converted to long

amoro-ams/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java, amoro-ams/src/test/java/org/apache/amoro/server/manager/TestKubernetesOptimizerContainer.java, amoro-ams/src/test/resources/config.yaml, docs/admin-guides/deployment-on-kubernetes.md, pom.xml
Close #2979.
- Support K8S Pod Template From KubernetesOptimizer
- Remove redundant comments
=> [AMORO-2979] Support K8S Pod Template From KubernetesOptimizer (#2979)

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/AbstractPartitionPlan.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/CommonPartitionEvaluator.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/OptimizingEvaluator.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/PartitionEvaluator.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableSummaryMetrics.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableSummaryMetrics.java, amoro-common/src/main/java/org/apache/amoro/table/descriptor/TableSummary.java, amoro-web/mock/modules/table.js, amoro-web/src/language/en.ts, amoro-web/src/language/zh.ts, amoro-web/src/types/common.type.ts, amoro-web/src/views/tables/index.vue, docs/user-guides/metrics.md
Close #3180.
- Implement health score calculation for tables
- Added TABLE_SUMMARY_HEALTH_SCORE metric in the `TableSummaryMetrics`
- Show health score on the table detail page
- Does this pull request introduce a new feature? (yes )
=> [AMORO-3180] Implement health score calculation for tables

dist/src/main/amoro-bin/conf/optimize/log4j2.xml
Close #3145 .
Currently there will be many logs for (de)compressor from CodecPool, and seems there is no other meaningful info log from this class, so we change
the log level from CodecPool from info to warn to filter out these logs
This only affect the local optimizer, and user need to change the configuration if they use flink/spark optimzier.
Before the change
After the change
=> [AMORO-3145] Filter out info log for CodecPool in optimizer 

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/PersistentBase.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java
=> [AMORO-3110] Avoid optimization status blocking in running

amoro-ams/src/main/java/org/apache/amoro/server/AmoroManagementConf.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java
=> [AMORO-3111]Avoid optimization state blocking in planning

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/SchedulingPolicy.java
Close #3196.
The real issue is scheduling hunger problem
The table runtime quotas are cached in the sorter once it has been calculated.
The correct logic is calculating quota on every single scheduling phase, and only cache quota result in a single phase.
So the fix is create a sorter for every schedule call.
=> [Amoro-3196]: Fix scheduling hungry issue

amoro-web/src/views/overview/components/MultipleDataCard.vue, amoro-web/src/views/overview/components/SingleDataCard.vue
It is not necessary to import `defineProps` api about vue.
=> [Improvement] Remove not necessary imports

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java
Close #3194.
- Only print the table ID, not the full table name.
=> [AMORO-3194]improvement: optimize plan log print

amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java, amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingStatus.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/SqlSessionFactoryProvider.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/TableRuntimeMeta.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/converter/OptimizingStatusConverter.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/mapper/TableMetaMapper.java, amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java, amoro-ams/src/main/java/org/apache/amoro/server/table/RuntimeHandlerChain.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableManager.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableService.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/BaseTableExecutor.java, amoro-ams/src/main/resources/derby/ams-derby-init.sql, amoro-ams/src/main/resources/mysql/ams-mysql-init.sql, amoro-ams/src/main/resources/postgres/ams-postgres-init.sql, amoro-ams/src/main/resources/postgres/upgrade-0.7.0-to-0.7.1.sql, amoro-ams/src/test/java/org/apache/amoro/server/RestCatalogServiceTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/TestDefaultOptimizingService.java, amoro-ams/src/test/java/org/apache/amoro/server/dashboard/TestOverviewCache.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/OptimizingStatusTest.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/TestOptimizingQueue.java, amoro-ams/src/test/java/org/apache/amoro/server/table/DerbyPersistence.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableRuntimeHandler.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableRuntimeManager.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableService.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableSummaryMetrics.java
Close #2893 .
Optimize the loading process when user open the `optimizer` page
-
=> [AMORO-2893] optimize table page loading

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/OptimizingEvaluator.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableSummaryMetrics.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestTableSummaryMetrics.java, docs/user-guides/metrics.md
Close #3220.
*  fetch `totalFileRecords`,`totalFileSize`,`totalFileCount` from snapshot summary
* add `table_summary_dangling_delete_files` metric  
danglingDeleteFiles = totalDeleteFiles - eqDeleteFiles - posDeleteFiles
=> [AMORO-3220] Optimize table summary metrics to fetch data

amoro-ams/src/main/resources/mysql/ams-mysql-init.sql
In ams-mysql-init.sql, the SQL for creating the table_runtime table is incorrect, which will cause the service to fail to start when redeploying Amoro.
=> [hotfix] ams-mysql-init.sql fix error init

amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
If OptimizerKeeper reset task status illegally(SUCCESS -> PLAN), optimizer may not be released or touched. In the meantime, the optimizer is restart, then the remaning task will never be executed.
Close #3110 .
- 
=> [AMORO-3110] Do not throw exception when retry task in optimizer keeper

amoro-ams/pom.xml, amoro-common/src/main/java/org/apache/amoro/config/OptimizingConfig.java
Close #3224.
- Compare min-plan-interval in OptimizingConfig#equals
=> [AMORO-3224] Compare min plan interval in optimizing config

amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java, dist/src/main/amoro-bin/bin/ams.sh, dist/src/main/amoro-bin/bin/load-config.sh, dist/src/main/amoro-bin/conf/env.sh, dist/src/main/assemblies/bin.xml
HiveConf can load the existing hive-site.xml from the classpath during initialization.
So Amoro should support adding some directories to the classpath at startup.
In addition, user-defined environment variable configuration files need to be supported.
- Add a env.sh in ${AMORO_CONF_DIR} 
- If exists env variables HADOOP_CONF_DIR and HIVE_CONF_DIR, add them to CLASSPATH
- Support add additional directories by env variable AMORO_ADDITION_CLASSPATH.
- Print all env variables and their value at startup.
=> [Improvement] Support env.sh and add HADOOP_CONF_DIR and HIVE_CONF_DIR to CLASSPATH

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/MixedAndIcebergTableDescriptor.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/ServerTableDescriptor.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java, amoro-common/src/main/java/org/apache/amoro/process/ProcessStatus.java, amoro-common/src/main/java/org/apache/amoro/table/descriptor/FormatTableDescriptor.java, amoro-format-hudi/src/main/java/org/apache/amoro/formats/hudi/HudiTableDescriptor.java, amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonTableDescriptor.java, amoro-web/mock/modules/table.js, amoro-web/src/services/table.service.ts, amoro-web/src/views/tables/components/Optimizing.vue
To support filter of optimizing type and status when show table optimizing process list.
- Add filter selection in WebUI
- Add filter status in TableDescriptorAPI
- Implement the filter in Mixed/Iceberg/Paimon/Hudi descriptor
- Add RESTAPI to get table process type for different format.
=> [Improvement] Support filter by status and type when show table optimizing process

amoro-common/src/main/java/org/apache/amoro/table/TableMetaStore.java
When loading a custom auth type catalog, we should not check the hdfs/core site files.
- Check hdfs/core site files only for simple and Kerberos auth.
=> [Hotfix] Fix loading custom auth s3 catalog issue

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerGroupController.java, amoro-web/src/language/en.ts, amoro-web/src/language/zh.ts, amoro-web/src/services/optimize.service.ts, amoro-web/src/views/resource/components/CreateOptimizerModal.vue, amoro-web/src/views/resource/components/List.vue, amoro-web/src/views/resource/index.vue
Close #3195 
1. The backend project has split the OptimizerController into OptimizerController and OptimizerGroupController. The OptimizerController now contains the create and release methods, while the OptimizerGroupController retains all the original logic of the OptimizerController.
2. The frontend project has added a "Create Optimizer" button on the Optimizer page.
Run test locally before making this pull request
=> [AMORO-3195]: OptimizerController decoupling to OptimizerGroupController

amoro-common/src/main/java/org/apache/amoro/process/ProcessStatus.java, amoro-common/src/main/java/org/apache/amoro/process/TableProcess.java, amoro-common/src/main/java/org/apache/amoro/process/TableProcessState.java, amoro-format-hudi/src/main/java/org/apache/amoro/formats/hudi/HudiTableDescriptor.java
Close #3172.
- Add Running Status in ProcessStatus
=> [AMORO-3172] AMS ProcessStatus Miss Running Status

amoro-format-paimon/pom.xml
```
2024-10-11 10:49:08,133 ERROR [main] [org.apache.amoro.server.AmoroServiceContainer] [] - AMS start error
java.io.UncheckedIOException: org.apache.paimon.fs.UnsupportedSchemeException: Could not find a file io implementation for scheme 's3' in the classpath.  Hadoop FileSystem also cannot access this path 's3://gzczy-test/warehouse'.
at org.apache.paimon.catalog.CatalogFactory.createUnwrappedCatalog(CatalogFactory.java:100) ~[paimon-bundle-0.9.0.jar:0.9.0]
at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:71) ~[paimon-bundle-0.9.0.jar:0.9.0]
at org.apache.paimon.catalog.CatalogFactory.createCatalog(CatalogFactory.java:67) ~[paimon-bundle-0.9.0.jar:0.9.0]
at org.apache.amoro.formats.paimon.PaimonCatalogFactory.paimonCatalog(PaimonCatalogFactory.java:73) …
```
=> [hotfix] Paimon S3 File Reader Miss Pom dependency

amoro-web/mock/modules/optimize.js, amoro-web/src/services/optimize.service.ts, amoro-web/src/types/common.type.ts, amoro-web/src/utils/table.ts, amoro-web/src/views/optimize/components/List.vue
=> [AMORO-3139] Improve list content of optimizing page

amoro-web/package.json, amoro-web/pnpm-lock.yaml, amoro-web/src/services/optimize.service.ts, amoro-web/src/views/resource/components/CreateOptimizerModal.vue, amoro-web/src/views/resource/components/List.vue, amoro-web/src/views/resource/index.vue, amoro-web/src/views/tables/components/Optimizing.vue
I found that the web project contains some code with lint errors and formatting issues many times.
I add two packages to lint and format code before commit. It is helpful to improve code quality and keep unified coding style.
=> [Improvement] Lint and format amoro web code before commit

amoro-ams/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java, charts/amoro/values.yaml
- Helm value.yaml remove **kube-config-path** value.
- KubernetesOptimizerContainer Support default Kubernetes client configuration.
=> [hotfix] k8s helm support using the default Kubernetes client configuration

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/PlatformFileInfoController.java, amoro-web/mock/modules/catalogs.js, amoro-web/mock/modules/common.js, amoro-web/mock/modules/optimize.js, amoro-web/mock/modules/overview.js, amoro-web/mock/modules/settings.js, amoro-web/mock/modules/table.js, amoro-web/mock/modules/terminal.js, amoro-web/src/services/global.service.ts, amoro-web/src/services/login.service.ts, amoro-web/src/services/optimize.service.ts, amoro-web/src/services/overview.service.ts, amoro-web/src/services/setting.services.ts, amoro-web/src/services/table.service.ts, amoro-web/src/services/terminal.service.ts, amoro-web/src/utils/request.ts, amoro-web/src/views/catalogs/Detail.vue, charts/amoro/templates/amoro-deployment.yaml
Close #3038.
Unify the API set for both dashboard and Open API in the same url [ /api/ams/v1 ]. 
Previously, frontend requests and external interface requests were distinguished by using the paths **ams/v1** and **api/ams/v1** respectively. Frontend requests required cookie validation for login status, while external interface requests needed to pass an apikey parameter for verification. In this design, the request paths from both sources are unified to **api/ams/v1**. For frontend requests, an additional header parameter **_X-Request-Source: frontend_** will be included. This allows the source of the request to be distinguished and routed to different validation logic accordingly.
- [ ☑️ ] Add screenshots for manual tests if appropriate
- [ ☑️ ] Run test locally before making a pull …
=> [AMORO-3038] Unify the API set for dashboard and open API

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java
Close #3253.
Before the change we'll check whether the table exists by loading the table, the loading step maybe too expensive, and it's redundant because the table exists will be checked in the folllowing step when loading table to retrieve the info.
-
=> [AMORO-3253] Optijmizing getOPtimizingProcessTasks and getOptimizingTypes rest efficiency

amoro-ams/pom.xml, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/MixedAndIcebergTableDescriptor.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/SqlSessionFactoryProvider.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/mapper/OptimizingMapper.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/TableRuntimeRefreshExecutor.java, amoro-ams/src/test/java/org/apache/amoro/server/TestDefaultOptimizingService.java, amoro-ams/src/test/java/org/apache/amoro/server/dashboard/TestIcebergServerTableDescriptor.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/BaseOptimizingChecker.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/TestOptimizingQueue.java, pom.xml
Close #3066.
- remove the ServerCatalog#tableExists(db, table) in TableController#getOptimizingProcesses because we can reuse the table load logic in the following logic
- push the offset and limit in mapper#selectOptimizingProcesses(MixedAndIcebergTableDescriptor#getOptimizingProcessesInfo) to db (this can limit the items retrieved from db)
=> [AMORO-3066] Optimizing the efficiency for optimizing-processes rest api

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/OptimizingEvaluator.java
```
2024-10-21 14:35:12,212 ERROR [async-table-runtime-refresh-executor-0] [org.apache.amoro.server.table.executor.TableRuntimeRefreshExecutor] [] - Refreshing table iceberg.xxx.xxx(tableId=198) failed.
java.lang.NumberFormatException: For input string: "2498622972"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_392]
at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_392]
at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_392]
at org.apache.iceberg.util.PropertyUtil.propertyAsInt(PropertyUtil.java:64) ~[iceberg-core-1.4.3.jar:?]
at org.apache.amoro.server.optimizing.plan.OptimizingEvaluator$PendingInput.<init>(OptimizingEvaluator.java:239) ~[amoro-ams-0.8-SNAPSHOT.jar:0.8-SNAPSHOT]
at …
```
=> [Hotfix] Use `propertyAsLong` instead of `propertyAsInt` for `total-records`

amoro-web/src/views/tables/components/Optimizing.vue
It fixes the RUNNING and SUBMITTED state color in the frontend dashboard.
Closes #3288.
- If yes, how is the feature documented? not applicable
=> [AMORO-3288] Status color of running and submitted

amoro-web/src/views/catalogs/Detail.vue
Close #3308.
The upload method was implemented additionally and did not use the default config. This bugfix adds the header 'X-Request-Source': 'Web' to the upload method.
=> [AMORO-3308][Bugfix]: get signature check error when upload catalog config files

amoro-ams/src/main/java/org/apache/amoro/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/values.yaml, docs/admin-guides/using-kyuubi.md
Close #xxx.
Support for terminal integration with LDAP authentication in Kyuubi
-
=> [AMORO-3309][Improvement] Support for terminal integration with LDAP authentication in Kyuubi

pom.xml
Close #3323.
- Exclude `hadoop-client-api` dependency to avoid class conflict with `hadoop-common`
=> [AMORO-3323]Exclude `hadoop-client-api` dependency

amoro-common/src/main/java/org/apache/amoro/CommonUnifiedCatalog.java, amoro-format-hudi/src/main/java/org/apache/amoro/formats/hudi/HudiHadoopCatalog.java, amoro-format-iceberg/src/main/java/org/apache/amoro/formats/mixed/MixedCatalog.java
Close #3330
1）the 'databaseExists' call in 'CommonUnifiedCatalog#createDatabase' and 'CommonUnifiedCatalog#dropDatabase' can be suppressed by the subsequent logic, so we delete redundant 'databaseExists' in those functions.
2) the 'databaseExists' in  'CommonUnifiedCatalog#listTables' can not be removed directly, because the 'HudiHadoopCatalog#listTables' and 'MixedCatalog#listTables' methods called in 'FormatCatalog#listTables' do not explicitly throw NoSuchDatabaseException. We add exception handling for NoSuchDatabaseException in these functions to eliminate the redundancy of 'databaseExists' in 'CommonUnifiedCatalog#listTables'.
=> [AMORO-3330] Reducing redundant 'databaseExists' in 'CommonUnifiedCatalog'

amoro-format-iceberg/src/main/java/org/apache/amoro/io/writer/IcebergFanoutPosDeleteWriter.java, amoro-format-iceberg/src/main/java/org/apache/amoro/utils/TableFileUtil.java, amoro-format-iceberg/src/test/java/org/apache/amoro/io/TestIcebergFanoutPosDeleteWriter.java
Relate for #3228 
Unable to judge correctly, need to remove the format suffix.
| - |example|
|:--:|:--:|
|dataFilePath|./data/data-1.parquet| 
|posDeleteFilePath | ./data/data-1-delete-suffix.parquet|
=> [AMORO-3228] Remove the format suffix in judgment condition

amoro-ams/src/main/java/org/apache/amoro/server/table/executor/HiveCommitSyncExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/OptimizingCommitExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/OptimizingExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/OrphanFilesCleaningExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/SnapshotsExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/table/executor/TableRuntimeRefreshExecutor.java
=> [hotfix] Fix incorrect parameter naming of some `TableExecutor`

charts/amoro/templates/amoro-configmap.yaml, charts/amoro/values.yaml
Close #xxx.
- export http-server.rest-auth-type variable in helm chart value.
- If yes, how is the feature documented? not applicable
=> [Improvement] expose 'http-server.rest-auth-type' variable in Helm chart

amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingEvaluator.java, amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/scan/IcebergTableFileScanHelper.java, amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/scan/KeyedTableFileScanHelper.java, amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/scan/TableFileScanHelper.java
Close #3289 .
In my environment, there is a table with many partitions waiting to be merged. Each plan is very time-consuming. After optimization, the time-consuming is significantly reduced
=> [ARORO-3289] Avoid calling getMixedTablePartitionSpecById in the scan loop

amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/src/main/java/org/apache/amoro/flink/table/FlinkSource.java
Close #3359 .
- add a filter to check whether the source is a parallelismSourceFunction
=> [AMORO-3359] only set parallelism on parallelismSourceFunciton

amoro-ams/src/test/java/org/apache/amoro/server/dashboard/TestIcebergServerTableDescriptor.java
Tried to fix unit test issues in :https://github.com/apache/amoro/actions/runs/12308627468/job/34358691837
- Clear derby tables after TestIcebergServerTableDescriptor execution
=> [Hotfix] Fix unit test issues

amoro-web/src/components/Sidebar.vue
Close #3371.
Modified interaction from hover to click.
[x] Added test cases to check the loading performance and interaction method.
[x] Conducted manual tests and included screenshots to demonstrate the changes.
[x] Ran tests locally before making this pull request.
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not applicable)
=> [AMORO-3371] Slow Display of Table List in Amoro Interface (#3371)

amoro-optimizer/amoro-optimizer-flink/src/main/java/org/apache/amoro/optimizer/flink/FlinkOptimizerExecutor.java
Close #3367.
- Retry the optimization process when a task fails, and handle unexpected errors that occur while extracting error messages.
=> [AMORO-3367] Avoid throwing StringIndexOutOfBoundsException in flink optimizer executors

amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/SparkUnifiedCatalogBase.java, amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/test/java/org/apache/amoro/spark/test/unified/UnifiedCatalogTestSuites.java, amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/src/main/java/org/apache/amoro/spark/SparkUnifiedCatalog.java
Close #xxx.
- Added the `dropNamespace` to support cascade or non-cascade in `SparkUnifiedCatalogBase` for spark 3.3
- spark 3.2 will use false by default
=> [hotfix] Fix drop database not working in terminal

amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/CommonPartitionEvaluator.java
Close #3391.
- Make sure to rewrite the segment file when the equality delete file exsist.
=> [AMORO-3391] Fix minor optimizing repeated issue

amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/TaskRuntime.java, amoro-ams/src/main/java/org/apache/amoro/server/persistence/StatedPersistentBase.java, amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java, amoro-ams/src/test/java/org/apache/amoro/server/TestDefaultOptimizingService.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/TestOptimizingQueue.java, amoro-common/src/main/java/org/apache/amoro/process/OptimizingStages.java, amoro-common/src/main/java/org/apache/amoro/process/OptimizingState.java, amoro-common/src/main/java/org/apache/amoro/process/ProcessStage.java, amoro-common/src/main/java/org/apache/amoro/process/ProcessStatus.java, amoro-common/src/main/java/org/apache/amoro/process/SimpleFuture.java, amoro-common/src/main/java/org/apache/amoro/process/StagedTaskDescriptor.java, amoro-common/src/main/java/org/apache/amoro/process/TableProcessState.java, amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/RewriteStageTask.java
Close https://github.com/apache/amoro/issues/3258 .
-
=>  Use SimpleFuture to refactor TaskRuntime

amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/iceberg/IcebergSparkFormat.java
The unified catalog does not support the Iceberg change metadata table syntax, which makes it impossible to support the create_changelog_view stored procedure.
```
spark-sql> CALL spark_catalog.system.create_changelog_view(
>   table => 'iceberg_v7.iceberg_overwrite',
>   options => map('start-snapshot-id','486064778759746866','end-snapshot-id', '1216062697090990172'),
>   changelog_view => 'my_changelog_view_4'
> );
ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.9.3 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.9.3 used for parser compilation does not match the current …
```
=> [AMORO-3383] fix: unified catalog should support iceberg  native create_changelog_view procedure

amoro-ams/pom.xml, pom.xml
=> [AMORO-3352]Add mysql-connector-j dependency by maven profile

amoro-web/src/views/optimize/components/List.vue
when optimizerGroup name has value like '/' , the search url will be  "http://127.0.0.1:1630/api/ams/v1/optimize/optimizerGroups/PROD/test/tables?dbSearchInput=&tableSearchInput=&page=1&pageSize=25". it will 404 for server. we should encode optimizerGroup.
when encode , it will be work well.
Close #xxx.
-
- Does this pull request introduce a new feature? (yes / no) 
no
=> [improvement] encode for optimizerGroup value

amoro-ams/src/main/java/org/apache/amoro/server/manager/SparkOptimizerContainer.java
Close #3401.
- When building the Spark config, a step was added to merge the resource group attributes to prevent the configuration of spark.kubernetes.namespace from not taking effect on the resource group.
=> [Hotfix] Spark k8s optimizer release error

amoro-ams/pom.xml, pom.xml
This reverts commit 4be9821704521f8c8a2c9db7e305bae55d1fdccd.
The license of MySQL is incompatible with the Apache License. Please see https://github.com/apache/amoro/issues/3352 for more information
Close #3352 .
- `git revert 4be9821704521f8c8a2c9db7e305bae55d1fdccd`
=> Revert "[AMORO-3352]Add mysql-connector-j dependency by maven profile“

amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/IcebergRewriteExecutor.java, amoro-format-iceberg/src/main/java/org/apache/amoro/table/BasicUnkeyedTable.java, amoro-format-iceberg/src/test/java/org/apache/iceberg/TestIcebergFindFiles.java, amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/pom.xml, amoro-format-mixed/amoro-mixed-flink/v1.15/amoro-mixed-flink-1.15/pom.xml, amoro-format-mixed/amoro-mixed-flink/v1.16/amoro-mixed-flink-1.16/pom.xml, amoro-format-mixed/amoro-mixed-flink/v1.17/amoro-mixed-flink-1.17/pom.xml, amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/pom.xml, amoro-format-mixed/amoro-mixed-spark/v3.2/amoro-mixed-spark-3.2/pom.xml, amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/pom.xml, pom.xml
#3084.
- Upgrade iceberg to 1.6.X
- Mixed Format iceberg version keep to 1.4.3
=> [AMORO-3084] Upgrade to iceberg 1.6.1

amoro-format-mixed/amoro-mixed-hive/src/main/java/org/apache/amoro/hive/catalog/MixedHiveTables.java, amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/src/test/java/org/apache/amoro/spark/test/suites/sql/TestMixedFormatSessionCatalog.java
**format**: mixed_hive
**engine**: spark
**improvement**: the comment does not be passed to hive table when create a mixed_hive table.
-  pass `comment`  when call hms api to create a hive table
=> [AMORO-3389][improvement]support add comment to mixed_hive table

amoro-ams/src/main/java/org/apache/amoro/server/manager/FlinkOptimizerContainer.java, amoro-ams/src/main/resources/mysql/upgrade.sql, amoro-ams/src/main/resources/postgres/upgrade.sql, amoro-ams/src/test/java/org/apache/amoro/server/manager/TestFlinkOptimizerContainer.java, amoro-common/src/main/java/org/apache/amoro/utils/MemorySize.java, amoro-common/src/test/java/org/apache/amoro/utils/MemorySizeTest.java
Currently, when we use flink optimizer groups, the memory parameters `flink-conf.jobmanager.memory.process.size` and `flink-conf.taskmanager.memory.process.size` only support plain numeric strings or strings with `m/g` suffix. If we configure them with mb/gb suffix, we'll get wrong parsed results. And the default unit for plain numeric strings is `mb`, which is inconsistent with the default unit of byte in the flink native parameter and may cause inconvenience for users familiar with flink when using this parameter.
Close #3329.
- Add a new class `MemorySize` to the `amoro-common` module for parsing flink's memory parameters, consistent with flink's native parsing logic.
- Update the values in the column `properties` of ams metadata tables `resource_group` and `resource` to automatically …
=> [AMORO-3329] Add MemorySize for parsing memory value and unit

amoro-ams/src/main/resources/postgres/ams-postgres-init.sql, amoro-ams/src/main/resources/postgres/upgrade.sql
There are syntax errors in the postgresql script:
1. In `ams-postgres-init.sql`, strings in the `COMMENT ON` statement do not support direct concatenation via `||`.
2. In `upgrade.sql`, the `jsonb_set` function is used with mismatched parameter types and incorrect path arguments.
Close #3414.
- Fix the above syntax errors in the scripts `ams-postgres-init.sql` and `upgrade.sql` 
=> [AMORO-3414] Fix syntax errors in postgresql scripts

docs/admin-guides/deployment-on-kubernetes.md, docs/admin-guides/deployment.md, docs/concepts/catalogs.md
=> [AMORO-3404] Correct the description about MySQL usage

amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java, amoro-ams/src/test/java/org/apache/amoro/server/config/TestConfigShade.java, amoro-ams/src/test/resources/configs/config-base64-shade.yaml, amoro-ams/src/test/resources/configs/config-default-shade.yaml, amoro-common/src/main/java/org/apache/amoro/config/shade/ConfigShade.java, amoro-common/src/main/java/org/apache/amoro/config/shade/impl/Base64ConfigShade.java, amoro-common/src/main/java/org/apache/amoro/config/shade/utils/ConfigShadeUtils.java, amoro-common/src/main/resources/META-INF/services/org.apache.amoro.config.shade.ConfigShade, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/tests/amoro-configmap_test.yaml, charts/amoro/values.yaml, dist/src/main/amoro-bin/conf/config.yaml
When we start Amoro Management Service , we need to set configuration items in plaintext in the config file, including sensitive configurations such as admin-password and the passwords for connecting to databases (e.g., mysql, pg, etc.), which may be a security risk. To avoid the use of plaintext passwords, we provide an interface (`ConfigShade`) by implementing which developers can customize the decryption method themselves.
We also provide an implementation for base64 encoding first, not only as an example implementation of the interface, but also to solve the current problem of plaintext passwords.
Close #3335.
- Add interface `ConfigShade` to the `amoro-common` module to provide the ability to customize decryption of sensitive options in the config file
- Provide an implementation …
=> [AMORO-3335] Add interface ConfigShade to support encryption of sensitive configuration items and provide a base64 encoding implementation

amoro-ams/src/main/java/org/apache/amoro/server/AmoroManagementConf.java, charts/amoro/templates/amoro-configmap.yaml, dist/src/main/amoro-bin/conf/config.yaml
… time (#3419)
The default database connection pool max wait time is 1000ms for now.
This is quite small and the wait timeout exception is easy to occur when the database system is a bit busy.
Resolve #3419 .
Change the default value of DB_CONNECT_MAX_WAIT_MILLIS to 30000 in AmoroManagementConf.java(amo-ams).
Change the default value of connection-pool-max-wait-millis to 30000 in amoro-configmap.yaml(charts) and config.yaml(dist).
The reason for choosing 30000 instead of 5000 is that the default connectionTimeout value of HikariCP is 30000 milliseconds (the default value of max-wait-millis of DBCP2 is -1), and the default values ​​of mainstream database connection pools are almost 30000ms or larger.
Does this pull request introduce a new feature?
No
=> [Improvement] Increase the default database connection pool max wait time

amoro-format-iceberg/src/main/java/org/apache/amoro/table/blocker/BasicTableBlockerManager.java, amoro-format-iceberg/src/main/java/org/apache/amoro/table/blocker/RenewableBlocker.java, amoro-format-iceberg/src/test/java/org/apache/amoro/table/blocker/TestBasicTableBlockerManager.java
Close #3410 .
- when we release block, we should cancel the renew future.
=> [AMORO-3410]  cancel renew procedure after releasing block

amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java, amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerController.java, amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerGroupController.java, amoro-ams/src/main/java/org/apache/amoro/server/resource/DefaultOptimizerManager.java, amoro-ams/src/test/java/org/apache/amoro/server/AMSManagerTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/AMSServiceTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/AmsEnvironment.java, amoro-ams/src/test/java/org/apache/amoro/server/TestDefaultOptimizingService.java, amoro-common/src/main/java/org/apache/amoro/resource/ResourceManager.java
=> [AMORO-3348] Extract the implementation of OptimizerManager

amoro-format-iceberg/src/main/java/org/apache/amoro/io/writer/GenericTaskWriters.java, amoro-format-mixed/amoro-mixed-trino/src/test/java/org/apache/amoro/trino/mixed/TestKeyedTable.java
related to https://github.com/apache/amoro/pull/3273#discussion_r1964936857
- set correct write metrics for writers
=> [Hotfix] Set table properties in GenericTaskWriters

amoro-format-iceberg/src/test/java/org/apache/amoro/utils/TestFileUtil.java
- The same method call are repeated multiple times with different inputs in the test `testGetUriPath` making it harder to maintain and extend.
- When the test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
Parameterized test `testGetUriPath`. This reduces duplication, allows easy extension by simply adding new value sets, and makes debugging easier as it clearly indicates which test failed instead of requiring a search through individual assertions.
Test run report after change:
No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not …
=> [Improvement]: Improved test testGetUriPath in TestFileUtil by retrofitting to parameterized test

amoro-common/src/test/java/org/apache/amoro/utils/MemorySizeTest.java
Aim:
Improve the test code by avoiding code duplication, improving maintainability, and enhancing readability. By converting the test into a parameterized unit test, we reduce boilerplate code, make it easier to extend by simply adding new input values, and improve debugging by clearly identifying which test case fails instead of searching through individual assertions.
- The same method call to `toHumanReadableString` is repeated multiple times with different inputs in the test `testToHumanReadableString` making it harder to maintain and extend.
- When this test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
Parameterized the test …
=> [Improvement]: Refactored test testToHumanReadableString of MemorySizeTest to paramerterized

amoro-common/src/test/java/org/apache/amoro/utils/MemorySizeTest.java
Aim:
Improve the test code by avoiding code duplication, improving maintainability, and enhancing readability. By converting the test into a parameterized unit test, we reduce boilerplate code, make it easier to extend by simply adding new input values, and improve debugging by clearly identifying which test case fails instead of searching through individual assertions.
- The same method call to `getKibiBytes`, `getMebiBytes`, `getGibiBytes`, & `getTebiBytes`  are repeated multiple times with different inputs in the tests `testParseKibiBytes`, `testParseMebiBytes`, `testParseGibiBytes`, & `testParseTebiBytes` respectively making them harder to maintain and extend.
- When any of these test fails, JUnit only shows which type of assertion failed, but not which specific input caused the …
=> [Improvement]: Refactored 4 tests in MemorySizeTest to use parameterized unit testing

amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableOptimizingMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableOrphanFilesCleaningMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableRuntime.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableSummaryMetrics.java, amoro-ams/src/test/java/org/apache/amoro/server/AMSManagerTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/table/AMSTableTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestSyncTableOfExternalCatalog.java
Currently, when adding and deleting tables from external catalogs, the `tableIdentifier` is added/deleted first and then the `tableRuntime` is added/deleted sequentially, this may result in a scenario where tableIdentifier deletion succeeds but tableRuntime deletion fails, and the following problems further occur: 
1. The web page displaying tableRuntime list for the specific catalog fails, because these tableRuntimes can not find the corresponding information in the table_identifier table; 
2. tableRuntime retained in the persistence will block the re-insertion of the table, due to the unique key conflicts.
Close #3413.
- When calling `disposeTable()` to dispose of a table, we first remove the tableRuntime before removing the tableIdentifier. This follows the reverse process of the …
=> [AMORO-3413] Optimize execution order when disposing tables

amoro-ams/src/main/java/org/apache/amoro/server/manager/FlinkOptimizerContainer.java, amoro-ams/src/test/java/org/apache/amoro/server/manager/TestFlinkOptimizerContainer.java
Currently, when generating startup commands for the flink optimizer, no double quotes`""` are added to the `flink-conf` parameter values. However, when the user-defined `flink-conf` parameter value contains spaces, this can cause the `${value}` in the `"-D${key}=${value}"` in the final generated startup command to contain spaces and the creation of the optimizer will fail.
For example, when i start a flink optimizer with the following configurations: jobmanager.memory.process.size=1000mb and taskmanager.memory.process.size=2gb, we can only see the following logs, with no ERROR message.
```
2025-03-17 19:29:29,838 INFO [JettyServerThreadPool-175] [org.apache.amoro.server.manager.FlinkOptimizerContainer] [] - Starting flink optimizer using command : export 
HADOOP_USER_NAME=hadoop && export …
```
=> [AMORO-3477] Add double quotes to the flink config values when generating the flink optimizer startup command

amoro-ams/src/main/java/org/apache/amoro/server/AmoroManagementConf.java, charts/amoro/templates/amoro-configmap.yaml, charts/amoro/tests/amoro-configmap_test.yaml
In #3097, we only modified the configuration file template `amoro-ams/dist/src/main/amoro-bin/conf/config.yaml` in the general deployment, but did not modify the relevant default parameters in the configuration file for kubernetes deployments. Further, we did not modify the default values of the internal parameters `ams.sync-hive-tables.enabled` and `ams.data-expiration.enabled`, which may lead to invalidation of the defaults in case of no user configuration in the `config.yaml`.
- Improve the default configuration file of helm charts: `charts/amoro/templates/amoro-configmap.yaml`.
- Modify the default values of the internal management configurations in class `AmoroManagementConf`.
- If yes, how is the feature documented? (not …
=> [Hotfix] Improve the default configuration for AMS internal service and Kubernetes deployment

amoro-web/src/router/index.ts
Close #3487 
Using history mode caused conflicts where frontend routes overlapped with server API endpoints, leading to 404 errors.  
Switching to hash mode ensures the frontend and backend routes remain distinct, preventing such issues.
=> [AMORO-3492] replace history mode with hash mode to avoid access issues

amoro-ams/src/test/java/org/apache/amoro/server/config/TestConfigShade.java
- The underlying test tests the encryption and decryption logic for 2 exact independent flows (Username and Password). Making all the lines repeated twice with different inputs making it harder to maintain and extend.
- When the test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
Parameterized test `testDecryptOption `
This reduces duplication, allows easy extension by simply adding new value sets, and makes debugging easier as it clearly indicates which test failed instead of requiring a search through individual assertions.
Test run report after change:
No
- If yes, how …
=> [Improvement]: Improved test testDecryptOption in TestConfigShade by removing redundancy and converting into Parameterized Test

amoro-ams/src/test/java/org/apache/amoro/server/optimizing/OptimizingStatusTest.java
- The same method call are repeated multiple times with different inputs in the test `testOptimizingStatusDisplayValue` making it harder to maintain and extend.
- When the test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
- The test also had a redundant check of the Number Of Optimizing Statuses.
Parameterized test `testOptimizingStatusCodeValue` and removed the redundant check.
This reduces duplication, allows easy extension by simply adding new value sets, and makes debugging easier as it clearly indicates which test failed instead of requiring a search through individual assertions.
Test run report after change:
- Does this …
=> [Improvement]: Parameterized Test testOptimizingStatusDisplayValue test in OptimizingStatusTest

amoro-ams/src/test/java/org/apache/amoro/server/optimizing/OptimizingStatusTest.java
- The same method call are repeated multiple times with different inputs in the test `testOptimizingStatusCodeValue` making it harder to maintain and extend.
- When the test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
- The test also had a completely independent testing logic related to the Number Of Optimizing Statuses.
Split the original test into 2 tests: `testNumberOfOptimizingStatuses` and a Parameterized test `testOptimizingStatusCodeValue `
This reduces duplication, allows easy extension by simply adding new value sets, and makes debugging easier as it clearly indicates which test failed instead of requiring a search …
=> [Improvement]: Improved test OptimizingStatusTest.testOptimizingStatusCodeValue to use parameterized unit testing

amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/pom.xml, amoro-format-mixed/amoro-mixed-spark/v3.2/amoro-mixed-spark-3.2/src/main/scala/org/apache/amoro/spark/sql/catalyst/analysis/RewriteMixedFormatCommand.scala, amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/src/main/scala/org/apache/amoro/spark/sql/catalyst/analysis/RewriteMixedFormatCommand.scala, amoro-format-mixed/amoro-mixed-spark/v3.5/amoro-mixed-spark-3.5/src/main/scala/org/apache/amoro/spark/sql/catalyst/analysis/RewriteMixedFormatCommand.scala
Enviroment:
format: mixed_hive
engine: spark3.3
catalog: `sparkUnifiedSessionCatalog`
bug:
table created by using `create table like  using mixed_hive`  is not a mixed_hive table.
```
spark-sql> create table ctl_demo(id int ,name string, dt string) using mixed_hive partitioned by (dt);
Time taken: 1.137 seconds
spark-sql> show create table ctl_demo;
CREATE TABLE spark_catalog.amoro_v7.ctl_demo (
id INT,
name STRING,
dt STRING)
USING mixed_hive
PARTITIONED BY (dt)
TBLPROPERTIES (
'base.hive.location-root' = 'hdfs://easyops-cluster/user/warehouse/amoro_v7.db/ctl_demo/hive',
'base.write.format' = 'parquet',
'delta.write.format' = 'parquet',
'flink.max-continuous-empty-commits' = '2147483647',
'schema.name-mapping.default' = '[ {
"field-id" : 1,
"names" : [ "id" ]
}, {
"field-id" : 2,
"names" …
```
=> [AMORO-3387]fix: create table like using mixed_hive

amoro-optimizer/amoro-optimizer-flink/src/main/java/org/apache/amoro/optimizer/flink/FlinkExecutor.java, amoro-web/src/router/index.ts
Close #3502.
1. In the close method, in addition to setting the worker thread exit flag, the worker thread is also gracefully exited.
2. If the worker thread does not exit, it may cause the problem of repeatedly creating multiple worker threads in some scenarios, which may cause OOM problems due to the existence of multiple worker threads.
=> [Bug]: The flink optimizer often triggers OOM exceptions. In fact, the files processed by each task are not large.

amoro-ams/src/main/java/org/apache/amoro/server/catalog/DefaultCatalogManager.java, amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java, amoro-ams/src/test/java/org/apache/amoro/server/table/TestSyncTableOfExternalCatalog.java
Currently when synchronizing the external directory and fetching the database table list fails, an empty `HashSet` is returned in `DefaultTableService#exploreExternalCatalog()`, which causes the database to be considered to contain 0 tables and triggers the removal of all its tables.
Close #3533.
- Throw an exception instead of returning an empty set when fetching the list of tables for a database fails.
=> [AMORO-3533] Avoid bulk table removal when synchronizing external catalogs and fetching database table listings fails

pom.xml
Close https://github.com/apache/amoro/issues/3538
- Update Hive dependency in hadoop2 profile.
=> [AMORO-3538] Resolve Hive 4 Metastore listing failure on Hadoop2

amoro-ams/src/main/java/org/apache/amoro/server/table/AbstractTableMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableOptimizingMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableOrphanFilesCleaningMetrics.java, amoro-ams/src/main/java/org/apache/amoro/server/table/TableSummaryMetrics.java
In the current implementation, each specific metric class (i.e. “TableOptimizingMetrics”, “TableOrphanFilesCleaningMetrics”, “TableSummaryMetrics") all contain similar logic and duplicate code for registering and unregistering metrics. This duplication makes the metrics more difficult to maintain and extend. To improve code maintainability and reduce redundancy, we introduce a generic abstract class `TableMetrics`.
Close #3559.
- Create `TableMetrics` abstract class
- Update `TableOptimizingMetrics`, `TableOrphanFilesCleaningMetrics`, and `TableSummaryMetrics` to extend `TableMetrics`.
=> [AMORO-3559] Extract abstract class for table metrics

amoro-format-hudi/src/main/resources/META-INF/services/org.apache.amoro.table.descriptor.FormatTableDescriptor
In the resources under the Amoro-format-hudi module, should fill in org.apache.amoro.formats.hudi.HudiTableDescriptor instead of paimon
Close #xxx.
-
- Does this pull request introduce a new feature? (yes / no) NO
=> [Hotfix] Fix HudiTableDesctiptor error

charts/amoro/templates/_pod.tpl, charts/amoro/tests/amoro-deployment_test.yaml
Currently, when setting amoroConf.log4j2 to non-null value in values.yaml, the generated helm chart has an indentation error that makes it invalid yaml. The error looks like the following in amoro-deployment.yaml.
```
Error: yaml: line 93: block sequence entries are not allowed in this context
```
Close #3549 .
- This commit fixes an erroneous helm comment which swallows unnecessary newline.
=> [AMORO-3549] Fix AMS helm chart cannot set log4j2 because of wrong indentation

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java
Close #3582.
- Optimize the implementation of the TableOptimizingProcess.poll() function to avoid waiting for locks and return immediately if the lock cannot be acquired.
=> Optimize the performance of optimizer pollTask

amoro-ams/src/main/java/org/apache/amoro/server/catalog/CatalogBuilder.java, amoro-common/src/main/java/org/apache/amoro/properties/CatalogMetaProperties.java, docs/admin-guides/managing-catalogs.md
Close #3587.
- Fixed the default value of clients to 20 and set the clients parameter when creating an external Hive metastore catalog.
- Added description of the clients parameter in the docs/admin-guides/managing-catalogs.md document
=> [AMORO-3587] Modify the default value of hive catalog clients to 20

amoro-optimizer/amoro-optimizer-flink/pom.xml
The current version of kryo included in amoro is 4.0.3. After 2.24.0, the groupId of kryo dependency has been changed to com.esotericsoftware (e.g. com.esotericsoftware:kryo:4.0.3), which caused the previous exclusion to fail to block kryo: 4.0.3 packaged into the flink optimizer dependency.
Close #3599.
- Update groupId of kryo dependency `com.esotericsoftware.kryo` to `com.esotericsoftware`
=> [AMORO-3599] remove com.esotericsoftware.kryo dependencies in flink optimizer package

docs/admin-guides/managing-optimizers.md
Close [#3616](https://github.com/apache/amoro/issues/3616)
Fix the spelling errors in doc of Managing Optimizers page.
- Does this pull request introduce a new feature? (no) 
=> [AMORO-3616][Improvement] Correct the spelling errors in doc of Managing Optimizers page

amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OverviewController.java
Close #3633 .
- Change the sorting rule of the table order by health score to compare the health scores instead of the table size.
=> [AMORO-3633][improvement]: Fix the sorting rules of topTables order by healthScore

amoro-ams/src/main/java/org/apache/amoro/server/AmoroManagementConf.java, amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/test/java/org/apache/amoro/server/AMSServiceTestBase.java, amoro-ams/src/test/java/org/apache/amoro/server/TestDefaultOptimizingService.java, dist/src/main/amoro-bin/conf/config.yaml
Currently, when the optimizer exits abnormally while executing a task or when there is an exception in the thrift communication between the optimizer and ams, ams fails to update the taskRuntime status, even though the task has already finished executing.  And the optimization process is also stuck in the running phase blocking the subsequent optimization.
Therefore, we need to add a task execution timeout detection in ams to stop and re-run the timeout task in ACK to prevent blocking the subsequent optimization process.
Close #3638.
- Add an amoro management configOption `optimizer.task-execute-timeout`
- Detect and retry the timeout taskRuntimes in the `optimizer-keeper-thread`
- If yes, how is the feature documented? (not …
=> [AMORO-3638] Add support for task retries when task execution times out

amoro-ams/src/main/resources/mysql/ams-mysql-init.sql
Close #3607 .
- Revise incorrect filed name in pk delcaration in ddl
- If yes, how is the feature documented? (not applicable )
=> [AMORO-3607]Fix syntax error in init sql #3607

amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/AbstractRewriteFilesExecutor.java
Close #3703.
- If the user has not set `write.delete.format.default`, we should use dataFileFormat
=> [AMORO-3703] Use dataFileFormat for deleteFile if not set

amoro-ams/src/main/java/org/apache/amoro/server/scheduler/PeriodicTableScheduler.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/BlockerExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/DanglingDeleteFilesCleaningExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/DataExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/HiveCommitSyncExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/OptimizingCommitExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/OptimizingExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/OrphanFilesCleaningExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/SnapshotsExpiringExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/TableRuntimeRefreshExecutor.java, amoro-ams/src/main/java/org/apache/amoro/server/scheduler/inline/TagsAutoCreatingExecutor.java
Close #3658.
Reduce the probability of each executor#executor() being called at the same time by changing each executor's getStartDelay() to a random value within a certain range to mitigate the dramatic increase in the number of metastore connections
=> [AMORO-3658] Modify the execution interval of the executor from fixed to a range of random values.

amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java, amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/src/main/java/org/apache/amoro/flink/catalog/MixedCatalog.java
Close #3716 .
- Improve the logic of getting table from internal catalog inside getTable method of FlinkUnifiedCatalog via reducing number of calling 'load table'.
=> [AMORO-3716]Enhance FlinkUnifiedCatalog getTable efficiency

amoro-ams/src/main/java/org/apache/amoro/server/optimizing/SchedulingPolicy.java
=> [AMORO-3755][Improvement]: Optimize log output of SchedulingPolicy 

pom.xml
…y-codec-http2
Close #3788.
- Following the approach outlined in this [PR](https://github.com/apache/amoro/pull/3653) to address the netty-handler vulnerability, I opted to upgrade the Netty version to 4.1.124.Final to resolve the vulnerability in netty-codec-http2.
=> [AMORO-3788] Bump Netty version to 4.1.124.Final to fix up vulnerabilities in netty-codec-http2

amoro-ams/src/main/java/org/apache/amoro/server/table/TableOptimizingMetrics.java
Close #3786 
- Add the missing counter increment for the `table_optimizing_process_failed_count` metric.
=> [AMORO-3786] Add missing logic to count failed optimizing processes

amoro-common/src/main/java/org/apache/amoro/properties/CatalogMetaProperties.java, amoro-format-iceberg/src/main/java/org/apache/amoro/table/TableProperties.java, amoro-format-iceberg/src/main/java/org/apache/amoro/utils/MixedFormatCatalogUtil.java, amoro-format-iceberg/src/test/java/org/apache/amoro/utils/TestMixedFormatCatalogUtil.java, amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java, amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/src/test/java/org/apache/amoro/flink/catalog/FlinkCatalogContext.java, amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/SparkUnifiedCatalogBase.java
=> [AMORO-3470][Feature]:Support catalog-level default properties storing into underlying tables within a unified catalog

amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java, amoro-ams/src/main/java/org/apache/amoro/server/optimizing/TaskRuntime.java, amoro-ams/src/test/java/org/apache/amoro/server/dashboard/utils/TestOptimizingUtil.java, amoro-ams/src/test/java/org/apache/amoro/server/optimizing/TestOptimizingQueue.java
#3399 removed lock protection from [StatedPersistentBase.java](https://github.com/apache/amoro/commits/master/amoro-ams/src/main/java/org/apache/amoro/server/persistence/StatedPersistentBase.java) and lead to some unexpected issue like #3794.
This PR tried to wrap all operations on the `TaskRuntime` with the `TableOptimizingProcess` lock, which will resolve the conflict operation errors on `TaskRuntime`, besides preventing the deadlock issue like #2623.
Close #3794.
- Wrap all task operations with the process lock
=> [AMORO-3794] Wrap task operation with process lock
