apache/amoro

- core/src/main/java/com/netease/arctic/io/writer/GenericTaskWriters.java
Pos-Delete file's lowerbounds/upperbounds of file path is too short, default is truncate(16)
https://iceberg.apache.org/docs/latest/configuration/
write.metadata.metrics.default
> lower_bounds/upper_bounds of pos-delete file use MetricsModes.Full

- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
Maybe flink ut blocked by mini cluster's starving for resources
> [flink] mini cluster block ut

- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
Reverts NetEase/arctic#45. Still blocking ut process sometimes.
> Revert "[flink] mini cluster block ut"

- .github/workflows/core-ci.yml
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/PartitionAndNodeGroup.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/assigner/ShuffleSplitAssigner.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/split/ArcticSplit.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/split/ChangelogSplit.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/split/SnapshotSplit.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkSink.java
1. Add flink 1.14 into ci
2. Fix flink 1.14 compile exception
> [flink] Add flink 1.14 into ci. And fix flink 1.14 compile exception

- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkCatalog.java
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/parser/ArcticSqlExtensionsParser.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/CreateArcticTableLikeExec.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/ExtendedArcticUnkeyedStrategy.scala
- spark/v3.1/spark/src/main/scala/org/apache/spark/sql/catalyst/parser/ArcticCreateTablePrimaryKeyAstBuilder.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedTableDDL.java
support `create table ... like ...` grammar from keyed table
> create table like

- ams/ams-server/pom.xml
- pom.xml
- spark/pom.xml
- spark/v2.3/spark/pom.xml
- spark/v2.3/spark/src/main/antlr4/com/netease/arctic/spark/sql/parser/ArcticSparkSql.g4
- spark/v2.3/spark/src/main/antlr4/imports/SqlBase.g4
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/reader/ArcticReader.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/ArcticSource.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/DataSourceTable.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/OverwriteSupport.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/TableSupport.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/util/ArcticSparkUtil.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/writer/ArcticWriter.java
- spark/v2.3/spark/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/ArcticSparkExtensions.scala
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/ArcticResolutionDelegateHiveRule.scala
> Feature spark 2.3 structure

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/ArcticScanContext.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/ArcticScanContext.java
- site/docs/ch/flink.md
- site/docs/en/flink.md
> [Flink] Support scan.startup.mode Configuration when Query Keyed Table by Flink SQL

- .github/workflows/spark-ci.yml
- .github/workflows/trino-ci.yml
> run spark trino ci only file modified

- .github/workflows/ams-ci.yml
- .github/workflows/core-ci.yml
- .github/workflows/flink-ci.yml
- .github/workflows/trino-ci.yml
speed up ci-cd
spark-ci.yml:  run only  spark module changed.   execute spark module && ams-server unit test 
flink-ci.yml:  run only flink module changed.  excute flink module unit test 
ams-ci.yml : run only  ams-server and optimize module changed. excute  ams-server and optimizer module unit test 
core-ci.yml: run when core/hive/api changed and excute core all module unit test
> speed up github ci/cd

- hive/src/main/java/com/netease/arctic/hive/table/KeyedHiveTable.java
- hive/src/main/java/com/netease/arctic/hive/table/SupportHive.java
- hive/src/main/java/com/netease/arctic/hive/table/UnkeyedHiveTable.java
a mix-in interface for mark table is adapt with hive
> [hive] add interface of SupportHive

- site/docs/ch/docker-quickstart.md
- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/spark/spark-get-started.md
Add env preparation without docker.
> [doc] flink doc opt

- flink/v1.12/flink-runtime/pom.xml
- flink/v1.14/flink-runtime/pom.xml
Add the flink-version in the flink-runtime modules.
> [Flink] Add Flink version properties in the flink-runtime module pom.xml

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/TableController.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/DDLRecordMapper.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableOperation.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/controller/TableControllerTest.java
add operations tab to table detail tab list
link https://github.com/NetEase/arctic/issues/116
> [ARCTIC-116][AMS]   Support table operations tab

- spark/v3.1/spark/pom.xml
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/DescribeKeyedTableExec.scala
#182 
add scala version into sparkV3.1 pom, and optimize desc
> fix desc and add scala to pom

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/TableController.java
add filters when return database list or table list
link[#115](https://github.com/NetEase/arctic/issues/115)
> [ARCTIC-115][ams]  support filter database or table by keywords 

- hive/src/main/java/com/netease/arctic/hive/op/ReplaceHivePartitions.java
- pom.xml
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/ArcticSparkHiveMainTest.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestHive.java
change pom for compatible with hive 2.1.1 & 2.3.7
> change pom for compatible with hive

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/improvement.yml
- .github/PULL_REQUEST_TEMPLATE
Address issue and pull request templates are not an available problem in the Arctic project.
- *Change the license at the head of templates*
- *Change the example of the pull request template*
- *Add the documentation in the pull request template*
> [ARCTIC-219] Address issue and pr templates are not available problem

- core/src/main/java/com/netease/arctic/io/writer/CommonOutputFileFactory.java
- hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveOutputFileFactory.java
Add uuid to no primary key table file name generation rule
> Fix no primary key table file name generation rule

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/FileInfoCacheMapper.java
improved https://github.com/NetEase/arctic/issues/270
some thread will not stop while cache InterruptedException
stop thread while cache InterruptedException
none
> stop thread while cache InterruptedException

- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
* The UGI reconstruction may cause an error indicating that the link to Hive Meta Store is closed by peer
- remove reconstruct ugi
An environment test was created to test
> [WIP] fix HMS cannot be connected in some cases

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveMajorOptimizePlan.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsEnvironment.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java
> Revert "Fix table runtime current snapshot"

- site/docs/ch/meta-service/dashboard.md
*Add 0.3.1 ArcticHiveCatalog doc config
- *Change doc, add how to configure ArcticHiveCatalog
- No need for test
> [Doc-284] Add the doc about AMS module adapt Hive

- site/config/ch/mkdocs.yml
- site/docs/ch/flink/flink-dim.md
- site/docs/ch/flink/flink-dml.md
- site/docs/ch/flink/flink-get-started.md
Address the Flink Dim and hive documentation format.
- *change the documentation of flink-dim.md and flink-quick-start.md*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) docs
> [hotfix][Flink] Address Flink DIM and hive documentation formats

- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java
fix #296 
Flower up flink-1.14 and flink-1.15
- *update the default value of the ArcticValidator.*
> [ARCTIC-296] hotfix: avoid submitting empty snapshots by default

- site/docs/ch/flink/flink-dim.md
#127 The Arctic Flink has supported the Arctic table as a dimension table in the Lookup Join scenario, but no performance tests have been done on this part of the functionality. We should run performance tests on this feature.
- *Add Flink temporal join performance test documentation in the flink chapter*
> [Doc]: Adding Flink temporal join performance test document

- ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/OptimizeManagerClientPools.java
- hive/src/main/java/com/netease/arctic/hive/op/HiveSchemaUpdate.java
- hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java
- hive/src/test/java/com/netease/arctic/hive/HiveTableTestBase.java
- hive/src/test/java/com/netease/arctic/hive/op/AutoSyncHiveTest.java
- hive/src/test/java/com/netease/arctic/hive/utils/HiveMetaSynchronizerTest.java
Fix #287.
- *Support synchrionize hive struct type to arctic*
- *Fix authentication propblem when synchrionize hive data write to arctic*
- *Format imports for hive moduel*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)  not documented
> [ARCTIC-287][Hive] support synchronize hive type struct to arctic

- site/config/ch/mkdocs.yml
- site/docs/ch/roadmap.md
Implement #221 
- *add roadmap.md in site*
- *add roadmap page nav*
none
> [ARCTIC-221][Docs]Add roadmap page in site

- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
> Revert "[WIP] fix HMS cannot be connected in some cases"

- .github/workflows/trino-ci.yml
- ams/ams-api/pom.xml
- ams/ams-dashboard/pom.xml
- ams/ams-server/pom.xml
- ams/pom.xml
- core/pom.xml
- dist/pom.xml
- flink/pom.xml
- flink/v1.12/flink-format/pom.xml
- flink/v1.12/flink-runtime/pom.xml
- flink/v1.12/flink/pom.xml
- flink/v1.14/flink-format/pom.xml
- flink/v1.14/flink-runtime/pom.xml
- flink/v1.14/flink/pom.xml
- flink/v1.15/flink-format/pom.xml
- flink/v1.15/flink-runtime/pom.xml
- flink/v1.15/flink/pom.xml
- hive/pom.xml
- optimizer/pom.xml
- pom.xml
- spark/pom.xml
- spark/v2.3/spark/pom.xml
- spark/v3.1/spark-runtime/pom.xml
- spark/v3.1/spark/pom.xml
- trino/pom.xml
*Update project version to 0.3.1*
- *Update project version to 0.3.1 in pom.xml*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not documented
> Update project version to 0.3.1

- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/meta-service/dashboard.md
- site/docs/ch/spark/spark-get-started.md
*Change download package version to 0.3.1-rc1*
- *Change download package version to 0.3.1-rc1*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not documented
> [Docs]change package version to v0.3.1 in doc url

- site/docs/ch/meta-service/dashboard.md
> add HA doc

- ams/ams-server/pom.xml
- site/docs/ch/meta-service/dashboard.md
resolve https://github.com/NetEase/arctic/issues/48
upgrade mysql connector version to 8.0.30
none
- If yes, how is the feature documented? ( docs)
> [ARCTIC-48][AMS]upgrade mysql connector version to 8.0.30

- core/src/test/java/com/netease/arctic/TableTestBase.java
- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunction.java
- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunction.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/hybrid/reader/RowDataReaderFunction.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/FlinkTestBase.java
fix #326 
It may cause exception when read arctic table.
- *Fix the fileOffsetIndex*
> [ARCTIC-326] Hotfix read fileoffset

- hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
> [Hive] Fix a typing mistake.

- site/docs/ch/meta-service/table-properties.md
fix a small link that does't refer to suitable page for better understanding.
> [Docs] update the link about changing table properties.

- core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedPosDeleteSparkWriter.java
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteUpdateArcticTable.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestUnkeyedTableDml.java
Fix the following bugs
1.Updating column value with decimal、double and float type will fail in Spark
2.Updating data across multiple partitions will fail in Spark
- *Fix bugs related to Spark SQL Update*
> [Spark]fix update bug

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/CreateArcticTableLikeExec.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/ExtendedArcticStrategy.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/delegate/TestArcticSessionCatalog.java
*Support ArcticSparkSessionCatalog to use "create table like" in spark*
> [Spark]Support ArcticSessionCatalog to create table like

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
Reslove  #375 
* Some pages cannot be redirected to the login page
- *Add more path redirect the static page url to index.html
> [BUG-375] Some pages cannot be redirected to the login page

- site/docs/ch/table-format/hive-format.md
fix #374 
- *modify doc about optimize support hive*
> [ARCTIC-374][doc]modify doc about optimize support hive

- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/writer/ArcticUnkeyedSparkOverwriteWriter.java
- spark/v2.3/spark/src/test/java/com/netease/arctic/spark/ArcticSparkMainTest.java
- spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestKeyedHiveTableInsertOverwriteDynamic.java
- spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestUnkeyedHiveTableInsertOverwriteDynamic.java
Feature spark2.3's unkeyed writer 
- *Complete Spark2.3 Unkeyed writer *
- *Complete ut*
> [Spark] Feature spark2.3 unkeyed writer

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteUpdateArcticTable.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
*No errors will be reported when updating the primary key. An exception will now be thrown*
> [SPARK] Update Primary Key Will Throw Exception

- site/docs/ch/contribute.md
- site/docs/ch/docker-quickstart.md
- site/docs/ch/meta-service/dashboard.md
- site/docs/ch/meta-service/table-management.md
- site/docs/ch/spark/spark-conf.md
- site/docs/ch/spark/spark-dataframe.md
- site/docs/ch/spark/spark-ddl.md
- site/docs/ch/spark/spark-dml.md
- site/docs/ch/spark/spark-get-started.md
- site/docs/ch/table-format/hive-format.md
- site/docs/ch/trino.md
Arctic Spark 0.3.2 support Insert/update/delete to primary key table，so update spark doc.
https://arctic.netease.com/ch/spark/spark-dml/#select-from-change-table
> [SPARK]Update the Spark document Adds the insert, update and delete of the primary key table

- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/io/TaskWriters.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedSparkBatchWrite.java
Spark v3.1 Unkeyed PosDelete Writer add uncheck txId
> [SPARK]Spark v3.1 Unkeyed PosDelete Writer add uncheck txId

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #410
- After poll task, if failed to load files from sysdb, put task back to queue
- If failed to put task back to queue, set task status to failed, then it could retry later
> [ARCTIC-410] fix optimize hang up if failed to connect to sysdb

- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/ArcticSource.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/ArcticSparkTable.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/source/TableSupport.java
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/ArcticSparkExtensions.scala
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/rule/ArcticResolutionDelegateHiveRule.scala
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/rule/ArcticStrategies.scala
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/rule/PreprocessArcticTableInsertionRule.scala
- spark/v2.3/spark/src/main/scala/com/netease/arctic/spark/sql/plan/OverwriteArcticTableDynamic.scala
- spark/v2.3/spark/src/test/java/com/netease/arctic/spark/ArcticSparkMainTest.java
- spark/v2.3/spark/src/test/java/com/netease/arctic/spark/TestComplexType.java
Feature spark 2.3 double flout write
- *Add spark 2.3 insert logical plan*
- *Add cast types in insert plan*
- *Add complex type test*
- Does this pull request introduces a new feature? (yes )
> [Spark] Feature spark 2.3 double flout write

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/Utils.java
Reslove #415 
* Some interfaces should not be blocked
- *Add token white list
- *Add interface white list
> [ARCTIC-415] Relax part of the check in AMS-Server

- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/SparkInternalRowCastWrapper.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/SimpleKeyedUpsertDataWriter.java
Update keyed table will write insert file and eq-delete file. The offset of the original two files is different.Now modify the two files so that they have the same offset
> [SPARK]Optimize Spark update keyed table

- site/docs/ch/flink/flink-dim.md
- site/docs/ch/flink/flink-dml.md
modify Flink doc to add a Flink version of the dim file and removed some unnecessary parameters in the dml file
- *modify Flink dim and dml documentation content*
> [hotfix][Flink]modify Flink dim and dml documentation content

- ams/ams-api/pom.xml
- ams/ams-dashboard/pom.xml
- ams/ams-server/pom.xml
- ams/pom.xml
- core/pom.xml
- dist/pom.xml
- flink/pom.xml
- flink/v1.12/flink-format/pom.xml
- flink/v1.12/flink-runtime/pom.xml
- flink/v1.12/flink/pom.xml
- flink/v1.14/flink-format/pom.xml
- flink/v1.14/flink-runtime/pom.xml
- flink/v1.14/flink/pom.xml
- flink/v1.15/flink-format/pom.xml
- flink/v1.15/flink-runtime/pom.xml
- flink/v1.15/flink/pom.xml
- hive/pom.xml
- optimizer/pom.xml
- pom.xml
- spark/pom.xml
- spark/v2.3/spark-runtime/pom.xml
- spark/v2.3/spark/pom.xml
- spark/v3.1/spark-runtime/pom.xml
- spark/v3.1/spark/pom.xml
- trino/pom.xml
resolve https://github.com/NetEase/arctic/issues/455
master branch pom version should be xxx-SNAPSHOT
change pom version to xxx-SNAPSHOT
> [ARCTIC-455]change pom version

- site/docs/ch/spark/spark-dml.md
Change spark dml doc, add note to Insert Into Primary keyed table
> [SPARK]Change spark dml doc, add note to Insert Into

- site/docs/ch/flink/flink-get-started.md
*Describe the supported Kafka versions in the arctic logstore documentation.*
Fix #49 
> [ARCTIC-49] Which kafka versions does the logstore support.

- hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java
Fix kerberos auth in CachedHiveClientPoll.
- *Add doAs in CachedHiveClientPool*
- *Throw right exception*
> [Hive] Fix kerberos authenticate

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java
#462 
Iceberg has rewrite check when add DataFiles is empty.
- *when major commit, if add DataFiles is empty, rewrite can delete DeleteFiles together*
> [ARCTIC-462][AMS] fix addDataFiles is empty when major optimize

- ams/ams-server/pom.xml
- optimizer/pom.xml
fix #489 
start optimizer with zookeeper ams uri error
change pom for depency conflix
> [ARCTIC-489]: start optimizer with zookeeper ams uri error

- site/docs/ch/benchmark.md
*There is something wrong with the description of the SQL statement part for the TPC-H queries in the benchmark documentation, which needs to be fixed.*
- *Replaced SQL statements related to TPC-H queries*
> [Doc][benchmark] Fixed the incorrect description of the TPC-H query statement

- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/meta-service/dashboard.md
- site/docs/ch/spark/spark-get-started.md
Change version to 0.3.2 in site.
- *Change version to 0.3.2 in site.*
> [Doc]Change version to 0.3.2 in site

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/FullOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MajorOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/MinorOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/ContentFileUtil.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestMajorExecutor.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestMinorExecutor.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestSupportHiveMajorExecutor.java
- optimizer/src/test/java/com/netease/arctic/optimizer/util/ContentFileUtil.java
fix #509
- *Optimize plan get file format from table property*
> [ARCTIC-509][AMS] Optimize plan get file format from table property

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #512 
- *if table is running, add failed tasks to execute*
> [ARCTIC-512][AMS] if table is running, add failed tasks to execute

- docker/ams/Dockerfile
- docker/flink/Dockerfile
- site/docs/ch/docker-quickstart.md
Dockerfile version change
- *Change version of Dockerfile and push images to DockerHub*
- *Change some SQL in quick start doc*
> [Docker] Dockerfile version change

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/improvement.yml
- .github/ISSUE_TEMPLATE/subtask.yml
Resolve #406 
- *Add subtask issue template*
- *Add subtasks input options for feature/improvement issue template*
> [ARCTIC-406]Add  subtask issue template

- docker/ams/Dockerfile
- docker/flink/Dockerfile
- site/docs/ch/docker-quickstart.md
Docker version ARG for convenient
- *Add ARCTIC_VERSION and RELEASE ARG in Dockerfile*
> [Docker] Docker version ARG

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/write/FlinkTaskWriterBuilder.java
Fix flink write change of compatible hive table
(cherry picked from commit a9666b3646ddbdf41983a484b70c099dee98f8da)
> Fix flink write change of compatible hive table (#533)

- site/docs/ch/ambari-hadoop-install.md
*(For example: The Arctic Flink dataStream API has already supported this configuration: 'scan.startup.mode', but it is not available with Flink SQL. We should expose this configuration to users when they are using Flink SQL.)*
- *Add the 'scan.startup.mode' configuration to the ArcticScanContext in the flink modules*
- *The flink 1.12 and 1.14 versions are affected.*
> Add ambari-hadoop install docs

- LICENSE
- hive/src/main/java/org/apache/iceberg/data/AdaptHiveGenericAppenderFactory.java
- hive/src/main/java/org/apache/iceberg/data/parquet/AdaptHiveBaseParquetReaders.java
- hive/src/main/java/org/apache/iceberg/data/parquet/AdaptHiveBaseParquetWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveColumnWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquet.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetConversions.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetDictionaryRowGroupFilter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetMetricsRowGroupFilter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetReader.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetSchemaUtil.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHivePrimitiveWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveReadConf.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveTypeToMessageType.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveReader.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveWriter.java
- hive/src/test/java/com/netease/arctic/hive/io/TestIOUtils.java
- pom.xml
Support int96 type  predicate push down in pqrquet
> Support int96 type predicate push down

- LICENSE
- hive/src/main/java/org/apache/iceberg/data/AdaptHiveGenericAppenderFactory.java
- hive/src/main/java/org/apache/iceberg/data/parquet/AdaptHiveBaseParquetReaders.java
- hive/src/main/java/org/apache/iceberg/data/parquet/AdaptHiveBaseParquetWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveColumnWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquet.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetConversions.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetDictionaryRowGroupFilter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetMetricsRowGroupFilter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetReader.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetSchemaUtil.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveParquetWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHivePrimitiveWriter.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveReadConf.java
- hive/src/main/java/org/apache/iceberg/parquet/AdaptHiveTypeToMessageType.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveReader.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveWriter.java
- hive/src/test/java/com/netease/arctic/hive/io/TestIOUtils.java
- pom.xml
* Support int96 type predicate push down
(cherry picked from commit a8832083446385adf7f4c73606823f02d28cc7c4)
> Support int96 type predicate push down (#542)

- core/src/main/java/com/netease/arctic/io/reader/ArcticDeleteFilter.java
- core/src/main/java/com/netease/arctic/io/reader/BaseArcticDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergPosDeleteReader.java
- core/src/main/java/com/netease/arctic/io/writer/GenericTaskWriters.java
- core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java
- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
- hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MajorExecutor.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MinorExecutor.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedPosDeleteSparkWriter.java
fix #543 
- *add doAs when read data files*
- *use ArcticFileIo to create pos-delete files*
> [ARCTIC-543][Optimizer] Fix Kerberos problem in Optimizer

- ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ArcticThriftUrl.java
resolve #515
change [regular expression](javascript:;)
> [ARCTIC-515]Including an line-through in the arctic HA property causes the catalog to load failed

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeCheckTask.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- core/src/main/java/com/netease/arctic/table/TableProperties.java
- site/docs/ch/meta-service/table-properties.md
fix #524 
- add table property 'optimize.execute.timeout' with default 30min
- check task execute timeout periodically
> [ARCTIC-524][OPTIMIZE] add optimize execute timeout table property

- core/src/main/java/com/netease/arctic/io/reader/BaseArcticDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergDataReader.java
- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveBaseArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveBaseIcebergDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveGenericArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/GenericAdaptHiveIcebergDataReader.java
- hive/src/test/java/com/netease/arctic/hive/HiveTableTestBase.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveWriter.java
- hive/src/test/java/com/netease/arctic/hive/io/TestIOUtils.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkKeyedDataReader.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkUnkeyedDataReader.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkKeyedDataReader.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkUnkeyedDataReader.java
fix #551 ,Reader don't use adapt hive parquet reader in #551 
> [HIVE][FLINK][SPARK]Fix reader not use adapt hive parquet reader

- core/src/main/java/com/netease/arctic/io/reader/BaseArcticDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergDataReader.java
- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/source/FlinkArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveBaseArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveBaseIcebergDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/GenericAdaptHiveIcebergDataReader.java
- hive/src/test/java/com/netease/arctic/hive/io/TestAdaptHiveWriter.java
- hive/src/test/java/com/netease/arctic/hive/io/TestIOUtils.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkKeyedDataReader.java
- spark/v2.3/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkUnkeyedDataReader.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkKeyedDataReader.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/ArcticSparkUnkeyedDataReader.java
Fix reader not use adapt hive parquet reader
(cherry picked from commit 82a73d9167169ca355108f18fb1b194d0087fb38)
> [HIVE][FLINK][SPARK]Fix reader not use adapt hive parquet reader (#567)

- .github/workflows/ams-ci.yml
- .github/workflows/core-ci.yml
- .github/workflows/flink-ci.yml
- .github/workflows/spark-ci.yml
- .github/workflows/trino-ci.yml
Add ci configs for release branches named like '0.x.x'
- *Change github ci configs for release branches*
> [Github]add ci config for release branches

- site/docs/ch/flink/flink-ddl.md
- site/docs/ch/flink/flink-dml.md
> [ARCTIC-557][FLINK] Doc catalog authorization configs

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/utils/ArcticAuthUtil.scala
resolve #582 
provider a standrad method to covert arctic command to auth operation type. this method will avoid to submit to PR to kyuubi once arctic add or change LogicalPlan name.
> [SPARK]Standrad auth utils method for kyuubi

- core/src/main/java/com/netease/arctic/io/reader/BaseArcticDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/BaseIcebergPosDeleteReader.java
- core/src/main/java/com/netease/arctic/io/writer/GenericTaskWriters.java
- core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java
- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
- hive/src/main/java/com/netease/arctic/hive/io/writer/AdaptHiveGenericTaskWriterBuilder.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MajorExecutor.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/MinorExecutor.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedPosDeleteSparkWriter.java
fix #543 
- *add doAs when read data files*
- *use ArcticFileIo to create pos-delete files*
> [ARCTIC-543][Optimizer] Fix kerberos optimizer

- dev/merge_arctic_pr.py
*Add a PR merge script wich support merging and cherry-picking PR*
- *Add merge_arctoc_pr.py to support merging and cherry-picking PR*
> [Github]Add PR merge script

- ams/ams-server/src/main/resources/sql/mysql/0.4.0-init.sql
- ams/ams-server/src/main/resources/sql/mysql/upgrade-0.3.2-to-0.4.0.sql
- ams/ams-server/src/main/resources/sql/mysql/upgrade-0.3.2-to-0.4.sql
change 0.4.0-init.sql because 0.3.2-init.sql is changed
add 0.3.2-init.sql change to 0.4.0-init.sql
> [AMS] change 0.4.0-init sql file

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- site/docs/ch/flink/flink-dml.md
resolve #598 
Update doc with code in flink file reading.
Sync 1.14, 1.15 with 1.12.
- *The flink 1.14 and 1.15 versions are affected.*
- *Update the documentation in the flink chapter*
> [ARCTIC-598][FLINK] Update the documentation in the Flink DML section

- site/docs/ch/meta-service/dashboard.md
add high availability doc
add high availability catalog uri doc
> [DOC] add high availability doc

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/config/ArcticMetaStoreConf.java
*improve #610 *
- *Add arctic.ams.thrift.worker.threads, arctic.ams.thrift.selector.threads, arctic.ams.thrift.selector.queue.size for ams thrift*
- *modify default value for thrift thread config*
> [ARCTIC-610][ams]optimize thrift default config

- site/docs/ch/meta-service/dashboard.md
*Add description about Hadoop/Hive version Arctic supported in user documention.*
- *Add description about Hadoop/Hive version Arctic supported in user documention*
- *Change some description about creating catalog in user documention*
> [ARCTIC-356][Doc]add Hadoop/Hive version supported message in user documention

- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
resolve #614 
- *move error log location*
> [ARCTIC-614][core]move error log location

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteDeleteFromArcticTable.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteUpdateArcticTable.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestKeyedTableDml.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestUnkeyedTableDml.java
fix #629 
when update or delete has no filter, will throw exception
> [ARCTIC-629][SPARK]Fix spark update has no filter will throw exception

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/DDLTracerService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/FileInfoCacheService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/TestDDLTracerService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/TestFileInfoCacheService.java
- core/src/test/java/com/netease/arctic/TableTestBase.java
fix #626 
1.file size and file count should add remove files
2.operation ddl should not contain \n at last
> [Bug]: Some bugs in local test for version 0.4.0 bug

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/AmsRestServer.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/SettingController.java
resolve https://github.com/NetEase/arctic/issues/630
> [ARCTIC-630][Improvement]: hidden username and password in setting page

- site/docs/ch/spark/spark-dml.md
Update the documentation of the Spark section.
'write.upsert.enable' -> 'write.upsert.enabled'.
Update the documentation of the Spark section.
> [hotfix] Update the configuration of 'write.upsert.enabled'

- site/docs/ch/meta-service/dashboard.md
Add a Kyuubi note to the Arctic Dashboard doc
> [hotfix]Add a kyuubi note to the Arctic Dashboard doc

- ams/ams-dashboard/src/views/catalogs/Detail.vue
Fix #648 
Fix save the field `storage_configs`
> [ARCTIC-648][AMS] Fix save the field `storage_configs`

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/FileInfoCacheService.java
Table identifier is not separated by delimiters
More readable
> [Hotfix] format table identifier log message in FileInfoCacheService

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java
> [AMS]Terminal requires a proxy user

- .idea/vcs.xml
resolve #668 
Add IssueNavigationLink for IDEA
Add vcs.xml
> [ARCTIC-668][Improvement]: Add IssueNavigationLink for IDEA

- flink/v1.12/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java
- flink/v1.14/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java
- flink/v1.15/flink-format/src/main/java/com/netease/arctic/flink/shuffle/LogRecordV1.java
fix #683 
When users insert data into the log-store of arctic table via Flink, some fields of the entire data have a null value, but when the data is read from the log-store these fields with a null value are given a default value, which should be fixed
- *Added logic for null value determination*
- *The flink 1.12, 1.14, 1.15 versions are affected.*
> [Flink][bugfix] fixed the problem that passing a null value to some fields would be given a default value

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSession.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSessionContext.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/kyuubi/KyuubiSession.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalTerminalSession.java
- dist/src/main/arctic-bin/conf/config.yaml
fix #661  
- add session active check before executing script.
- check the kyuubi session via select 1
> fix #661. check session available before execute script

- site/docs/ch/spark/spark-get-started.md
- spark/v2.3/spark-runtime/pom.xml
- spark/v3.1/spark-runtime/pom.xml
> [SPARK]Fix arctic spark version

- ams/ams-server/src/main/resources/sql/derby/ams-init.sql
- ams/ams-server/src/main/resources/sql/mysql/0.4.0-init.sql
- ams/ams-server/src/main/resources/sql/mysql/upgrade-0.3.2-to-0.4.0.sql
fix #659 
mysql:
-> mediumtext
derby:
-> clob(64m)
> [ARCTIC-659][Improvement]: Increase the length of filed platform_file_info.file_content_b64

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/CatalogController.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/OptimizeQueueMapper.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/CatalogUtil.java
fix #733 and fix add optimize queue cache error
1. remove catalog cache when edit catalog
2. getqueue id from system DB when load optimize queue config in the first time
> [Bug][AMS][ARCTIC-733]: Catalog cache is not updated after edit catalog information

- core/src/main/java/com/netease/arctic/table/TableMetaStore.java
Fix #737 
Capitalize the `authMethod` parameter.
> [ARCTIC-737][AMS] Capitalize the `authMethod` parameter.

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/AdaptHiveService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java
fix #748 
remove cache when drop table
> [ARCTIC-748][Bug][AMS]: remove and rebuild hive table can not upgrade

- ams/ams-api/src/main/java/com/netease/arctic/ams/api/client/ThriftClientPool.java
resolve #731 
- *set max message size in thrift client*
> [ARCTIC-731] Set max message size in thrift client

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java
fix #744 
- *Use partition info in data file info to delete the no partition change tables*
> [AECTIC-744][ams] Fix no expire for no partition keyed table

- hive/src/main/java/com/netease/arctic/hive/utils/CatalogUtil.java
- site/docs/ch/docker-quickstart.md
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkCatalog.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/SparkSQLProperties.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestKeyedTableDDL.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java
fix #686 
Use timestamp with zone in iceberg format to solve time zone problems
> [SPARK]Use timestamp with zone in iceberg format

- optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskExecutor.java
*Remove table cache in table optimizer*
- *Remove table cache in table optimizer.*
> [ARCTIC-728][Optimizer]Remove table cache in table optimizer

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSessionContext.java
*Fix #785.*
- *Drop semicolon when executing sql in Terminal on AMS Dashboard*
> [ARCTC-754][AMS]Drop semicolon when executing sql in Terminal on AMS Dashboard

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/FileInfoCacheService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/TestFileInfoCacheService.java
To fix #781 
show FileContent of iceberg table as `data` `pos-deletes` `eq-deletes`
> [ARCTIC-781] Modify the form of FileContent of native iceberg table

- ams/ams-api/src/main/java/com/netease/arctic/ams/api/properties/CatalogMetaProperties.java
- core/src/main/java/com/netease/arctic/catalog/BaseIcebergCatalog.java
Fix #712 
- *Add `include.databases` in `CatalogMetaProperties`.*
- *Add regular expressions to match database name in `com.netease.arctic.catalog.BaseIcebergCatalog#listDatabases`*
> [ARCTIC-712][AMS] Support for regular expressions to match database name for Hive Metastore

- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestKeyed.java
*Ignore testFileUpsertWithSamePrimaryKey unit test case for ci blocking error in Github*
- *Ignore testFileUpsertWithSamePrimaryKey unit test case*
- *Flink 1.12/1.14/1.15 are affected*
> [Flink]Ignore testFileUpsertWithSamePrimaryKey unit test case

- dist/src/main/arctic-bin/conf/log4j2.xml
- dist/src/main/arctic-bin/conf/optimize/log4j2.xml
Modify log file archiving rules
Modify log file archiving rules like https://github.com/NetEase/arctic/issues/678#issuecomment-1323276805
> [Improvement] Modify log file archiving rules

- site/docs/ch/flink/flink-get-started.md
Follow-up the issue #778.
We need to add some statements to the documentation page of the Flink section.
If you are using the mixed-format table, please check the documentation pages by this [link](https://arctic.netease.com/ch/flink/flink-get-started/);
if you are using original iceberg format table, please check the documentation page by this [link](https://iceberg.apache.org/docs/latest/flink-connector/);
- Update the flink-get-started.md
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)  docs
> [hotfix] Update the flink-get-started.md and add the mixed-format statement in the Arctic-Flink section

- site/docs/ch/spark/spark-get-started.md
Add a notice of spark docs that our document is for the mixed-format table. 
- Add  a notice of spark docs that our document is for the mixed-format table. 
> [Arctic-658][Docs]: Add notice of spark docs

- docker/README.md
*Fix package command on docker build script file.*
- *Change `mvn package -p` to `mvn package -pl`*
> [Docker]Fix package command on docker build script file.

- site/config/ch/mkdocs.yml
- site/docs/ch/mpp/impala.md
Add impala doc
Add site/docs/ch/mpp/impala.md
- Does this pull request introduces a new feature? (**yes** / no)
> [Docs]Add impala doc

- site/docs/ch/configurations.md
- site/docs/ch/flink/flink-cdc-to-arctic.md
It's the incorrect description. 
So remove it first and add a new improvement after this.
Flink documentation page:  flink-cdc-to-arctic.md
> [DOC][hotfix] Remove the reading shuffle description in Flink documentation page

- core/src/test/java/com/netease/arctic/io/IcebergFanoutPosDeleteWriterTest.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/ArcticSourceTest.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestMajorExecutor.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/executor/TestMinorExecutor.java
Fix #827 
Fix path separators in UTs.
> [ISSUE-827] Fix the failed UTs in win.

- site/docs/ch/benchmark/benchmark-step.md
Polish benchmark doc
Modify Arctic-Trino plugin url
Rename "前缀" to "后缀"
- Does this pull request introduces a new feature? (**yes** / no)
> [Docs]Polish benchmark doc

- site/docs/ch/quickstart/cdc-ingestion.md
- site/docs/ch/quickstart/quick-demo.md
polish docs for quick start.
- *Add the guidance to use to execute 'nc' command in flink container*
- *Polish some guidance*
- If yes, how is the feature documented? (docs )
> [Docs] polish quick-start document

- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/spark/spark-get-started.md
*update download URL for flink/spark runtime jar in site*
- *update download URL for flink/spark runtime jar in site*
> [Docs]update download url in site

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java
Fix OrphanFilesCleanService get metadata files with recursive=false
> [ARCTIC-877] Fix OrphanFilesCleanService get metadata files with recursive=false

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/IJDBCService.java
We found cpu usage is very high even no optimizing job in ams.
Avoid find class frequently in com.netease.arctic.ams.server.service.IJDBCService
> Avoid find class in jar frequently

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableQuotaInfo.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IOptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeCheckTask.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/QuotaService.java
fix #871  and fix #756 
- check tables in queue periodically (use optimize checker)
- continue loading other tables if failed to load any table
- add more logs for optimize plan
> [ARCTIC-871] [ARCTIC-756] Fix pending optimizing after change optimizer group and handle table load error

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/MetaService.java
*fix bug*
- *Fix NPE when resolving #870*
> [ARCTIC-870] Fix NPE when resolving #870

- ams/ams-api/pom.xml
- ams/ams-dashboard/pom.xml
- ams/ams-server/pom.xml
- ams/pom.xml
- core/pom.xml
- dist/pom.xml
- flink/pom.xml
- flink/v1.12/flink-format/pom.xml
- flink/v1.12/flink-runtime/pom.xml
- flink/v1.12/flink/pom.xml
- flink/v1.14/flink-format/pom.xml
- flink/v1.14/flink-runtime/pom.xml
- flink/v1.14/flink/pom.xml
- flink/v1.15/flink-format/pom.xml
- flink/v1.15/flink-runtime/pom.xml
- flink/v1.15/flink/pom.xml
- hive/pom.xml
- optimizer/pom.xml
- pom.xml
- spark/pom.xml
- spark/v2.3/spark-runtime/pom.xml
- spark/v2.3/spark/pom.xml
- spark/v3.1/spark-runtime/pom.xml
- spark/v3.1/spark/pom.xml
- trino/pom.xml
*To resolve #747, add some maven configuration*
- *Add a deploy-maven-central profile in maven pom configuration file*
- *Add some necessary maven configuration*
> [ARCTIC-747]Add maven central deploy profile

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/read/FlinkSplitPlanner.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/FlinkSplitPlanner.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/FlinkSplitPlanner.java
Fix #903 
The Closeable resources should be close correctly.
> [ARCTIC-903][Flink] Close CloseableIterator after plan files/plan tasks in flink module

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseIcebergOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergFullOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergMinorOptimizePlan.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/FileInfoCacheService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/SupportHiveSyncService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/OptimizeIntegrationTest.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileClean.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizeCommit.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergFullOptimizePlan.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizeCommit.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestIcebergMinorOptimizePlan.java
- core/src/main/java/com/netease/arctic/scan/BaseKeyedTableScan.java
- hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java
fix #896 
- close after planFiles()
> [ARCTIC-896] Close FileScanTask CloseableIterable in module ams/core/hive

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalManager.java
When two catalogs have the same authentication mode and authentication user, and you switch between using in terminal, it will throw an exception.
Change the sessionId composition
sessionId = cookie + authMod + authName + catalog
> [BUG]Fix terminal change catalog throw namespace not found

- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/spark/spark-get-started.md
Change download url in site for version 0.4.0
- Change download url in site for version 0.4.0
> [Docs]Change download url in site for version 0.4.0

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java
fix https://github.com/NetEase/arctic/issues/922
clean related optimize tasks when the error is throwed
> [ARCTIC-922] Catch found new position delete ValidationException

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
related pr: https://github.com/NetEase/arctic/pull/872
Avoid re-throwing exceptions periodically
> [ARCTIC-875] Avoid printing duplicate error logs

- site/docs/ch/flink/flink-cdc-to-arctic.md
- site/docs/ch/flink/flink-get-started.md
- site/docs/ch/flink/hidden-kafka.md
fix doc
Fix flink cdc quick start config and add a description about log store changelog config 
> [Hotfix][doc] Fix flink cdc quick start config and add a description about log store changelog config 

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/ArcticExtensionUtils.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/ExtendedArcticStrategy.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteAppendArcticTable.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteDeleteFromArcticTable.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/optimize/RewriteUpdateArcticTable.scala
Remove useless code and optimized the physical plan in Spark:
> [SPARK]Remove useless code and optimized code in Spark

- core/src/main/java/com/netease/arctic/io/writer/BaseTaskWriter.java
- core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java
fix #981 
- *use table io to close in SortedPosDeleteWriter and BaseTaskWriter*
> [ARCTIC-981] Fix the Kerberos problem in the SortedPosDeleteWriter for the minor optimizing

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/plans/TruncateArcticTable.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/ExtendedArcticStrategy.scala
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/execution/TruncateArcticTableExec.scala
- spark/v3.1/spark/src/main/scala/org/apache/spark/sql/catalyst/expressions/ArcticExpressionUtils.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/SparkTestContext.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/TestTruncate.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestDropPartitions.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestTruncate.java
resolve #540 
Support truncate table in spark
> [ARCTIC-540][SPARK]Support truncate table

- core/src/main/java/com/netease/arctic/utils/StructLikeSet.java
- core/src/main/java/com/netease/arctic/utils/map/RocksDBBackend.java
- core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java
- core/src/main/java/com/netease/arctic/utils/map/StructLikeCollections.java
- core/src/main/java/com/netease/arctic/utils/map/StructLikeSpillableMap.java
- core/src/test/java/com/netease/arctic/utils/map/TestSimpleSpillableMap.java
- core/src/test/java/com/netease/arctic/utils/map/TestSimpleSpilledMap.java
- core/src/test/java/com/netease/arctic/utils/map/TestStructLikeMap.java
- dist/src/main/arctic-bin/bin/localOptimize.sh
- dist/src/main/arctic-bin/conf/config.yaml
- optimizer/src/main/java/com/netease/arctic/optimizer/OptimizerConfig.java
- optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/local/LocalOptimizer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/BaseExecutor.java
improve #925 
- *The optimize group adds spill map config to start optimizer*
- *The spill map supports the custom directory*
> [ARCTIC-925][Optimizer] The optimize group adds config to support spill map and improve spill map with the custom directory

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/FileInfoCacheService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/TestFileInfoCacheService.java
- core/src/main/java/com/netease/arctic/table/BaseUnkeyedTable.java
- core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java
- core/src/main/java/com/netease/arctic/trace/ArcticAppendFiles.java
- core/src/main/java/com/netease/arctic/trace/ArcticOverwriteFiles.java
- core/src/main/java/com/netease/arctic/trace/ArcticReplacePartitions.java
- core/src/main/java/com/netease/arctic/trace/ArcticRowDelta.java
- core/src/test/java/com/netease/arctic/trace/TableTracerTest.java
resolve #1013 
AMS tracer report snapshot information even if no new file is submitted
> [Improvement][Core]: ams tracer should report snapshot information even if no new file is submitted

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java
- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/kafka/testutils/KafkaTestBase.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/DynamicTableFactory.java
- hive/src/test/java/com/netease/arctic/hive/ArcticHiveTestMain.java
- site/docs/ch/flink/flink-ddl.md
Add the introduction about the correspondence between arctic table data types and flink data types.
Optimize some codes.
Fixed: #1019 
- *Introduce arctic supported data types in the flink/flink-ddl.md*
- *Import the static method*
- *Add the log about the cost of Kafka and HMS startup*
> [ARCTIC-1019] Introduce the correspondence between the arctic table and flink data types

- core/src/main/java/com/netease/arctic/io/reader/ArcticDeleteFilter.java
- core/src/main/java/com/netease/arctic/io/reader/BaseArcticDataReader.java
- core/src/main/java/com/netease/arctic/io/reader/DataReaderCommon.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveArcticDeleteFilter.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveBaseArcticDataReader.java
- hive/src/main/java/com/netease/arctic/hive/io/reader/AdaptHiveGenericArcticDataReader.java
- hive/src/test/java/com/netease/arctic/hive/ArcticHiveTestMain.java
- hive/src/test/java/com/netease/arctic/hive/HiveTableTestBase.java
- hive/src/test/java/com/netease/arctic/hive/io/HiveTestRecords.java
- hive/src/test/java/com/netease/arctic/hive/io/KeyedTimeStampTest.java
- hive/src/test/java/com/netease/arctic/hive/io/TestIOUtils.java
- trino/src/main/java/com/netease/arctic/trino/keyed/KeyedConnectorPageSource.java
- trino/src/main/java/com/netease/arctic/trino/keyed/KeyedDeleteFilter.java
- trino/src/main/java/com/netease/arctic/trino/keyed/KeyedPageSourceProvider.java
Fix #1012.
- *Add adapt Hive Arctic delete filter to open delete files in Arctic Hive compatible table.*
- *Do some adaption for the adapt hive Arctic reader.*
- *Add some test methods and JUnit tests.*
- *Change Trino's filter to adapt Hive.*
> [ARCTIC-1012] Fix Timestamp field type as a key will cause ClassCastException in Arctic Hive compatible table

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeTaskItem.java
misuse of `com.netease.arctic.utils.SerializationUtils#toInternalTableFile`
- change to `com.netease.arctic.utils.SerializationUtils#toContentFile` for target files
> [ARCTIC-994] fix serialization for target files of hive support table

- .github/workflows/ams-ci.yml
- .github/workflows/core-ci.yml
- .github/workflows/flink-ci.yml
- .github/workflows/spark-ci.yml
- .github/workflows/trino-ci.yml
*Github ci configuration files are out of date on branch 0.3.x due to lack of ci for branch 0.3.x*
- watch 0.** branch for all GitHub workflow
> [Github]Trigger github ci for branch 0.3.x

- dist/src/main/arctic-bin/conf/log4j2.xml
- dist/src/main/arctic-bin/conf/optimize/log4j2.xml
fix #1083 
- add `<Configuration monitorInterval="10">` to log4j2.xml
> [ARCTIC-1083] support modifying log4j2.xml dynamically

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/InternalCatalogBuilder.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/InternalCatalogBuilder.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/InternalCatalogBuilder.java
Using import statements replace the fully qualified package name of the class ArcticCatalog.
- *replace the fully qualified package name of the class ArcticCatalog*
- *The flink 1.12, 1.14, and 1.15 versions are affected.*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
> [hotfix] Using import statements replace the fully qualified package name of a class

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalManager.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/TerminalSessionFactory.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/terminal/local/LocalSessionFactory.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/reader/UnkeyedSparkBatchScan.java
fix #1090 
- Add new option in SessionConfigOptions: IS_NATIVE_ICEBERG
> [ARCTIC-1090][AMS]Terminal support add hadoop conf into sparkConf

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
When changing the optimizing group, it may plan concurrently in different groups.
- refresh and check optimizing group is correct before optimize
> [Hotfix] 0.3.x fix concurrent plan in different optimizing group

- site/docs/ch/guides/deployment.md
- site/docs/ch/spark/spark-conf.md
There are somethings wrong in docs `ch/spark/spark-conf.md`, so this PR will fix it.
- Fix configure error of the spark catalog
- Add ha config.
> [Docs]: Fix config problem in spark-conf page

- ams/ams-server/src/main/resources/sql/mysql/upgrade-0.4.0-to-0.4.1.sql
The column `properties` of `table_blocker` is lost in upgrade sql.
- add column `properties` into `upgrade-0.4.0-to-0.4.1.sql`
> [ARCTIC-985] fix upgrade sql for `table_blocker`

- core/src/main/java/com/netease/arctic/data/file/FileNameGenerator.java
fix #1114 
- add more logs for reproduce
> [ARCTIC-1114] Address Arctic file name parse error 

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #800 
- *Clean useless files when optimize commit fails*
> [ARCTIC-800] Clean useless files when optimize commit fails (#801)

- core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java
fix #981 
- *use table io to close in SortedPosDeleteWriter*
> [ARCTIC-981] Fix the Kerberos problem in the SortedPosDeleteWriter for the minor optimizing #982

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/TaskHistoryMapper.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BasicOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeCheckTask.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java
fix #1103 
- *Clear the optimizing tasks when the optimizing commit failed*
- *Clear the optimizing tasks when the table has failed tasks after max retry*
> [ARCTIC-1103][AMS] Clear the optimizing tasks when the optimizing commit failed

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/SettingController.java
…in the configuration file can be read
resolve #1162 
Modified the obtaining configuration mode. All system configurations in the configuration file can be read
> [Improvement]: Added the ams configuration items that can be configured in the configuration file

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/ContentFileUtil.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/HiveLocationUtils.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtil.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileClean.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestExpiredFileCleanSupportHive.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestOrphanFileClean.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/utils/UnKeyedTableUtilTest.java
- core/src/main/java/com/netease/arctic/utils/ManifestEntryFields.java
fix #1105 
- *The snapshot expire check valid DataFiles according to scan from metadata files*
- *The orphan file clean check valid DataFiles according to scan from metadata files*
> [ARCTIC-1105][AMS] Fix snapshot expire and orphan clean misdelete the DataFiles for 0.3.x

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/mapper/TaskHistoryMapper.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableOptimizeRuntime.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeCheckTask.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TableOptimizeItemTest.java
fix #1103 
- *Clear the optimizing tasks when the optimizing commit failed*
- *Clear the optimizing tasks when the table has failed tasks after max retry*
> [ARCTIC-1103][AMS] Clear the optimizing tasks when the optimizing commit failed for 0.3.x

- optimizer/src/main/java/com/netease/arctic/optimizer/local/LocalOptimizer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskExecutor.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskReporter.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/executor/AbstractExecutor.java
- optimizer/src/test/java/com/netease/arctic/optimizer/operator/BaseTaskExecutorTest.java
fix #1189 
- Optimizer reports a failed result to AMS when failed to load the table
- Add some unit tests for `BaseTaskExecutor`
> [ARCTIC-1189][Optimizer] Optimizer reports a failed result to AMS when failed to load table

- optimizer/src/main/java/com/netease/arctic/optimizer/operator/OperatorFactory.java
- optimizer/src/test/java/com/netease/arctic/optimizer/flink/FlinkOptimizerFactoryTest.java
- optimizer/src/test/java/com/netease/arctic/optimizer/local/LocalOptimizerFactoryTest.java
fix #1188, fix serialization of `LocalOptimizer`
-  make OperatorFactory extends Serializable
-  add unit test for Optimizer's serialization for module optimizer
> [ARCTIC-1188][Optimizer] fix serialization of LocalOptimizer

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
- optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkConsumer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/local/LocalOptimizer.java
fix #1197 
- the polling task request should return immediately
- `Optimizer` should wait for a while between each polling task request
> [ARCTIC-1197][Optimizer] Optimizer should wait for a while between each polling task request

- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/ArcticSparkSessionCatalog.java
- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/hive/TestCreateTableDDL.java
Merging the two pull request causing problems with unit tests and compilation errors
https://github.com/NetEase/arctic/pull/1211
https://github.com/NetEase/arctic/pull/1198
change some tests in spark.
> [SPARK]Fixed problems caused by merging branches

- site/docs/ch/quickstart/quick-demo.md
According to the quick demo guide processes, users may copy the namenode address from the guide when they are creating catalogs, but it is not an actual runnable address from the user side, we should suggest users change it.
- *update the quick-demo.md*
> [hotfix] Add a suggestion to users change the actual namenode address in the quick demo guide

- site/docs/ch/spark/spark-ddl.md
Docs of spark DDL has some problems, transform name is wrong.
- fix transform name in spark ddl docs
> [Docs]: Fix transform name in spark ddl docs

- .github/workflows/core-ci.yml
- .github/workflows/labeler.yml
- .github/workflows/trino-ci.yml
Removed `labeler.yml` by mistake in #1195, we need add it back. 
- *Add back labeler.yml*
- *Fix paths in core-ci.yml and trino-ci.yml*
> [Github]Add back labeler.yml

- core/src/test/java/com/netease/arctic/listener/ArcticRunListener.java
fix: #1254 
- *Log execution time of each UT, sorted from the large to small*
> [ARCTIC-1254] Determine the execution time of JUnit Tests in the flink modules

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BasicOptimizeCommit.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/OptimizingIntegrationTest.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/AbstractOptimizingTest.java
- ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/MixedIcebergOptimizingTest.java
fix #1319 
- Major Self-Optimizing should not delete pos-delete files
> [ARCTIC-1319] [ams] Major Self-Optimizing should not delete pos-delete files

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java
fix #1319  for 0.3.x
- Major Self-Optimizing should not delete pos-delete files
> [ARCTIC-1319] [ams] fix 0.3.x Major Self-Optimizing should not delete pos-delete files

- pom.xml
fix #1327
- *remove jacoco-maven-plugin's include scope*
> [ARCTIC-1327]Codecov Report shows coverage is 0.00%

- site/docs/ch/spark/spark-ddl.md
resolve #1340
Optimize the description of Spark CreateTableLike
Modify spark-ddl.md
Add a description: `create table like` supports only binary groups
> [ARCTIC-1340][Spark][Doc]Optimize the description of Spark CreateTableLike

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/CatalogController.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/controller/PlatformFileInfoController.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/PlatformFileInfoService.java
fix: https://github.com/NetEase/arctic/issues/1120
> [Arctic-1120]we return bytes array when we response file load request

- hive/src/main/java/com/netease/arctic/hive/catalog/ArcticHiveCatalog.java
fix #1318. Do privilege check through  checking where the base directory exists  before loading table 
- add privilege checking call before loading table
- Does this pull request introduces a new feature? (yes/ **no**)
> [Arctic-1318][Improvement]: we should throw a exception when we have no privilege to access the files of table

- ams/server/src/main/java/com/netease/arctic/server/optimizing/IcebergCommit.java
Deleting the old DeleteFile operation often causes the commit to fail, but this does not affect the accuracy of the data, so we want to perform this operation alone to avoid Optimizing always failing
Commit the DeleteFile delete operation separately in IcebergCommit
> Commit the DeleteFile delete operation separately in Iceberg Format

- ams/server/src/main/java/com/netease/arctic/server/terminal/SparkContextUtil.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/TerminalSession.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/TerminalSessionFactory.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/kyuubi/KyuubiSession.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalSessionFactory.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalTerminalSession.java
cherry pick #1264  to refactor-ams
> [AMS-Refactor]Use ArcticSparkSessionCatalog for terminal

- flink/v1.12/flink/src/main/java/com/netease/arctic/flink/interceptor/FlinkTablePropertiesInvocationHandler.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticDoubleWriteStatus.java
- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/interceptor/FlinkTablePropertiesInvocationHandler.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/catalog/CatalogTest.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticDoubleWriteStatus.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/interceptor/FlinkTablePropertiesInvocationHandler.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/catalog/TestCatalog.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticDoubleWriteStatus.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/write/TestAutomaticLogWriter.java
fixed: #414 
Arctic Table Properties has been updated, but the arctic table properties in the FlinkTablePropertiesInvocationHandler didn't be refreshed.
Reproduced by the follow ut:
```java
{
ArcticTableLoader tableLoader = ArcticTableLoader.of(PK_TABLE_ID, catalogBuilder);
tableLoader.open();
ArcticTable arcticTable = tableLoader.loadArcticTable();
boolean catchUp = true;
String catchUpTs = "1";
UpdateProperties updateProperties = arcticTable.updateProperties();
updateProperties.set(LOG_STORE_CATCH_UP.key(), String.valueOf(catchUp));
updateProperties.set(LOG_STORE_CATCH_UP_TIMESTAMP.key(), catchUpTs);
updateProperties.commit();
arcticTable.refresh();
Map<String, String> properties = arcticTable.properties();
Assert.assertEquals(String.valueOf(catchUp), …
```
> [Arctic-414][Improvement]: Refresh the arctic properties in the FlinkTablePropertiesInvocationHandler after table refreshed

- core/src/main/java/com/netease/arctic/op/ArcticTableOperations.java
Fix `temp` method use `ArcticTableOperations` for Kerberos auth (#984)
cherry-pick #984 to 0.4.x 
changing where authentication fails in my local and similar. 
Surround the code by arcticTable.io().doAs()
> [ARCTIC-965][AMS] Fix `temp` method use `ArcticTableOperations` for Kerberos auth (pick 984)

- spark/v3.1/spark/src/main/scala/com/netease/arctic/spark/sql/catalyst/analysis/RewriteArcticCommand.scala
pick #1429 from master to 0.4.x which fix #1403  
- add write options for both keyed table and unkeyed table.
- add some test case
> [Arctic-1403][Pick-1429]: Spark CTAS write to hive location for unkeyed table

- hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
Pick #1463 from master to 0.4.x to fix #1350 in older branch.
Use Set instead of List when checking orpthan files.
Run test locally before making a pull request
> [Arctic-1350][Pick-1463][Hive]: Improvement the performance of orphanfile check when hive table commit

- ams/server/src/main/java/com/netease/arctic/server/catalog/IcebergCatalogImpl.java
- ams/server/src/main/java/com/netease/arctic/server/catalog/MixedCatalogImpl.java
- ams/server/src/main/java/com/netease/arctic/server/catalog/MixedHiveCatalogImpl.java
- ams/server/src/main/java/com/netease/arctic/server/catalog/ServerCatalog.java
- core/src/main/java/com/netease/arctic/catalog/IcebergCatalogWrapper.java
- hive/src/main/java/com/netease/arctic/hive/catalog/MixedHiveTables.java
after update catalog properties, the `CatalogMeta` in the child class of `ServerCatalog` is not changed.
- call onMetadataUpdate() after update catalog metadata of `ServerCatalog`
> [AMS-Refactor] fix update catalog properties

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/mapper/OptimizingMapper.java
persistence optimizing process failedReason
persistence optimizing process failedReason
> [AMS-Refactor] persistence optimizing process failedReason

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/mapper/OptimizingMapper.java
- ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java
- ams/server/src/main/resources/derby/ams-derby-init.sql
- ams/server/src/test/java/com/netease/arctic/server/optimizing/BaseOptimizingChecker.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/TestIcebergHadoopOptimizing.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/TestMixedIcebergOptimizing.java
fix optimizing integration test
fix optimizing integration test
> [AMS-Refactor] fix optimizing integration test

- site/docs/ch/concepts/self-optimizing.md
> [ARCTIC-1506] Correct the word spelling mistake

- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java
- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceFetcherManager.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/read/internals/KafkaSourceFetcherManager.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/read/hidden/kafka/TestKafkaSourceReader.java
*fix compile error*
- *change import path*
> fix compile error

- ams/ams-server/pom.xml
- optimizer/pom.xml
- pom.xml
Upgrade POM dependencies to resolve security issues.
upgrade `fastjson`,`mybitas` version, exclude `org.apache.velocity` 
> [AMS] Upgrade POM dependencies to resolve security issues.

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java
This is to merge this PR: https://github.com/NetEase/arctic/pull/1501  into version 0.4. x
- *Add the 'scan.startup.mode' configuration to the ArcticScanContext in the flink modules*
- *The flink 1.12 and 1.14 versions are affected.*
> [ARCTIC-1500][Bug]: failed to delete orphaned files

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/model/TableOptimizeRuntime.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java
fix #1514 
- optimizing should retry with exponentially increasing interval
> [ARCTIC-1514] Optimizing should retry with exponentially increasing interval

- optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkConsumer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskConsumer.java
- optimizer/src/main/java/com/netease/arctic/optimizer/operator/BaseTaskExecutor.java
- optimizer/src/main/java/com/netease/arctic/optimizer/util/ExceptionUtil.java
fix #1489 
- The Optimizer reports the complete exception stack to AMS
> [ARCTIC-1489] The Optimizer reports the complete exception stack to AMS

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingProcess.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
- ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
Fix quota calculation logic
Fix quota calculation logic
> [Refactor-AMS] Fix quota calculation logic

- ams/server/src/main/resources/mysql/upgrade-0.4.1-to-0.5.0.sql
> [ARCTIC-1524][AMS] Add `optimizer_token`,`thread_id` field in table `task_runtime`

- ams/server/src/main/java/com/netease/arctic/server/catalog/CatalogBuilder.java
- core/pom.xml
- pom.xml
> [ARCTIC-1478][AMS] Adapting IcebergCatalogImpl: GlueCatalog

- ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java
> [ARCTIC-1526][AMS] Use `MetricsSummary` from `TableOptimizingProcess` instead `getAs`

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
fix #1363 
- AMS should not throw exception to optimizer when handing reported result
> [ARCTIC-1363][hive] Fix Optimizer retry report result costing too much time when task is deleted

- core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java
resolve #1453 
When reporting properties, tracer needs to merge catalog properties.
> [Bug]: Unexpected data in Operations section of table details

- core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java
resolve https://github.com/NetEase/arctic/issues/1453
When reporting properties, tracer needs to merge catalog properties.
> [ARCTIC-1453]: Unexpected data in Operations section of table details

- ams/server/src/main/java/com/netease/arctic/server/optimizing/SchedulingPolicy.java
- ams/server/src/main/java/com/netease/arctic/server/resource/ContainerMetadata.java
> [ARCTIC-1542] Fix NPE when load optimizer config with null propoerty

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/ArcticMetaStore.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/exception/ArcticRuntimeException.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/ServiceContainer.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/utils/ThriftServiceProxy.java
resolve #1469
Add the server exception message to the exception returned by the Thrift interface.
Error message like:
> [ARCTIC-1496] Additional exception handling should be added to the getTable method in Thrift

- core/src/main/java/com/netease/arctic/catalog/BasicArcticCatalog.java
- core/src/test/java/com/netease/arctic/catalog/TestMixedCatalog.java
resolve #1551 
- *Merge catalog properties before validation*
> [ARCTIC-1551]: Global Catalog configuration not valid for table build check

- site/docs/ch/guides/deployment.md
- site/docs/ch/guides/managing-tables.md
Some configuration descriptions in the doc are incorrect
Fix doc
> [Doc] Fix errors in doc

- ams/server/src/main/java/com/netease/arctic/server/table/executor/SnapshotsExpiringExecutor.java
… deleting empty snapshot dir
fix #1563 
will not throw pre-check exception
> [ARCTIC-1563] Check if file-io supports file system operations before deleting empty snapshot dir

- pom.xml
fix #1575  by upgrading  maven-scala-plugin-version to 4.8.1
> [ARCTIC-1575]: Update maven-scala-plugin version to 4.8.1

- flink/v1.12/flink/src/test/java/com/netease/arctic/flink/read/hybrid/enumerator/TestArcticSourceEnumerator.java
*fix compile error*
- *Changed Class constructors and table references*
- *The flink 1.12 version is affected.*
> [0.4.x] Fix compile error

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingType.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingPlanner.java
- ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/TestMixedHiveOptimizing.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/TestMixedIcebergOptimizing.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/flow/checker/FullOptimizingMove2HiveChecker.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/flow/checker/FullOptimizingWrite2HiveChecker.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/plan/TestOptimizingPlanner.java
Improve the https://github.com/NetEase/arctic/issues/1617
rename the Optimize Type FULL_MAJOR to FULL to make it match with official site describe.
> [ARCTIC-1617][Improvement]: Change the Optimize Type FULL_MAJOR to FULL

- ams/server/src/main/java/com/netease/arctic/server/optimizing/KeyedTableCommit.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java
fix #1620
- set delete-untracked-hive-file=true when Mixed Hive Table Optimizing commit
> [ARCTIC-1620] Check there are no orphan files in the directory when Mixed Hive Full Optimizing committing

- ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java
fix #1535, when there is no optimizing process.
- `SELECT IN(...)` cannot be empty
> [ARCTIC-1535] Fix displaying empty optimizing process

- ams/server/src/main/resources/mysql/upgrade-0.4.1-to-0.5.0.sql
fix the sql bugs introduced by  PR #1608 
- fix the sql problems in upgrade-0.4.1-to-0.5.0.sql
> [ARCTIC-1339][AMS]: Fix sql problems in upgrade-0.4.1-to-0.5.0.sql

- ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/model/PartitionFileBaseInfo.java
resolve #1648 
Use the String data type to represent snapshotId in the HTTP interface.
- Does this pull request introduces a new feature? (yes /no)
> [ARCTIC-1648] Commit IDs in Files page are not accurate

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergFullOptimizePlan.java
fix https://github.com/NetEase/arctic/issues/1571
Enable 'self-optimizing.full.trigger.interval' to support native iceberg tables in arctic 0.4.x.
> [ARCTIC-1571][Improvement][AMS]Iceberg Format Table's full optimizing should be triggered by interval

- core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java
- core/src/test/java/com/netease/arctic/utils/ArcticDataFilesTest.java
fix in 0.4.x, #1600, #1653 
- support null for partition values
- support special characters in partition values
> [ARCTIC-1600][ARCTIC-1653] cherry-pick to 0.4.x fix null and special charactors for partition value

- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
Support creating a catalog with an empty configuration file.
Set default value `<configuration></configuration>` for catalog when the store config file for creating a new catalog is empty.
> [ARCTIC-1666] Support creating a catalog with an empty configuration file.

- hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
fix #1662 
The alter operation on the hive will also go through an orphan file cleanup check
> [ARCTIC-1662] The attemp file clean missed the overwrited partition

- ams/server/pom.xml
close https://github.com/NetEase/arctic/issues/1399#issue-1682675511
update spark version to 3.3 in pom.xml
> [ARCTIC-1399][Improvement]: Use spark3.3 as default backend for terminal sql

- ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
fix #1686 
- update currentStatusStartTime after change to pending
> [ARCTIC-1686] Update status start time after optimizing status changed to pending

- ams/optimizer/pom.xml
- ams/server/src/main/java/com/netease/arctic/server/persistence/TaskFilesPersistence.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/converter/Object2ByteArrayConvert.java
- ams/server/src/main/java/com/netease/arctic/server/utils/CompressUtil.java
- ams/server/src/main/resources/derby/ams-derby-init.sql
fix #1687 
enhance #1650 and #1624 
1. resolve kryo dependency conflict
2. catch exception when unzip rewrite input tasks from db
3. increase the storage length of rewrit_input in derby
> [ARCTIC-1687] Exclude kryo dependency which in ams-core from ams-optimizer module

- ams/optimizer/pom.xml
- ams/server/src/main/java/com/netease/arctic/server/persistence/TaskFilesPersistence.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/converter/Object2ByteArrayConvert.java
- ams/server/src/main/resources/derby/ams-derby-init.sql
> Revert "[ARCTIC-1687] Exclude kryo dependency which in ams-core from ams-optimizer module"

- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/OptimizingPlanner.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/StatedPersistentBase.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/JDBCResultSet.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/StatementResult.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/TerminalSessionContext.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/kyuubi/KyuubiTerminalSessionFactory.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalTerminalSession.java
- ams/server/src/test/java/com/netease/arctic/server/table/TestTableRuntimeHandler.java
- spark/v3.1/spark/src/main/java/com/netease/arctic/spark/util/DistributionAndOrderingUtil.java
- spark/v3.1/spark/src/test/java/com/netease/arctic/spark/test/helper/TestTable.java
- spark/v3.2/spark/src/main/java/com/netease/arctic/spark/util/DistributionAndOrderingUtil.java
- spark/v3.2/spark/src/test/java/com/netease/arctic/spark/test/helper/TestTable.java
- spark/v3.3/spark/src/main/java/com/netease/arctic/spark/util/DistributionAndOrderingUtil.java
- spark/v3.3/spark/src/test/java/com/netease/arctic/spark/test/helper/TestTable.java
For Lists, stream is an unnecessary dependency, iceberg-bundled-guava is a better choice, it may be a future burden, we should minimize unnecessary dependencies as much as possible。
com.clearspring.analytics.util.Lists -> org.apache.iceberg.relocated.com.google.common.collect.Lists
> Replace com.clearspring.analytics.util.Lists with org.apache.iceberg.relocated.com.google.common.collect.Lists

- ams/api/src/main/java/com/netease/arctic/ams/api/client/OptimizingClientPools.java
Fix #1707.
- *Make thrift client pool max size unlimited.*
> [ARCTIC-1707] Make Thrift client pool max size to unlimited

- ams/api/pom.xml
- ams/api/src/main/java/com/netease/arctic/ams/api/resource/ResourceGroup.java
issue: https://github.com/NetEase/arctic/issues/1611
For flinkcontainer optimizer, When making a connection via ams in high availability mode, NoSuchMethodError is encountered 
in ams/optimizer module, shade com.netease.arctic.shaded.org.apache.zookeeper and com.netease.arctic.shaded.org.apache.curator, to avoid NoSuchMethodError for flink optimizer
no
no
> [optimizer]For flinkcontainer optimizer, When making a connection via ams in high availability mode, NoSuchMethodError is encountered

- ams/server/src/main/java/com/netease/arctic/server/optimizing/scan/IcebergTableFileScanHelper.java
fix #1730 
Add a ceche when building IcebergDeleteFile in IcebergTableFileScanHelper.scan to prevent too many generated IcebergDeleteFiles
> [ARCTIC-1730] Add a ceche when building IcebergDeleteFile in IcebergTableFileScanHelper.scan to prevent too many generated IcebergDeleteFiles

- ams/server/src/main/resources/log4j2.xml
Fix typo caused can't recognize appender
Fix log4j2.xml typo
> [Bug] Fix log4j2.xml appender typo

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeExecuteService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/SupportHiveSyncService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TableExpireService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/TrashCleanService.java
resolve #1737 
- add try-catch for scheduleWithFixedDelay
> [ARCTIC-1737] Fix the tasks of `ScheduledExecutorService` that halts when an exception or error is thrown

- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/IcebergPartitionPlan.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/MixedIcebergPartitionPlan.java
fix #1729 
IcebergPartitionPlan should implement buildTaskSplitter
1. move MixedHivePartitionPlan Bin-Packing to AbstractPartitionPlan
2. IcebergPartitionPlan use Bin-Packing 
*before*:
*now*
> [ARCTIC-1729] IcebergPartitionPlan impl buildTaskSplitter by Bin-Packing

- .gitignore
- CONTRIBUTING.md
resolve #1750 
- add `CONTRIBUTING.md` to guild contributing
> [ARCTIC-1750] add `CONTRIBUTING.md` to guild contributing

- ams/server/src/main/resources/derby/ams-derby-init.sql
- ams/server/src/main/resources/mysql/ams-mysql-init.sql
fix #1787 
- remove insert statement from ams-mysql-init.sql
- remove insert statement from ams-derby-init.sql
> [ARCTIC-1787] [Improvement]: remove insert sql of local_catalog from ams-init.sql

- flink/v1.12/flink-runtime/pom.xml
- flink/v1.14/flink-runtime/pom.xml
- flink/v1.15/flink-runtime/pom.xml
fix #1797 
- *change pom.xml content*
> [ARCTIC-1797][FLINK] Arctic Flink Runtime Jar doesn't include source code.

- hive/src/main/java/com/netease/arctic/hive/utils/UpgradeHiveTableUtil.java
- hive/src/test/java/com/netease/arctic/hive/utils/TestUpgradeHiveTableUtil.java
fix #1815 
Replaced the incorrect code
> [AMORO-1815] Failure to upgrade a partitioned hive table

- ams/server/src/main/java/com/netease/arctic/server/table/executor/OrphanFilesCleaningExecutor.java
- ams/server/src/main/java/com/netease/arctic/server/utils/IcebergTableUtil.java
- ams/server/src/test/java/com/netease/arctic/server/table/executor/TestOrphanFileCleanIceberg.java
- core/src/main/java/com/netease/arctic/table/TableProperties.java
- dist/src/main/arctic-bin/conf/config.yaml
- docs/user-guides/configurations.md
resolve #1628 
- rename `Independent` delete files to `Dangling` delete files
- rename `arctic` to `amoro` for derby location
> [ARCTIC-1628] Rename `Independent` delete files to `Dangling` delete files

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
resolve #1826 
- remove tasks from executing tasks of optimizing queue when tasks are canceled
> [AMORO-1826] Remove tasks from executing tasks when tasks are canceled

- ams/server/src/main/java/com/netease/arctic/server/table/RuntimeHandlerChain.java
- ams/server/src/main/java/com/netease/arctic/server/table/executor/BaseTableExecutor.java
resolve #1830
- fix the `dispose` of RuntimeHandlerChain
- add some logs for disposing thread pools
> [AMORO-1830] Fix AMS release thread pools after HA

- ams/server/src/main/java/com/netease/arctic/server/optimizing/SchedulingPolicy.java
fix #1822.
- Skip when sorter is not changed in scheduling policy
> [AMORO-1822]Fix editting group error

- ams/server/src/main/java/com/netease/arctic/server/optimizing/SchedulingPolicy.java
> [AMORO-1822]fix checktyle erros

- ams/optimizer/src/main/java/com/netease/arctic/optimizer/FlinkOptimizerContainer.java
- ams/optimizer/src/main/java/com/netease/arctic/optimizer/LocalOptimizerContainer.java
- ams/optimizer/src/main/java/com/netease/arctic/optimizer/OptimizerConfig.java
- ams/optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizer.java
- ams/optimizer/src/main/java/com/netease/arctic/optimizer/local/LocalOptimizer.java
- ams/optimizer/src/test/java/com/netease/arctic/optimizer/OptimizerTestHelpers.java
- ams/optimizer/src/test/java/com/netease/arctic/optimizer/TestOptimizerConfig.java
- ams/server/src/test/java/com/netease/arctic/server/AmsEnvironment.java
- dist/src/main/arctic-bin/bin/localOptimize.sh
- docs/admin-guides/managing-optimizers.md
fix #1845 
- *Add calculate optimizer resource allocation on optimizer side*
> [AMORO-1845][Optimizer] Add calculate optimizer resource allocation on optimizer side

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IOptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/JDBCMetaService.java
fix #1682 
Before removing runtime and history, configure it flexibly according to your needs.
> [ARCTIC-1682] When Load Catalog or Get database fails, the optimize history of all tables under the catalog and database disappears

- ams/server/src/main/java/com/netease/arctic/server/persistence/SqlSessionFactoryProvider.java
Close #1899 
- add init mysql schema srcipt 
> [AMORO-1899] add init schema in mysql

- core/src/main/java/com/netease/arctic/op/ArcticHadoopTableOperations.java
- core/src/main/java/com/netease/arctic/utils/ArcticInMemoryLockManager.java
- core/src/main/java/com/netease/arctic/utils/IcebergInMemoryLockManager.java
Close #1882 .
- using `ArcticInMemoryLockManager` to fix the NPE of `InMemoryLockManager`
> [AMORO-1882] fix NullPointerException when calling InMemoryLockManager#release of Iceberg

- ams/server/src/main/java/com/netease/arctic/server/persistence/SqlSessionFactoryProvider.java
- docs/admin-guides/deployment.md
Optimize deployment document and improve code quality
-
> [AMORO-1899] improve init schema in mysql

- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/flow/TestKeyedContinuousOptimizing.java
- ams/server/src/test/java/com/netease/arctic/server/optimizing/flow/TestUnKeyedContinuousOptimizing.java
Close #1953.
- Improve segment file rewrite trigger conditions.
> [AMORO-1953][AMS] Improve the triggering conditions for segment file rewriting

- spark/v3.1/spark-runtime/pom.xml
- spark/v3.2/spark-runtime/pom.xml
- spark/v3.3/spark-runtime/pom.xml
Close #1963.
- exclude org.apache.thrift.TException during shade amoro spark.
> [AMORO-1963][Spark]: Do not relocate the `org.apache.thrift.TException`

- ams/server/pom.xml
- ams/server/src/main/java/com/netease/arctic/server/ArcticManagementConf.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/SqlSessionFactoryProvider.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/converter/Object2ByteArrayConvert.java
- ams/server/src/main/resources/postgres/ams-postgres-init.sql
- dist/src/main/arctic-bin/conf/config.yaml
- dist/src/main/assemblies/bin.xml
- docs/admin-guides/deployment.md
> [AMORO-1966] Add PostgreSQL as system database

- ams/server/src/main/java/com/netease/arctic/server/table/executor/OrphanFilesCleaningExecutor.java
> [AMORO-1981]  orphan files could not be deleted

- docs/engines/spark/spark-conf.md
- docs/engines/spark/spark-get-started.md
Close #1908.
- Change all 'AmoroSpark*' properties with 'ArcticSpark*'.
- If yes, how is the feature documented? ( docs )
> [AMORO-1908] Fix Spark doc error

- ams/server/src/main/java/com/netease/arctic/server/table/executor/OrphanFilesCleaningExecutor.java
- ams/server/src/test/java/com/netease/arctic/server/table/executor/TestOrphanFileClean.java
- core/src/main/java/com/netease/arctic/table/BasicUnkeyedTable.java
Close #1959 .
- orphan files clean should not clean statistics files
- add unit test case
> [AMORO-1959] fix orphan files clean mistakenly delete the statistics files

- flink/v1.14/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java
- flink/v1.14/flink/src/test/java/com/netease/arctic/flink/table/TestLookupSecondary.java
- flink/v1.15/flink/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java
- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/TestLookupSecondary.java
Close #1891 .
- Update ArcticDynamicSource#getProjectedSchema(), and add primary keys into the projected schema if it is incomplete.
- Update Flink 1.14 and 1.15
> [AMORO-1891] Incomplete Lookup Table Source schema needs automatic primary key addition

- dist/src/main/arctic-bin/bin/ams.sh
Close #2006.
- The return value of the previous command is only evaluated once
- If yes, how is the feature documented? (not applicabled)
> [AMORO-2006] Fix value logic in startup shell

- docker/demo-cluster.sh
Close #2010.
- Change 'PROJECT_VERSION' to 'latest'.
- Remove useless alias
> [AMORO-2010] Modify Docker Image version to 'latest' in the startup script

- core/src/main/java/com/netease/arctic/mixed/MixedTables.java
Close #2029.
- Wrapper tables with ArcticTableOperations when load/create table.
> [AMORO-2029]: Using ArcticTableOperation in mixed-iceberg

- flink/v1.15/flink/src/test/java/com/netease/arctic/flink/table/LookupITCase.java
Fix Flink LookUpJoin TestLookup Test Failed（Just Modify Flink 1.15 Model）
Close #2061.
- add streaming config
> [AMORO-2061] Fix Flink LookUpJoin TestLookup Test Failed

- ams/server/src/test/java/com/netease/arctic/server/manager/TestActivePluginManager.java
fix ci problem of TestActivePluginManager
rename loading class name to pass ci
> [Hotfix]: Fix ci problem in master branch

- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BasicOptimizeCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/SupportHiveCommit.java
- ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/SupportHiveSyncService.java
- hive/src/main/java/com/netease/arctic/hive/op/OverwriteHiveFiles.java
- hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java
- hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
- hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java
Close #1898 .
- move files to the location stored in iceberg properties instead of to the hive location
- support check and fix hive location before committing
> [AMORO-1898] 0.4.x fix move files to stale hive location for Mixed Hive Table

- flink/flink-common/pom.xml
> [Build] Remove duplicated dependency

- .github/workflows/core-hadoop2-ci.yml
- .github/workflows/core-hadoop3-ci.yml
- .github/workflows/trino-ci.yml
Limit concurrency of workflow to reduce task queuing in GitHub Actions.
> [CI] Limit concurrency of workflow

- ams/server/pom.xml
- ams/server/src/main/java/com/netease/arctic/server/ArcticManagementConf.java
- docker/amoro/Dockerfile
- docs/admin-guides/deployment.md
- pom.xml
Close #2036.
- Remove dependency on `mysql:mysql-connector-java`
- Change the deployment doc
- Download `mysql:mysql-connector-java` dependency for Amoro Docker image
> [AMORO-2036]Remove dependency on `mysql:mysql-connector-java`

- core/pom.xml
- core/src/main/java/com/netease/arctic/io/reader/CombinedDeleteFilter.java
- pom.xml
Close #2078.
- Reduce memory for large pos-deletes
> [AMORO-2078] Replace set with bitmap when apply pos delete records

- flink/flink-common-iceberg-bridge/pom.xml
- flink/flink-common/pom.xml
- flink/pom.xml
- flink/v1.16/flink-runtime/pom.xml
- flink/v1.16/flink/pom.xml
- flink/v1.17/flink/pom.xml
Add Support Flink 1.16 POM
Close #2027.
- Add Support Flink 1.16 POM And Model
> [AMORO-2027] Flink supports 1.16 version

- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/utils/DesensitizationUtil.java
Close #2102.
- support hidden catalog properties
- support desensitize data of catalog configuration
> [AMORO-2102] Support hidden catalog properties and desensitized secret key

- docs/concepts/table-watermark.md
- docs/user-guides/using-tables.md
> [AMORO-2154] Remove redundant whitespace characters

- trino/src/main/java/com/netease/arctic/trino/DefaultArcticCatalogFactory.java
Fix double-checked locking field is not declared volatile in `DefaultArcticCatalogFactory`
-
> [Improvement] Fix double-checked locking field is not declared volatile

- ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java
Polish the code to obtain the Paimon table compaction information.
- Push down page logic.
- Abstract ServerTableDescriptor's method.
- Reduce logic in the controller.
> [Improvement] Polish the code to obtain the Paimon table compaction information

- core/src/test/java/com/netease/arctic/catalog/TableTestBase.java
- core/src/test/java/com/netease/arctic/io/TestBasicTableTrashManager.java
- core/src/test/java/com/netease/arctic/io/TestRecoverableArcticFileIO.java
Try to fix the error in the unit tests.
- Drop database after table related test finished.
> [Hotfix]Drop database after table test finished

- charts/amoro/templates/NOTES.txt
Fix notes text when helm deployment.
- Fix notes text of helm deployment notes.
> [Fix]: Fix notes text in helm startup

- ams/server/src/main/java/com/netease/arctic/server/catalog/CatalogType.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/CatalogController.java
- ams/server/src/main/java/com/netease/arctic/server/terminal/TerminalManager.java
- core/src/main/java/com/netease/arctic/catalog/IcebergCatalogWrapper.java
- core/src/main/java/com/netease/arctic/utils/CatalogUtil.java
Close #2192.
- put S3 related properties to catalog properties
> [AMORO-2192] Fix S3 related configurations not working

- ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java
Add the corresponding REST handler to DashboardServer.
Close #2213.
As titled.
- If yes, how is the feature documented? not documented
> [AMORO-2213] Expose table operations REST API

- ams/server/src/main/java/com/netease/arctic/server/ArcticServiceContainer.java
- dist/src/main/arctic-bin/conf/config.yaml
> [AMORO-2188] Fix NPE when only using external optimizers

- ams/server/src/main/java/com/netease/arctic/server/table/TableConfiguration.java
- ams/server/src/main/java/com/netease/arctic/server/table/executor/DataExpiringExecutor.java
> [AMORO-2208] Validate NULL data expiration configuration

- pom.xml
fix CVE: [CVE-2022-25845](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-25845)
- fix CVE's
>  Bump fastjson to 1.2.83

- dist/src/main/arctic-bin/bin/ams.sh
As titled.
Close #2218.
As titled.
-
> [AMORO-2218] Fix AMS's classpath order not consistent

- docs/formats/paimon.md
> [Doc]Add paimon doc about how to use s3 or oss

- docs/formats/overview.md
> [DOC] Fixed a counting error

- optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkReporter.java
Close #2242 .
- close Flink optimizer touch thread after failover
> [AMORO-2242] fix 0.4.x close Flink optimizer touch thread after failover

- ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/FormatTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizingProcessDetailInfo.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizingTaskInfo.java
Close #2117.
- Add new interface `/tables/catalogs/{catalog}/dbs/{db}/tables/{table}/optimizing-processes/{processId}/tasks`
```
{
"message": "success",
"code": 200,
"result": {
"list": [
{
"tableId": 1351,
"processId": 1698840207040,
"taskId": 1,
"partitionData": "",
"status": "SUCCESS",
"retryNum": 0,
"threadId": 0,
"startTime": 1698840208000,
"endTime": 1698840214000,
"costTime": 12038,
"failReason": null,
"summary": {
"newFileSize": 5148771,
"newFileCnt": 1,
"rewriteDataSize": 5338697,
"rewritePosDataSize": 0,
"equalityDeleteSize": 24091,
"positionalDeleteSize": 1849,
"rewriteDataFileCnt": 7,
"reRowDeletedDataFileCnt": 0,
"eqDeleteFileCnt": 6,
"posDeleteFileCnt": 1
},
"properties": {
"task-executor-factory-impl": "com.netease.arctic.optimizing.IcebergRewriteExecutorFactory"
}
}
], …
```
> [AMORO-2117] Support Http interface for getting details of optimizing tasks

- flink/flink-common/src/main/java/com/netease/arctic/flink/catalog/ArcticCatalog.java
CatalogTableImpl in Flink Feature is Deprecated,Use CatalogTable.of to Create CatalogBaseTable
Close #2264.
- Use CatalogTable.of Create CatalogBaseTable Replace to CatalogTableImpl
> [AMORO-2264] Flink Create Amoro CatalogTableImpl Use CatalogTable.of

- README.md
> [DOC] Add a supported table format

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
Close #2279
- Avoding optimizing status blocked
> [AMORO-2279] Retry failed tasks when restarting AMS

- docs/admin-guides/deployment.md
fix doc
-Change the wrong url to the right one
> [Doc] Fix a download jump url error on the Deploy page.

- ams/dashboard/README.md
> Fix typo in dashboard's README.md

- ams/server/src/main/java/com/netease/arctic/server/table/DefaultTableService.java
- core/src/main/java/com/netease/arctic/utils/TablePropertyUtil.java
Close #2302.
- Ignore Iceberg if it is a table store of mixed-iceberg when sync table in external catalog
> [AMORO-2302]: Donot trigger optimizing for mixed iceberg table store in Iceberg catalog.

- ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
> [AMORO-2318]: Fix cost time for TaskRunTime

- flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/ArcticRowDataLookupFunction.java
- flink/flink-common/src/main/java/com/netease/arctic/flink/lookup/BasicLookupFunction.java
- flink/flink-common/src/main/java/com/netease/arctic/flink/table/ArcticDynamicSource.java
Close #2357.
- Use LookupFunctionProvider Replace Deprecated TableFunctionProvider
> [AMORO-2357] Flink Use LookupFunctionProvider Replace Deprecated TableFunctionProvider

- core/src/main/java/com/netease/arctic/optimizing/OptimizingInputProperties.java
Fix a typo issue in `OptimizingInputProperties` class.
-
> Fix typo in OptimizingInputProperties.java

- ams/server/src/main/java/com/netease/arctic/server/table/executor/SnapshotsExpiringExecutor.java
> Update wrong comments in SnapshotsExpiringExecutor.java

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
When AMS restarts, we set the snapshot id of the base store to that of the change store.
- set the correct change snapshot id
> [HotFix] Fix loading the optimizing snapshot id of change store for Mixed Format KeyedTable

- ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/MixedTableMaintainer.java
Close #2440 
- using the correct list of files
> [AMORO-2440] Fix the batch deletion of Change Store files for Mixed Format Table

- ams/optimizer/flink-optimizer/pom.xml
Close #2418.
- No more expcetion
> [AMORO-2418] Exclude kryo dependency from flink-optimizer

- .github/labeler.yml
As #2374 changed the structure of project modules, this PR try to fix the GitHub labeler issue.
- Fix `labeler.yml`
> [Infra]Fix github labeler for module changes

- ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java
Close #2468.
- Return when 'null'.
> [AMORO-2468] Fix NPE when cleaning

- ams/server/src/main/java/com/netease/arctic/server/optimizing/UnKeyedTableCommit.java
- mixed/hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java
- mixed/hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java
Close #2454.
- use the new RewriteFiles API
- support special case for optimizing commit
> [AMORO-2454] Self-Optimizing commit for the Iceberg Format table will not separately remove Delete files

- ams/dashboard/mock/modules/catalogs.js
- ams/dashboard/mock/modules/common.js
- ams/dashboard/mock/modules/table.js
Support [Menu Table] mock server
-
> [Feature]: Support Menu Table mock server

- ams/dashboard/mock/modules/catalogs.js
Supports Catalogs Menu Mock Server
Close #xxx.
-
> [Feature]: Supports Catalogs Menu Mock Server

- ams/dashboard/mock/modules/common.js
- ams/dashboard/mock/modules/terminal.js
- ams/server/src/main/java/com/netease/arctic/server/terminal/local/LocalSessionFactory.java
Supports Terminal Menu Mock Server
Close #xxx.
-
> [Improvement]: Supports Terminal Menu Mock Server

- ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/CommonPartitionEvaluator.java
close #2509 improve 1
- Remove the condition (rewritePosSegmentFileCount > 0)
> [AMORO-2509] Rollback the trigger condition of minor compaction

- core/src/main/java/com/netease/arctic/table/BasicUnkeyedTable.java
…rg.apache.iceberg.Table in Amoro
Close #2389.
-
> [AMORO-2389] Implement the toString() method for all the implementation class of org.apache.iceberg.Table in Amoro

- mixed/flink/v1.15/flink-runtime/pom.xml
- mixed/flink/v1.16/flink-runtime/pom.xml
- mixed/flink/v1.17/flink-runtime/pom.xml
When using Flink api to write data into mix-iceberg table, it will update the table metadata to incorrect value
Close #2525 .
- exclude org.apache.iceberg.mr.hive.* from shade flink runtime
> [AMORO-2525] Fix bug #2525 - When using Flink api to write data into mix-iceberg table, it will update the table metadata to incorrect value

- core/src/main/java/com/netease/arctic/utils/ExpressionUtil.java
- core/src/test/java/com/netease/arctic/BasicTableTestHelper.java
- core/src/test/java/com/netease/arctic/utils/TestKeyedExpressionUtil.java
- core/src/test/java/com/netease/arctic/utils/TestUnkeyedExpressionUtil.java
Close #2542 .
- Add detection to avoid throwing exceptions in `org.apache.iceberg.expressions`
> [AMORO-2542] Fix Using `transform` partition and the partition value is `null`, the problem of `optimizing` cannot be triggered

- docs/admin-guides/managing-optimizers.md
Fix typo for flink optimizer configuration
- fix typos
cc @zhoujinsong
> [docs] Fix typo for flink optimizer configuration

- pom.xml
Close #1946 .
- Upgrade javalin to 4.6.8
> [AMORO-1946]: javalin version bump to 4.6.8 #1946

- ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java
Close #2554.
- If the authToken expires, the task should be put into retry queue
> [AMORO-2554] If the authToken expires, the task should be put into retry queue

- README.md
Fix typo in README.md for Building
-fix typos
> [docs] Fix typo in README.md for Building

- docs/admin-guides/deployment-on-kubernetes.md
Fix  typo for flink conf in deployment on kubernetes
-
> [docs] Fix typo for flink conf in deployment on kubernetes

- ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java
- core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java
- core/src/main/java/com/netease/arctic/utils/TableFileUtil.java
- core/src/test/java/com/netease/arctic/utils/TestFileUtil.java
Close #2579.
- Remove as many empty directories as possible
> [AMORO-2579] Skip the direcotories if can not be deleted when expire snapshots

- ams/api/pom.xml
- ams/server/src/test/resources/log4j2.xml
- mixed/flink/flink-common-iceberg-bridge/pom.xml
Remove dependency log4j:1.2.17 and modify test log level
- Remove dependency log4j:1.2.17
- Modify test log level
> [Hotfix] Remove dependency log4j:1.2.17 and exclude logback

- charts/amoro/templates/amoro-deployment.yaml
> [AMORO-2589] Amoro Helm charts meet errors when rendering templates

- ams/optimizer/common/src/main/java/com/netease/arctic/optimizer/common/OptimizerExecutor.java
- ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkExecutor.java
- ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizer.java
- ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizerExecutor.java
Close #2510.
- Get TaskmanagerInfo through getRuntimeContext().getTaskManagerRuntimeInfo().getConfiguration() and add info  to the fail message
- Add a metric for the total number of tasks processed in the optimize executor, and include optimizeGroup as a label for easier visualization
> [AMORO-2510] [Improvement]: add some flink runtime info for optimizer

- ams/api/pom.xml
- ams/server/pom.xml
- ams/server/src/test/java/com/netease/arctic/server/persistence/TestNestedSqlSession.java
- core/pom.xml
- mixed/hive/pom.xml
- mixed/trino/pom.xml
- pom.xml
This is a part of the work for #2012 aiming at bumping some dependencies' versions to enhance the security of the project.
- Bump up `org.mockito:mockito-core` to 4.11.0 and it is the latest version that supports JDK8.
- Drop `org.powerpock:powermock-api-mockito2` dependency as mockito has supported mocking static method in 4.x.
- Bump up `org.apache.commons:commons-pool` to 2.12.0
- Bump up `org.apache.curator:curator-framework` to 5.6.0
- Bump up `org.apache.zookeeper:zookeeper` to 3.9.1
- Bump up `com.github.ben-manes.caffeine:caffeine` to 2.9.3 and it is the latest version that supports JDK8.
- Bump up `com.esotericsoftware:kyro` to 4.0.3
- Bump up `org.apache.common:commons-lang3` to 3.14.0
- Bump up `org.roaringbitmap:RoaringBitmap` to 1.0.1
- Bump up …
> [AMORO-2012]Bump up some dependencies' versions

- CONTRIBUTING.md
> [AMORO-2592] Optimizing location about building steps so that contributors fo find it easier

- mixed/flink/v1.15/flink-runtime/pom.xml
- mixed/flink/v1.16/flink-runtime/pom.xml
- mixed/flink/v1.17/flink-runtime/pom.xml
Close #2587.
- Add `org.apache.httpcomponents.client5:*` to Flink runtime jars
- Add `org.apache.httpcomponents.core5:*` to Flink runtime jars
- Relocation `org.apache.hc` to `com.netease.arctic.shaded.org.apache.hc`
- Apply changes to Flink 1.15/1.16/1.17
> [AMORO-2587] Add httpcomponents classes into Flink runtime jars

- ams/server/src/main/java/com/netease/arctic/server/table/DataExpirationConfig.java
Close #2603 
- provide default value if the property was null
> [AMORO-2603] Add default values in annotation for data expiration config

- ams/api/pom.xml
- ams/api/src/main/java/com/netease/arctic/ams/api/Action.java
- ams/api/src/main/java/com/netease/arctic/ams/api/ServerTableIdentifier.java
- ams/api/src/main/java/com/netease/arctic/ams/api/StateField.java
- ams/api/src/main/java/com/netease/arctic/ams/api/TableRuntime.java
- ams/api/src/main/java/com/netease/arctic/ams/api/config/DataExpirationConfig.java
- ams/api/src/main/java/com/netease/arctic/ams/api/config/OptimizingConfig.java
- ams/api/src/main/java/com/netease/arctic/ams/api/config/TableConfiguration.java
- ams/api/src/main/java/com/netease/arctic/ams/api/config/TagConfiguration.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/AmoroProcess.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/OptimizingStage.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/OptimizingState.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/PendingInput.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/ProcessFactory.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/ProcessState.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/ProcessStatus.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/SimpleFuture.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/TableProcess.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/TableProcessState.java
- ams/api/src/main/java/com/netease/arctic/ams/api/process/TableState.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/StatedPersistentBase.java
- ams/server/src/main/java/com/netease/arctic/server/table/DataExpirationConfig.java
- ams/server/src/main/java/com/netease/arctic/server/table/ServerTableIdentifier.java
- ams/server/src/main/java/com/netease/arctic/server/table/TableConfiguration.java
- ams/server/src/main/java/com/netease/arctic/server/table/TagConfiguration.java
- core/pom.xml
Close #2597.
Define action and process api in ams-api module
- There are process interfaces under process package.
- TableRuntime would be pulled into api for ProcessFactory interface as well as ServerTableIdentifier and TableConfiguration
> [AMORO-2597] Define action and process api in ams-api module

- core/src/main/java/com/netease/arctic/scan/TableEntriesScan.java
> [AMORO-2617]Failed to remove orphan files after dropping a partition field

- ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
…er according to the snapshot time of the table
Close #2606.
-
> [Amoro-2606] Paimon snapshot display on the page should be arranged in reverse order according to the snapshot time of the table

- mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/catalog/MixedCatalog.java
- mixed/flink/flink-common/src/test/java/com/netease/arctic/flink/catalog/TestLegacyMixedCatalog.java
Close #2.
- Flink support for Setting/Altering Amoro table properties
- Add Tests about change the key properties
> [AMORO-2] Flink support for Setting/Altering Amoro table properties

- mixed-format/spark/v3.2/spark/src/main/scala/com/netease/arctic/spark/sql/ArcticExtensionUtils.scala
- mixed-format/spark/v3.3/spark/src/main/scala/com/netease/arctic/spark/sql/ArcticExtensionUtils.scala
Close #2633 .
- Use the current database of the catalog as the table name for the database.
> [Bug]: spark failed to call 'create table t1 like t2'

- ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
> [AMORO-2614]Get `PartitionSpec` based on the specId carried by the file

- ams/server/src/main/java/com/netease/arctic/server/optimizing/maintainer/IcebergTableMaintainer.java
> [AMORO-2619]Skip the deleted direcotories when cleaning orphan files

- ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java
> [AMORO-2631]When the optimizer expires, filter out the tasks that are in a successful state

- ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
Optimize codes and reduce memory footprints.
Replace mutable collections with the immutable ones.
> [Hotfix] Optimize codes of task status transition map

- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/LoginController.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/OptimizerController.java
- ams/server/src/main/java/com/netease/arctic/server/dashboard/model/OptimizerInstanceInfo.java
Close #2654.
- Discard import shade class of jackson in `com.netease.arctic.server.dashboard.controller` package,  maybe there are conflicting between javalin's default jsonmapper and shade class.
> [Hotfix] Cannot construct instance of Jsonnode when doing login

- .github/workflows/docker-images.yml
> [AMORO-2636] Auto build official docker image of spark optimizer

- ams/server/src/main/java/com/netease/arctic/server/DefaultOptimizingService.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
- ams/server/src/test/java/com/netease/arctic/server/TestDefaultOptimizingService.java
> [AMORO-2612]Avoid task always being in scheduled state

- ams/server/src/main/java/com/netease/arctic/server/exception/ArcticRuntimeException.java
- ams/server/src/main/java/com/netease/arctic/server/exception/TaskRuntimeException.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
- ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
- core/src/main/java/com/netease/arctic/ErrorCodes.java
- core/src/test/java/com/netease/arctic/MockArcticMetastoreServer.java
Close #2662
- Added an IllegalTaskException
> [AMORO-2662]After the token expires,the optimizer repeatedly commits tasks that have been reset to ams

- docs/engines/flink/flink-dml.md
Close #2002.
- Add Introduce the Lookup Join with mixed-format table via Flink
> [AMORO-2002][DOC]: Introduce the Lookup Join with mixed-format table via Flink

- .github/workflows/docker-images.yml
- ams/optimizer/spark-optimizer/pom.xml
> [AMORO-2677] Fix github ci error for the spark-optimizer image

- ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java
- ams/server/src/main/java/com/netease/arctic/server/persistence/StatedPersistentBase.java
- ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java
- ams/server/src/test/java/com/netease/arctic/server/persistence/TestStatedPersistentBase.java
> [Hotfix] Fix typo in StatedPersistentBase

- ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java
> [AMORO-2623] Avoid deadlock in task cancellation

- ams/server/src/main/java/com/netease/arctic/server/ArcticManagementConf.java
- docs/admin-guides/deployment.md
Close #2496.
- Add configuration docs for AMS terminal
> [AMORO-2496][DOC]: Add configuration docs for AMS terminal

- ams/optimizer/flink-optimizer/src/main/java/com/netease/arctic/optimizer/flink/FlinkOptimizer.java
- ams/optimizer/spark-optimizer/src/main/java/com/netease/arctic/optimizer/spark/SparkOptimizer.java
> [AMORO-2683] Modify the job name of SparkOptimizer and FlinkOptimizer

- docker/optimizer-flink/Dockerfile
Close #2681.
- Upgrade Optimizer Flink Docker File Flink and aws versions
> [AMORO-2681] Upgrade Optimizer Flink Docker File

- docker/optimizer-spark/Dockerfile
> [AMORO-2696] Upgrade Optimizer Spark Docker File

- README.md
> [Hotfix] update start history link

- docs/admin-guides/deployment-on-kubernetes.md
Fix typo in deployment-on-kubernetes.md
- docs/admin-guides/deployment-on-kubernetes.md
No need to test
- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? docs
> [Hotfix] Fix typo in deployment-on-kubernetes.md

- ams/server/src/main/java/com/netease/arctic/server/persistence/mapper/CatalogMetaMapper.java
> [Bug] fix wrong column name in CatalogMetaMapper

- .idea/vcs.xml
> [AMORO-2742] Update issue link to apache

- core/src/main/java/com/netease/arctic/formats/iceberg/IcebergCatalog.java
Close #2743 .
- call method through doAs
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented)**
> [AMORO-2743]add doAs before call catalog method in IcebergCatalog class

- ams/dashboard/src/views/catalogs/Detail.vue
Close #2630 .
- Support choose multi formats when add a new catalog
> [AMORO-2630] Support choose multi formats when add a new catalog

- core/src/main/java/org/apache/amoro/table/TableProperties.java
- mixed-format/spark/v3.2/spark/src/main/java/org/apache/amoro/spark/table/ArcticSparkTable.java
- mixed-format/spark/v3.3/spark/src/main/java/org/apache/amoro/spark/table/ArcticSparkTable.java
> [AMORO-2755] Add judgment and reduce duplicate 'put'

- pom.xml
> [AMORO-2765] Filter out jersey in hadoop client

- CONTRIBUTING.md
- README.md
Fix README.md adapt to new module name
> [Hotfix][Docs] Fix README.md adapt to new module name

- .github/labeler.yml
Fix labeler.yml adapt to new folder
> [Hotfix][Infra] Fix labeler.yml adapt to new folder

- amoro-ams/amoro-ams-dashboard/README.md
Fix the dashboard README.md adapt to new module name
Fix the dashboard README.md adapt to new module name
> [Hotfix][Docs] Fix the dashboard README.md adapt to new module name

- .github/workflows/docker-images.yml
- docker/amoro/Dockerfile
Fix docker file for amoro.
- Fix the docker file for the new dist folder
- Fix the GitHub workflows for new apache org
> [Hotfix] Fix docker file and GitHub workflows

- .github/workflows/docker-images.yml
Fix docker images workflow.
- Change the module folder in docker images workflow configurations
> [Hotfix] Fix docker images workflow due to folder change

- .github/workflows/docker-images.yml
Flink/Spark optimizer build failed in ci: https://github.com/apache/amoro/actions/runs/8874353412/job/24361638596
This PR try to fix it.
- Correct the optimizer folder
> [Hotfix] Fix building error for docker images of optimizers

- amoro-ams/amoro-ams-server/pom.xml
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/KubernetesOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/LocalOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/main/resources/META-INF/services/org.apache.amoro.api.resource.ResourceContainer
- amoro-ams/dist/src/main/arctic-bin/bin/optimizer.sh
- amoro-ams/dist/src/main/arctic-bin/conf/config.yaml
- charts/amoro/templates/_optimizer.tpl
- charts/amoro/templates/amoro-configmap.yaml
- charts/amoro/values.yaml
- docker/amoro/entrypoint.sh
- docs/admin-guides/managing-optimizers.md
- pom.xml
Close #1958.
- KubernetesOptimizerContainer Support Running On K8S
> [AMORO-1958] Implement KubernetesOptimizerContainer to support running Optimizer natively on K8S

- amoro-ams/amoro-ams-optimizer/common/src/main/java/org/apache/amoro/optimizer/common/AbstractOptimizerOperator.java
hotfix
FlinkOptimizerExecutor runs in an independent thread, so the `stopped` variable is maintained by multiple threads.
> [Hotfix] Apply the volatile modifier to stopped variable.

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/TerminalController.java
Close #2772.
- Auto generate terminal sessionID if not specified
> [AMORO-2772] Auto generate terminal sessionID if not specified

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/HighAvailabilityContainer.java
As titled.
Replace transient keyword with volatile, cause followerLath could be updated by different threads.
> [Hotfix] Fix wrong usage of transient in HighAvailabilityContainer

- amoro-ams/amoro-ams-server/pom.xml
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/VersionController.java
Close #2813 
Before this commit, it would only show the version of the project at the topbar,   but this may not be enough for some cases, in this commit we enhanced the version info by including the abbrev.
-
> [AMORO-2813] Improve the version info about the project

- amoro-ams/amoro-ams-dashboard/src/components/Topbar.vue
- amoro-ams/amoro-ams-dashboard/src/components/VirtualRecycleScroller.vue
- amoro-ams/amoro-ams-dashboard/src/components/echarts/Chart.vue
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/login/index.vue
login Component import
Close #xxx.
-
> [AMORO-2730]: fix the login Component import

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/TerminalManager.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/TerminalSessionContext.java
> [AMORO-2823] update catalog meta and corresponding terminal session

- amoro-ams/amoro-ams-dashboard/src/views/terminal/index.vue
> Shortcut display disorder in terminal page

- .github/workflows/trino-ci.yml
minor
Simplify the packaging and testing ci process for trino module.
`-pl 'amoro-ams/amoro-ams-api,amoro-core,amoro-mixed-format/amoro-mixed-format-hive'` and `-am` are in conflict.
We can use `-pl 'amoro-mixed-format/amoro-mixed-format-trino' -am`.
```
[root@djump /work/amoro/amoro]#  
[root@djump /work/amoro/amoro]#  mvn17 clean install -pl 'amoro-mixed-format/amoro-mixed-format-trino' -Dhadoop=v2 -am -B -P trino-spotless
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Amoro Project Parent                                               [pom]
[INFO] Amoro Project Core                                                 [jar]
[INFO] Amoro Project AMS Parent …
```
> [MINOR] Simplify the packaging and testing ci process for trino module

- amoro-ams/amoro-ams-dashboard/mock/modules/settings.js
- pom.xml
Close #2845.
Fix incorrect mock data about optimize group.
> [AMORO-2845] Fix incorrect mock data about optimize group

- CONTRIBUTING.md
- README.md
- docs/admin-guides/deployment.md
The build guide now is quite complex, I tried to simplify it. 
- Simplify project build guide.
> [Improvement] Improve project build guide

- amoro-ams/amoro-ams-dashboard/package.json
- amoro-ams/amoro-ams-dashboard/src/components/VirtualRecycleScroller.vue
- amoro-ams/amoro-ams-dashboard/src/components/loading/loading.vue
- amoro-ams/amoro-ams-dashboard/src/components/sql-editor/index.vue
- amoro-ams/amoro-ams-dashboard/src/main.ts
- amoro-ams/amoro-ams-dashboard/src/utils/editor.ts
fix eslint warning error & ts error
#2852 
-
> [AMORO-2852]: fix eslint error & ts

- docker/README.md
- docker/build.sh
hotfix.
Fix some minor issues about docker.
> [hotfix] Fix some minor issues about docker

- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/pom.xml
- amoro-mixed-format/amoro-mixed-format-spark/amoro-mixed-format-spark-3-common/pom.xml
- amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-3.2/pom.xml
- pom.xml
Bump up the Spark32 version from 3.2.2 to 3.2.4 to avoid vulnerable issues.
- Bump up spark32 version to 3.2.4
> [Hotfix] Bump up spark32 version to 3.2.4

- amoro-mixed-format/amoro-mixed-format-trino/pom.xml
Bump up commons-collections to 3.2.2 to avoid vulnerable issues.
- Bump up commons-collections to 3.2.2.
> [Hotfix] Bump up commons-collections for amoro-mixed-format-trino module

- amoro-mixed-format/amoro-mixed-format-trino/pom.xml
Bump up jackson-databind to 2.13.5 to avoid vulnerable issues.
- Bump up jackson-databind to 2.13.5
> [Hotfix] Bump up jackson-databind version for amoro-mixed-format-trino module

- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/pom.xml
As titled.
- Remove unused profiles in Spark optimizer module
> [Hotfix] Remove unused profiles in Spark optimizer module

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/RestCatalogService.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/catalog/ExternalCatalog.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/catalog/InternalCatalog.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/catalog/InternalIcebergCatalogImpl.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/catalog/MixedHiveCatalogImpl.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/catalog/ServerCatalog.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/DefaultTableService.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/TestInternalIcebergCatalogService.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/catalog/TestServerCatalog.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/optimizing/TestIcebergHadoopOptimizing.java
- amoro-core/src/main/java/org/apache/amoro/AmoroCatalog.java
- amoro-core/src/main/java/org/apache/amoro/CommonUnifiedCatalog.java
- amoro-core/src/main/java/org/apache/amoro/formats/iceberg/IcebergCatalog.java
- amoro-core/src/main/java/org/apache/amoro/formats/mixed/MixedCatalog.java
- amoro-core/src/main/java/org/apache/amoro/formats/paimon/PaimonCatalog.java
- amoro-core/src/test/java/org/apache/amoro/formats/TestAmoroCatalogBase.java
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/catalog/FlinkUnifiedCatalog.java
- amoro-mixed-format/amoro-mixed-format-spark/amoro-mixed-format-spark-3-common/src/main/java/org/apache/amoro/spark/SparkUnifiedCatalog.java
- amoro-mixed-format/amoro-mixed-format-spark/amoro-mixed-format-spark-3-common/src/test/java/org/apache/amoro/spark/test/SparkTestBase.java
- amoro-mixed-format/amoro-mixed-format-spark/amoro-mixed-format-spark-3-common/src/test/java/org/apache/amoro/spark/test/unified/UnifiedCatalogTestSuites.java
Close #2886.
Optimize the naming of database/table methods in AmoroCatalog and ServerCatalog.
rename `boolean exists(String database);` to `boolean databaseExists(String database);`
rename `boolean exists(String database, String table);` to `boolean tableExists(String database, String table);`
> [AMORO-2886] Optimize the naming of database/table methods in catalog

- charts/amoro/values.yaml
> [Hotfix] Correct the refer urls in helm chart's values.yaml

- README.md
- amoro-ams/amoro-ams-dashboard/pom.xml
Close #2910.
We need to build the project many times for debug some issues, so add this profile to speed up the build.
> [AMORO-2910] Add profile to skip WebUI build process

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/maintainer/IcebergTableMaintainer.java
Instants are zoneless, thus it's redundant to adjust the zone of an instant.
-
> [Hotfix] Optimize code in IcebergTableMaintainer

- .github/ISSUE_TEMPLATE/bug_report.yml
Table format is important information when reporting a bug, we should add a selector for it in our bug report issue template.
- Add a table format selector to the bug report issue template.
> [Improvement] Add a table format selector to the bug report issue template

- amoro-core/src/main/java/org/apache/amoro/table/TableMetaStore.java
Close #2918.
- Create different UGI for different Hadoop usernames.
> [AMORO-2918] Support multiple simple authrization username for different catalogs

- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/v1.15/amoro-mixed-format-flink-runtime-1.15/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/v1.16/amoro-mixed-format-flink-runtime-1.16/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/v1.17/amoro-mixed-format-flink-1.17/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/v1.17/amoro-mixed-format-flink-runtime-1.17/pom.xml
- amoro-mixed-format/amoro-mixed-format-spark/v3.2/amoro-mixed-format-spark-runtime-3.2/pom.xml
- amoro-mixed-format/amoro-mixed-format-spark/v3.3/amoro-mixed-format-spark-runtime-3.3/pom.xml
- pom.xml
This PR tried to improve the maven shade plugin configurations.
- Add some global shade plugin configurations.
- Adjust shade artifacts for runtime jars.
> [Improvement] Improve shade plugin configurations

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/utils/ParamSignatureCalculator.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/utils/TableStatCollector.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/AbstractPluginManager.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/FlinkOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/LocalOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/SparkOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/maintainer/IcebergTableMaintainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/maintainer/MixedTableMaintainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/TerminalManager.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/AmsEnvironment.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/optimizing/maintainer/TestOrphanFileCleanIceberg.java
- amoro-core/src/main/java/org/apache/amoro/mixed/MixedTables.java
- amoro-core/src/main/java/org/apache/amoro/utils/map/RocksDBBackend.java
- amoro-core/src/test/java/org/apache/amoro/MockAmoroManagementServer.java
- amoro-core/src/test/java/org/apache/amoro/catalog/MixedTables.java
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/main/java/org/apache/amoro/flink/metric/MetricsGenerator.java
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/test/java/org/apache/amoro/flink/lookup/ByteArraySetSerializerTest.java
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/src/test/java/org/apache/amoro/flink/read/TestMixedFormatSource.java
- amoro-mixed-format/amoro-mixed-format-hive/src/main/java/org/apache/amoro/hive/catalog/MixedHiveTables.java
- amoro-mixed-format/amoro-mixed-format-spark/amoro-mixed-format-spark-3-common/src/test/java/org/apache/amoro/spark/test/SparkTestBase.java
- amoro-mixed-format/amoro-mixed-format-trino/src/main/java/org/apache/hadoop/util/VersionInfo.java
LOG output uses `{}` to replace the `+` operation
> [Hotfix] LOG output uses `{}` to replace the `+` operation

- amoro-ams/dist/pom.xml
- amoro-ams/dist/src/main/assemblies/bin.xml
- docs/admin-guides/deployment.md
- pom.xml
- tools/releasing/create_binary_release.sh
- tools/releasing/create_source_release.sh
- tools/releasing/deploy_staging_jars.sh
Add some releasing tools to help simplify the releasing process.
The scripts are copied from [Apache Flink](https://github.com/apache/flink/tree/master/tools/releasing) project and modified as needed.
- Add create_release_binary.sh
- Add create_source_release.sh
- Add deploy_staging_jars.sh
- Change the compression method of AMS from zip to tar.gz
> Add releasing tools

- docker/amoro/Dockerfile
- docker/build.sh
As titled.
- Fix docker build ci to adapt to the new AMS bin package.
> [Hotfix] Fix docker build ci

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java
> [AMORO-2934] Update lastOptimizedSnapshotId to currentSnapshotId When there is no task to be optimized

- docker/build.sh
hotfix, fix unknown args when exec build script.
```
#./build.sh --tag v0.7 amoro-flink-optimizer
Unknown args of v0.7
Usage: ./build.sh [options] [image]
Build for Amoro demo docker images.
Images:
amoro-flink-optimizer   Build official Amoro optimizer deployed with flink engine for production environments.
amoro-spark-optimizer   Build official Amoro optimizer deployed with spark engine for production environments.
amoro                   Build official Amoro image used for production environments.
Options:
--flink-version         Flink binary release version, default is 1.15.3, format must be x.y.z
--spark-version         Spark binary release version, default is 3.3.3, format must be x.y.z
--apache-archive        Apache Archive url, default is https://archive.apache.org/dist …
```
> [hotfix] Fix unknown args when exec build script

- pom.xml
> [Hotfix] Bump Hadoop version to 3.4.0 and fix related critical vulnerabilities

- .github/labeler.yml
As titled.
- Fix some errors in `.github/labeler.yml`
> [Hotfix] Fix GitHub labeler configurations

- docs/_index.md
- docs/admin-guides/deployment-on-kubernetes.md
- docs/admin-guides/deployment.md
- docs/admin-guides/managing-catalogs.md
- docs/admin-guides/managing-optimizers.md
- docs/admin-guides/using-kyuubi.md
- docs/concepts/catalogs.md
- docs/concepts/self-optimizing.md
- docs/concepts/table-watermark.md
- docs/engines/flink/flink-ddl.md
- docs/engines/flink/flink-dml.md
- docs/engines/flink/flink-ds.md
- docs/engines/flink/flink-get-started.md
- docs/engines/flink/using-logstore.md
- docs/engines/spark/spark-conf.md
- docs/engines/spark/spark-ddl.md
- docs/engines/spark/spark-get-started.md
- docs/engines/spark/spark-queries.md
- docs/engines/spark/spark-writes.md
- docs/engines/trino.md
- docs/formats/iceberg.md
- docs/formats/mixed-hive.md
- docs/formats/mixed-iceberg.md
- docs/formats/overview.md
- docs/formats/paimon.md
- docs/user-guides/cdc-ingestion.md
- docs/user-guides/configurations.md
- docs/user-guides/metrics.md
- docs/user-guides/using-tables.md
- pom.xml
As titled.
- Add Apache license header for all files under `docs`.
- Adapt apache-rat plugin configuration.
> [Improvement] Add apache license header for docs

- pom.xml
Exclude aws bundles from hadoop-aws, we have declared the dependencies of AWS separately.
- Exclude aws bundles from hadoop-aws
> [Improvement] Remove aws bundle dependencies from ams bin

- docker/README.md
- docker/amoro/Dockerfile
- docker/build.sh
As title
Add maven-mirror to speed up building image doc
> [Improvement] Add maven-mirror to speed up building image doc

- pom.xml
As titled.
- Extend jar plugin from apache parent.
- Add outputTimestamp to help generate right NOTICE file
- Add maven-remote-resources-plugin configuration to include DISCLAIMER
> [Improvement] Fix maven jar plugin configuration for apache release

- .github/workflows/docker-images.yml
Change `mvn install` to `mvn package` to build amoro docker image.
- Change `mvn install` to `mvn package` to build amoro docker image.
> [Hotfix] Fix amoro docker image build ci

- .github/workflows/core-hadoop2-ci.yml
- .github/workflows/docker-images.yml
- .github/workflows/trino-ci.yml
- README.md
- pom.xml
- tools/releasing/create_binary_release.sh
Add `hadoop2` profile and set the default to `hadoop3`.
- Remove `hadoop3` profile and make it the default
- Change profile activition
- Adapt GitHub workflows and README
> [Improvement] Improve maven profile configurations for hadoop version

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/local/LocalSessionFactory.java
This pr is related to issue #2969 and has been manually tested locally.
Close #2969.
-
> [Improvement]: Eliminate AMS Full GC impact deriving from local terminal clean spark context #2969

- amoro-ams/amoro-ams-dashboard/src/components/Sidebar.vue
- amoro-ams/amoro-ams-dashboard/src/components/Topbar.vue
Close #xxx.
https://github.com/apache/amoro/assets/70570907/6d41b97a-1db3-4f42-9eeb-ae3019edbb76
> [Improvement] Support changing language for dashboard

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/OptimizingQueue.java
If we upgrade AMS but there are tables whose status is running, AMS can not start normally for the deserialization error. The root cause is that `TableRuntime#completeProcessL283 optimizingProcess.getTargetSnapshotId()`  optimizingProcess has not been initialized yet.
Exception stack:
```
Caused by: java.io.InvalidClassException: org.apache.amoro.table.TableMetaStore; local class incompatible: stream classdesc serialVersionUID = -7257151990323524190, local class serialVersionUID = 8582766959166530544
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699) ~[?:1.8.0_412]
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005) ~[?:1.8.0_412]
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852) ~[?:1.8.0_412]
at …
```
> [Hotfix] Meet NPE when loading task runtimes

- amoro-ams/amoro-ams-dashboard/src/language/en.ts
- amoro-ams/amoro-ams-dashboard/src/language/zh.ts
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/Detail.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/components/ErrorMsg.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Operations.vue
> [AMORO-2996] Reload catalogs page after removing the existing catalog

- amoro-ams/amoro-ams-dashboard/src/components/tables-sub-menu/CreateDB.vue
- amoro-ams/amoro-ams-dashboard/src/language/en.ts
- amoro-ams/amoro-ams-dashboard/src/language/zh.ts
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/Detail.vue
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/components/ErrorMsg.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/GroupModal.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Operations.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Optimizing.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/terminal/components/sql-result.vue
> WIP [AMORO-3002] Complete internationalization for some remaining pages

- amoro-ams/amoro-ams-dashboard/src/components/tables-sub-menu/CreateDB.vue
- amoro-ams/amoro-ams-dashboard/src/language/en.ts
- amoro-ams/amoro-ams-dashboard/src/language/zh.ts
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/Detail.vue
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/components/ErrorMsg.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/GroupModal.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Operations.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Optimizing.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/terminal/components/sql-result.vue
> Revert "WIP [AMORO-3002] Complete internationalization for some remaining pages"

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/optimizing/plan/CommonPartitionEvaluator.java
Close #3009 .
- Treat read and write cost as the same when evaluating optimizing
> [AMORO-3009] Treat read and write cost as the same when evaluating optimizing

- amoro-ams/amoro-ams-dashboard/src/App.vue
- amoro-ams/amoro-ams-dashboard/src/components/Topbar.vue
- amoro-ams/amoro-ams-dashboard/src/language/en.ts
- amoro-ams/amoro-ams-dashboard/src/language/zh.ts
- amoro-ams/amoro-ams-dashboard/src/views/catalogs/Detail.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/components/ErrorMsg.vue
- amoro-ams/amoro-ams-dashboard/src/views/hive-details/upgrade.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/GroupModal.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Operations.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Optimizing.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Selector.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/index.vue
- amoro-ams/amoro-ams-dashboard/src/views/terminal/components/sql-result.vue
Close #xxx.
https://github.com/apache/amoro/assets/70570907/f5d2801b-ac30-485a-96ee-6528a2c0671f
> [Improvement] Complete internationalization for some remaining pages

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/local/LocalSessionFactory.java
> [AMORO-3015]terminal can't create iceberg table when using unified catalog

- amoro-ams/amoro-ams-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java
- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/pom.xml
- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/src/main/java/org/apache/amoro/optimizer/spark/SparkOptimizerExecutor.java
- amoro-core/src/main/java/org/apache/amoro/io/AuthenticatedHadoopFileIO.java
- amoro-core/src/main/java/org/apache/amoro/io/reader/StructLikeFunnel.java
- amoro-core/src/main/java/org/apache/amoro/table/TableMetaStore.java
- amoro-core/src/main/java/org/apache/amoro/utils/SerializationUtil.java
- docs/admin-guides/managing-optimizers.md
Close #3012.
- Exclude unnecessary artifacts for spark optimizer.
- Improve some log messages.
- Remove some unnecessary methods.
> [AMORO-3012] Exclude unnecessary artifacts for spark optimizer

- .github/workflows/trino-ci.yml
- README.md
- amoro-ams/amoro-ams-server/pom.xml
- amoro-ams/dist/pom.xml
- amoro-core/pom.xml
- amoro-mixed-format/amoro-mixed-format-trino/pom.xml
- pom.xml
- tools/releasing/create_binary_release.sh
Following the discussion here: https://lists.apache.org/thread/2ss2ngmft9c2vh235lrdtxh18s5q52ho ,
the PR tried to make the RocksDB dependency optional.
- Add support-disk-storage profile to make RocksDB dependency optional
- Rename profile trino-spotless to format-mixed-format-trino
- Polish some dependencies
> [Improvement] Make RocksDB dependency optional

- amoro-ams/amoro-ams-dashboard/README.md
- amoro-ams/amoro-ams-dashboard/package.json
- amoro-ams/amoro-ams-dashboard/pom.xml
- amoro-ams/amoro-ams-dashboard/src/App.vue
- amoro-ams/amoro-ams-dashboard/src/components/Topbar.vue
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/ScaleOut.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/GroupModal.vue
- amoro-ams/amoro-ams-dashboard/src/views/terminal/index.vue
> [Improvement] set engines to prompt the lowest version of node and format code

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java
Close #3021.
- TableController get getTableDetail Runtime NPE Fixed,Use OptimizingStatus.IDLE By default not get
> [AMORO-3021]: AMS First Time Async Load External Catalog Select OptimizingStatus Have NPE (#3021) 

- amoro-ams/amoro-ams-dashboard/mock/modules/catalogs.js
- amoro-ams/amoro-ams-dashboard/src/components/tables-sub-menu/TablesMenu.vue
> [AMORO-3023]: fix the search input

- amoro-ams/amoro-ams-dashboard/mock/modules/catalogs.js
- amoro-ams/amoro-ams-dashboard/src/services/setting.services.ts
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/utils/ParamSignatureCalculator.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/exception/SignatureCheckException.java
As titled.
- Unify the common parts of the dashboard API and the open API.
- Improve some logging messages.
> [Improvement] Unify the common parts of the dashboard API and the open API

- amoro-ams/amoro-ams-dashboard/src/components/Layout.vue
- amoro-ams/amoro-ams-dashboard/src/utils/chart.ts
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Snapshots.vue
> [AMORO-2444] Fix the problem that the y-axis content is too long 

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/MixedAndIcebergTableDescriptor.java
Close #3029 .
- Return 0 records when the table has no snapshot.
> [AMORO-3029] Fix table record calculating with empty table

- README.md
As titled.
- Fix the description about `no-extented-disk-storage` profile.
> [Hotfix] Fix build guide in README.md

- tools/releasing/create_source_release.sh
Close #3043.
- Change source release file suffix to `tar.gz`
> [AMORO-3043] Change source release file suffix to `tar.gz`

- charts/amoro/templates/amoro-deployment.yaml
As titled.
- Fix liveness and readiness uri for amoro deployment
> [Hotfix] Fix liveness and readiness uri for amoro deployment

- pom.xml
Fix this problem
- Add test-jar goal for maven-jar-plugin
> [Improvement] Add test-jar goal for maven-jar-plugin

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/FormatTableDescriptor.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/MixedAndIcebergTableDescriptor.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/PaimonTableDescriptor.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/ServerTableDescriptor.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/dashboard/model/ConsumerInfo.java
Close #3027.
- Add getTableConsumerInfos interface and impl in FormatTableDescriptor
- Add getTableConsumerInfos in AMS Rest Api
> [AMORO-3027]: Support Paimon Consumer Info in Ams

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/executor/TableRuntimeRefreshExecutor.java
Close #3039.
- Update optimized snapshot id when optimizing evaluation result is unnecessary.
> [AMORO-3039] Update optimized snapshot id when optimizing evaluation result is unnecessary

- amoro-core/src/main/java/org/apache/amoro/client/AmsClientPools.java
- amoro-core/src/main/java/org/apache/amoro/client/OptimizingClientPools.java
- amoro-core/src/main/java/org/apache/amoro/client/PoolConfig.java
- amoro-core/src/main/java/org/apache/amoro/client/ThriftClientPool.java
- amoro-core/src/test/java/org/apache/amoro/client/TestPoolConfig.java
- docs/admin-guides/managing-optimizers.md
Close #3035.
- Support setting thrift client pool configs from the url.
- Polish some codes.
> [AMORO-3035] Support setting thrift client pool configs from url

- docs/admin-guides/managing-optimizers.md
Fix typo in managing-optimizers.md
> [Doc]Fix typo in managing-optimizers.md

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/terminal/TerminalManager.java
> [AMORO-3056] Support graceful shutdown for AMS

- amoro-ams/amoro-ams-dashboard/pom.xml
As titled.
This change will ensure that the automatically installed pnpm version remains consistent with `pnpm-lock.yaml`.
- Bump up pnpm to 9.6.0.
> Bump up pnpm to 9.6.0

- amoro-ams/amoro-ams-dashboard/src/views/tables/index.vue
> [Improvement] Prevent the table name from being truncated prematurely

- amoro-ams/amoro-ams-dashboard/src/types/common.type.ts
- amoro-ams/amoro-ams-dashboard/src/utils/index.ts
- amoro-ams/amoro-ams-dashboard/src/views/optimize/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/resource/components/List.vue
- amoro-ams/amoro-ams-dashboard/src/views/tables/components/Optimizing.vue
> [Hotfix] Fix the function that convert ms

- pom.xml
After releasing the amoro shade 0.7.0-incubating, we should change the dependency version here.
- Change amoro shade version to 0.7.0-incubating
> Change amoro shade version to 0.7.0-incubating

- .github/workflows/docker-images.yml
Close #3086.
- Add `latest` tag for release images
- Add `-hadoop3` suffix for hadoop3 buildings
> [AMORO-3086] Add more tags for amoro docker images built by ci

- amoro-ams/amoro-ams-server/src/main/resources/mysql/upgrade-0.6.1-to-0.7.0.sql
- amoro-ams/amoro-ams-server/src/main/resources/mysql/upgrade.sql
- amoro-ams/amoro-ams-server/src/main/resources/postgres/upgrade-0.6.1-to-0.7.0.sql
- amoro-ams/amoro-ams-server/src/main/resources/postgres/upgrade.sql
Move upgrade SQL for version 0.7.0
- Move upgrade SQL for version 0.7.0
> Move upgrade SQL for version 0.7.0

- README.md
This change is needed to fix the inconsistency between the description and the command line in the README.md.
> [Hotfix] Revised spark version in README.md

- .github/workflows/docker-images.yml
- README.md
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/FlinkOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/manager/TestFlinkOptimizerContainer.java
- amoro-ams/amoro-ams-server/src/test/resources/config.yaml
- amoro-ams/amoro-ams-server/src/test/resources/flink-conf.yaml
- docker/build.sh
- docker/optimizer-flink/Dockerfile
- pom.xml
Close #3087.
- Support FlinkOptimizerContainer With Flink 1.20
- Support new flink config with **config.yaml**
> [AMORO-3087]: Optimizer Support Flink 1.20 (#3087)

- CONTRIBUTING.md
As titled.
- Remove description about sign ICLA.
> Remove out-of-date guide in CONTRIBUTING.md

- .github/workflows/stale.yml
As titled.
- Add stale GitHub workflow
- Mark issue to be stale after 180 days with no activity and close it in next 14 days.
- Mark PR to be stale after 30 days with no activity and close it in next 7 days.
> Add stale GitHub workflow to improve Issue&PR management

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableOptimizingMetrics.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableRuntime.java
- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/utils/IcebergTableUtil.java
- amoro-ams/dist/src/main/amoro-bin/conf/plugins/metric-reporters.yaml
- docs/user-guides/metrics.md
Close #2993.
- As mentioned in the issue
> [AMORO-2993] Enrich optimizing metrics

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/manager/FlinkOptimizerContainer.java
Close #3128 .
- Make the yarn application name for flink optimizer more meaningful
before the change
after the change
- If yes, how is the feature documented? (not applicable
> [AMORO-3128] Make yarn application name for flink optimizer more meaningful

- amoro-ams/amoro-ams-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java
- amoro-ams/amoro-ams-optimizer/amoro-optimizer-flink/src/main/java/org/apache/amoro/optimizer/flink/FlinkOptimizerExecutor.java
- amoro-ams/amoro-ams-optimizer/amoro-optimizer-spark/src/main/java/org/apache/amoro/optimizer/spark/SparkOptimizerExecutor.java
> [AMORO-3110]extract error message in optimizers

- grafana/README.md
- grafana/dashboard.json
> [AMORO-3131]  Add the grafana dashboard template

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/table/TableSummaryMetrics.java
- amoro-ams/amoro-ams-server/src/test/java/org/apache/amoro/server/table/TestTableSummaryMetrics.java
Fix compile errors brought in by #3109.
- Fix package errors.
> [Hotfix] Fix some compile errors

- amoro-web/src/types/common.type.ts
- amoro-web/src/views/catalogs/Detail.vue
- amoro-web/src/views/tables/components/Selector.vue
**I add optimizingStatus key for IBaseDetailInfo interface. It fixed successfully. Please check screenshot below.**
> [Improvement]: Add missing optimizingStatus key and format code

- .github/workflows/core-hadoop2-ci.yml
- .github/workflows/core-hadoop3-ci.yml
- .github/workflows/trino-ci.yml
GitHub CI workflows did not work as expected due to module changes.
We should fix it.
- Fix GitHub ci configurations
> [Hotfix] Fix github ci due to module changes

- tools/releasing/create_binary_release.sh
Close #3186.
-
executing `sh releasing/create_binary_release.sh` in `tools` dir
> [AMORO-3186] Force check git dir when creating release binary

- pom.xml
Close #3150.
- Bump up curator to 5.7.0
- We also need to upgrade the version of amoro-shade-zookeeper-3
> [AMORO-3150] Bump up curator to 5.7.0

- amoro-ams/src/main/java/org/apache/amoro/server/manager/AbstractPluginManager.java
- dist/src/main/amoro-bin/conf/plugins/metric-reporters.yaml
> [AMORO-3199] Avoid loading the same plugin repeatedly

- amoro-web/src/views/optimize/components/List.vue
fix the dataSource superimposed
Close #3206.
-
> [AMORO-3206] fix the dataSource superimposed

- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonTableDescriptor.java
- pom.xml
Close #3202.
- Upgrade Paimon to 0.9.0
> [AMORO-3202] Upgrade Paimon Version to 0.9.0

- amoro-web/src/language/en.ts
- amoro-web/src/language/zh.ts
- amoro-web/src/views/optimize/components/List.vue
before: 
after: 
fetch data when click the search button to replace fetch data when change the input
Close #3205 .
-
> [AMORO-3205] fetch data when click the search button

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/OverviewCache.java
- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/OptimizingPlanner.java
OverviewCache may throw a null pointer exception when the AMS does not have any tables. 
- As the title
> Fix null pointer exception for OverviewCache

- amoro-ams/src/main/java/org/apache/amoro/server/persistence/mapper/TableMetaMapper.java
When AMS restarts `TableRuntime` can't get tableSummary
- As the title
> [Hotfix] Fix OverviewCache init failed

- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/CommonPartitionEvaluator.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/io/writer/IcebergFanoutPosDeleteWriter.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/utils/TableFileUtil.java
Close #3228.
- Rewrite all pos delete files not written by optimizing process
> [AMORO-3228] Rewrite pos delete files not written by optimizing process

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/OptimizerGroupController.java
- amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java
- amoro-ams/src/main/java/org/apache/amoro/server/table/TableManager.java
> [AMORO-3218] Fix logic for consturct the result of optimizer tables api

- amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
> [AMORO-3242] Fix optimizer keeper unregister npe

- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/plan/OptimizingPlanner.java
> [AMORO-3269] Use actualPartitionPlans to determine the optimizingType

- amoro-ams/src/main/resources/postgres/upgrade-0.7.0-to-0.7.1.sql
- amoro-ams/src/main/resources/postgres/upgrade.sql
Close #3267.
- Fix upgrade script bug
> [AMORO-3267] Fix postgres upgrade script bugs

- dist/src/main/amoro-bin/conf/plugins/metric-reporters.yaml
> [Hotfix] Fix incorrect license

- amoro-web/src/views/optimize/components/List.vue
> [Improvement] Improve the table display on the optimizing tables page

- amoro-web/package.json
- amoro-web/pnpm-lock.yaml
> [AMORO-3291] Remove simple git hooks and lint staged

- dist/pom.xml
- dist/src/main/assemblies/release-bin.xml
Close #3302.
-
`mvn clean package -DskipTests -Pno-plugin-bin`
> [AMORO-3302] Make plugin jar optional for packing

- amoro-ams/amoro-ams-server/pom.xml
- amoro-ams/dist/src/main/assemblies/release-bin.xml
- amoro-core/pom.xml
- amoro-mixed-format/amoro-mixed-format-flink/amoro-mixed-format-flink-common/pom.xml
- amoro-mixed-format/amoro-mixed-format-hive/pom.xml
- pom.xml
> [AMORO-3303] Optimize the final tarball to keep it within the specified size for 0.7

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/TableController.java
Close #3319.
- change tableController#getTableDetail, add null check for tableRuntime 
> [AMORO-3319][Bugfix]: tableRuntime NPE causes table page error

- amoro-web/src/services/table.service.ts
As title.
- fix vue ams get detail of SnapshotId url error
> [hotfix] fix vue ams get detail of SnapshotId url error

- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcess.java
- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/OptimizingProcessMeta.java
- amoro-ams/src/main/java/org/apache/amoro/server/persistence/TableRuntimeMeta.java
- amoro-ams/src/test/java/org/apache/amoro/server/optimizing/BaseOptimizingChecker.java
Replace OptimizingProcess#Status with ProcessStatus.
-
> [hotfix] Replace OptimizingProcess#Status with ProcessStatus.

- amoro-ams/amoro-ams-server/src/main/java/org/apache/amoro/server/persistence/mapper/TableMetaMapper.java
Wrong column name in TableMetaMapper#selectTableRuntimeMetas of branch 0.7.x
Change the column name target_change_napshot_id to target_change_snapshot_id 
> fixup column name in TableMetaMapper#selectTableRuntimeMetas

- README.md
Close #3332.
- Add project home page and mail list in the README
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documente)
> [AMORO-3332] Add homepage info and maillist in the README

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/DashboardServer.java
- amoro-web/package.json
- amoro-web/pnpm-lock.yaml
- amoro-web/src/main.ts
- amoro-web/src/views/login/index.vue
login router fail
link #3274 
-
> fix: login router fail

- LICENSE-binary
Close #3333 .
- Add license for files copied from other repo(bitnami/charts) 
> [AMORO-3333] Include file copied from bitnami/charts into license

- amoro-ams/src/main/java/org/apache/amoro/server/terminal/SparkContextUtil.java
Close #xxx.
- Fixed incorrect use of the paimon catalog
> [hotfix] Fixed incorrect use of the paimon catalog

- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/SchedulingPolicy.java
- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/sorter/BalancedSorter.java
- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/sorter/QuotaOccupySorter.java
- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/sorter/SorterFactory.java
- amoro-ams/src/main/resources/META-INF/services/org.apache.amoro.server.optimizing.sorter.SorterFactory
Close #3382.
Currently, the code requires significant changes when adding a new policy sorter instance in SchedulingPolicy, making it difficult to quickly and easily implement new additions
> [AMORO-3382]Refactor the policy strategy in Amoro's plan module for a plugin-based transformation

- amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/SessionCatalogBase.java
- amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/SparkUnifiedSessionCatalogBase.java
- amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/main/java/org/apache/amoro/spark/mixed/MixedSessionCatalogBase.java
- amoro-format-mixed/amoro-mixed-spark/v3.2/amoro-mixed-spark-3.2/src/main/java/org/apache/amoro/spark/MixedFormatSparkSessionCatalog.java
- amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/src/main/java/org/apache/amoro/spark/SparkUnifiedSessionCatalog.java
**Environment:**
format: mixed_hive/hive
Engine: spark 3.3
Catalog: SparkUnifiedSessionCatalog  with mixed_hive format
**bug:**
Spark SQL cannot recognize a successfully registered Hive UDF
**description**
```
spark-sql> reload jar hdfs:///tmp/spark_udf-1.0-SNAPSHOT.jar;
spark-sql> create function hive_db.StringUdf as 'org.example.udf.StringUdf' using jar 'hdfs:///tmp/spark_udf-1.0-SNAPSHOT.jar';
Error in query: Function 'hive_db.StringUdf' already exists in database 'hive_db'
spark-sql> select id,hive_db.StringUdf(name) from amoro_like;
Error in query: Undefined function: hive_db.StringUdf; line 1 pos 10
spark-sql> select id,hive_db.StringUdf(name) from tbl_schema_chg;
Error in query: Undefined function: hive_db.StringUdf; line 1 pos 10
spark-sql>
```
- fix load_function logic
- Does …
> [AMORO-3385][bug]fix SparkUnifiedSessionCatalog should support load hive function for hive/mixed-hive table

- dist/src/main/amoro-bin/conf/config.yaml
> Hotfix: AMS can't start with default `overview-cache.refresh-interval`

- amoro-ams/src/main/java/org/apache/amoro/server/catalog/DefaultCatalogManager.java
Copy catalog meta for outside usage to prevent unexpected change.
- As titled.
> [Hotfix] Copy catalog meta for outside usage

- amoro-web/src/utils/request.ts
- amoro-web/src/views/catalogs/Detail.vue
> [AMORO-3369] fix download error

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/component/reverser/IcebergTypeToSparkType.java
- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/controller/CatalogController.java
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonTableMetaExtract.java
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonTypeToSparkType.java
fix some code style
Close #xxx.
-
> [Improvement]fix some code style

- docs/admin-guides/deployment.md
- docs/admin-guides/using-customized-encryption-method-for-configurations.md
> [Doc] Add docs for configuring encrypted sensitive configuration items

- CONTRIBUTING.md
- README.md
Close #3480 .
Provide Slack channel
Update CONTRIBUTing.md and README.md
-
> [Amoro-3480] Optimize community contributing docs

- amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
> [AMORO-3490] we got  `sync optimizer groups failed` error in ams-error.log

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/OverviewManager.java
Close #3500.
- Fix Overview table data statistics
> [AMORO-3500] Fix Overview table data statistics

- amoro-ams/pom.xml
- amoro-format-iceberg/pom.xml
- amoro-format-mixed/amoro-mixed-trino/pom.xml
- amoro-metrics/amoro-metrics-prometheus/pom.xml
- amoro-optimizer/amoro-optimizer-flink/pom.xml
- amoro-optimizer/amoro-optimizer-spark/pom.xml
- tools/releasing/create_binary_release.sh
This is an improvement of the releasing stuff before Amoro 0.8.0
- Remove the plugin jars of AMS from the ASF releasing package
- Instead, deploy these jars to the public Maven repo
> [Improvement] Reduce release package size & deploy ams plugins

- amoro-common/src/test/java/org/apache/amoro/utils/MemorySizeTest.java
Aim:
Improve the test code by avoiding code duplication, improving maintainability, and enhancing readability. By converting the test into a parameterized unit test, we reduce boilerplate code, make it easier to extend by simply adding new input values, and improve debugging by clearly identifying which test case fails instead of searching through individual assertions.
- The same method call to `parseBytes` are repeated multiple times with different inputs in the test `testParseBytes` making it harder to maintain and extend.
- When any of these test fails, JUnit only shows which type of assertion failed, but not which specific input caused the failure.
Parameterized `testParseBytes`
This …
> [Improvement]: Refactored MemorySizeTest.testParseBytes to Parameterized Test

- CONTRIBUTING.md
- README.md
This PR changes the joining Slack information to the ASF workspace, due to it providing a complete archiving capability.
- As titled
> [Improvement] Change the joining slack information to the ASF workspace

- amoro-format-iceberg/src/main/java/org/apache/amoro/formats/iceberg/IcebergCatalog.java
Close #3524 .
- wrap 'drop table' action call within metaStore.doAs { ......}
> [AMORO-3524]:fix iceberg catalog 'drop table'  implementation without authentication

- amoro-ams/src/main/java/org/apache/amoro/server/optimizing/maintainer/IcebergTableMaintainer.java
> [AMORO-3515] Improve: format table maintainer log information

- amoro-common/pom.xml
- amoro-format-hudi/pom.xml
- amoro-format-paimon/pom.xml
This PR standardizes the module names with Amoro Project prefix.
> [Improvement] Standardize the module names with Amoro Project prefix

- README.md
- Auto refresh the latest code for deepwiki
> Doc: Add DeepWiki badge to README for auto refresh the wiki weekly with the latest code

- .github/workflows/docker-images.yml
The current Docker image does not have hudi and paimon dependencies. Adding them will improve the user experience.
Close #xxx.
-
> [HotFix] Add paimon and hudi dependency in docker

- amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/plan/AbstractOptimizingPlanner.java
Fix #3545 
This change merges the logic in AbstractOptimizingPlanner to avoid having `actualPartitionPlans` with only unschedulable tasks.
- If yes, how is the feature documented? not applicable
> [AMORO-3545] Prevent empty tasks list during planning

- amoro-ams/src/main/java/org/apache/amoro/server/terminal/SparkContextUtil.java
- amoro-ams/src/main/java/org/apache/amoro/server/terminal/local/LocalSessionFactory.java
- amoro-format-mixed/amoro-mixed-flink/amoro-mixed-flink-common/pom.xml
- amoro-format-mixed/amoro-mixed-spark/amoro-mixed-spark-3-common/src/test/java/org/apache/amoro/spark/test/SparkTestContext.java
- amoro-format-mixed/amoro-mixed-spark/v3.3/amoro-mixed-spark-3.3/pom.xml
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonCatalog.java
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonCatalogFactory.java
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonTableDescriptor.java
- pom.xml
Close #3441.
- bump to paimon 1.1.1
- filter paimon format table in catalog
- edit catalog exist method
> [AMORO-3441] Support Apache Paimon 1.1.1

- amoro-web/src/views/optimize/components/List.vue
Close #3594.
- When the table identifier is long, the full name is displayed
> [AMORO-3594] Improve table identifiers display

- README.md
Fix quickstart URL in the README.
- Fix quickstart URL in the README.
> [HOTFIX]Fix quickstart URL in the README

- amoro-optimizer/amoro-optimizer-spark/src/main/java/org/apache/amoro/optimizer/spark/SparkOptimizer.java
- Fixed the memory display error in Spark optimizer resource allocation.
> Fixed the memory display error in Spark optimizer resource allocation.

- amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
- amoro-optimizer/amoro-optimizer-common/src/main/java/org/apache/amoro/optimizer/common/OptimizerExecutor.java
Close #3637.
- Notify the ams of the completion of the task as long as the task is successfully acknowledged.
> [AMORO-3637] Complete task when optimizer get an exception in task execution

- amoro-format-mixed/amoro-mixed-hive/src/main/java/org/apache/amoro/hive/op/UpdateHiveFiles.java
Close #3684
- Testify if add files exists and ignore creating keep file procedure when no add files when commiting.
> Fix continually creating unused keep_file when committing for an unpartitioned mixed_hive table optimization

- amoro-ams/src/main/java/org/apache/amoro/server/dashboard/utils/OptimizingUtil.java
- amoro-ams/src/test/java/org/apache/amoro/server/dashboard/TestIcebergServerTableDescriptor.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/MetricsSummary.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/optimizing/RewriteStageTask.java
> [AMORO-3692] Remove deprecated metrics and update related logic in MetricsSummary

- amoro-ams/src/test/java/org/apache/amoro/server/AmsEnvironment.java
- amoro-ams/src/test/java/org/apache/amoro/server/RestCatalogServiceTestBase.java
The GitHub CI pipeline occasionally fails. We need to identify the root causes and implement fixes.
-
> [Improvement] Polish codes in AmsEnvironment and fix some errors in GitHub CI

- amoro-ams/src/main/java/org/apache/amoro/server/catalog/CatalogBuilder.java
- amoro-ams/src/main/java/org/apache/amoro/server/catalog/DefaultCatalogManager.java
- amoro-ams/src/test/java/org/apache/amoro/server/table/TestCatalogService.java
Close #3677.
- Set clients for hive catalog if not exists
> [AMORO-3677] Fill catalogProperties in creating catalog rather than building

- amoro-ams/src/main/java/org/apache/amoro/server/catalog/DefaultCatalogManager.java
This PR tried to fix the issue in GitHub CI like:https://github.com/apache/amoro/actions/runs/16739146569/job/47383835389?pr=3644
- As titled.
> [Improvement] Invalidate catalog meta cache after updating

- amoro-common/src/main/java/org/apache/amoro/TableSnapshot.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/formats/iceberg/IcebergSnapshot.java
- amoro-format-iceberg/src/main/java/org/apache/amoro/formats/mixed/MixedSnapshot.java
- amoro-format-paimon/src/main/java/org/apache/amoro/formats/paimon/PaimonSnapshot.java
Close https://github.com/apache/amoro/issues/3734.
Snapshot should provide users with relevant information such as operation and schema, which will bring useful improvements to visualization.
> [AMORO-3734][Improvement]: Add operation/schemaId to Snapshot

- .asf.yaml
Close #3757 .
- Add ml settings for `discussions` in `.asf.yaml`
> [AMORO-3757] Configure ml for discussion to make .asf.yml notification happy

- amoro-ams/src/main/java/org/apache/amoro/server/AmoroServiceContainer.java
- amoro-ams/src/main/java/org/apache/amoro/server/DefaultOptimizingService.java
- amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableRuntime.java
- amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java
- amoro-common/src/main/java/org/apache/amoro/TableRuntime.java
Close #3754 .
- call stop regardless of whether the service is serving
- unregister metric key before registration
> [AMORO-3754]failed to failover when only one node is alive in ha mode #3754

- amoro-ams/src/main/java/org/apache/amoro/server/table/DefaultTableService.java
Close #3803 .
- Complete initialized flag before scheduling explore tables
> [Amoro-3803] Complete initialized flag before scheduling explore tables
